  env:
    matrix:
      - env: TO_TEST=BACKEND TESTS=UNIT
      - env: TO_TEST=BACKEND TESTS=INTEGRATION
  language: python
  python:
    - "3.6"
  services: mysql
  install:
    - ./travis-scripts/install.sh
  before_script:
    - ./travis-scripts/before_script.sh
  script:
    - if [ "$TO_TEST" = "BACKEND" ]; then "coverage run backend/manage.py test api.app.tests.$TESTS"; fi
  notifications:
    email: false
  after_failure:
    - cat /tmp/debug.log
  after_success:
    - coveralls

  jobs:
    include:
      - stage: CodeDeploy Stage
        before_install: skip
        install: skip
        before_script: skip
        script: echo "Deploying to Stage Server..."
        deploy:
          on:
            branch: master
          provider: codedeploy
          revision_type: github
          access_key_id: $TRAVIS_AWS_ACCESS_KEY_ID
          secret_access_key: $TRAVIS_AWS_SECRET_ACCESS_KEY
          application: "ActionPhaseStage"
          deployment_group: "ActionPhaseStage"
          region: "us-east-2"