  env:
    global:
      - COVERALLS_PARALLEL=true
    matrix:
      - BACKEND=1 FRONTEND=0 TESTS=backend
      - BACKEND=0 FRONTEND=1 TESTS=frontend
      - BACKEND=1 FRONTEND=1 TESTS=e2e
  language: python
  python:
    - "3.6"
  services: mysql
  cache:
    directories:
      - ~/.npm
      - ~/.cache
  install:
    - ./travis-scripts/install.sh
  before_script:
    - ./travis-scripts/before_script.sh
  script:
    - if [ "$TESTS" = "backend" ]; then coverage run backend/manage.py test api.app.tests; fi
    - if [ "$TESTS" = "frontend" ]; then cd frontend && yarn test --coverage; fi
    - if [ "$TESTS" = "e2e" ]; then cd frontend && cypress run; fi
  notifications:
    email: false
  after_failure:
    - cat /tmp/debug.log
  after_success:
    - codecov
  addons:
    apt:
      packages:
        - xvfb
    artifacts:
      target_paths: $TRAVIS_BUILD_NUMBER
      bucket: actionphase-artifacts
      s3_region: us-east-1
      paths:
        - /home/travis/build/jhouser/actionphase/frontend/cypress/videos/

  jobs:
    include:
      - stage: CodeDeploy Stage
        before_install: skip
        install: skip
        before_script: skip
        script: echo "Deploying to Stage Server..."
        deploy:
          on:
            branch: master
          provider: codedeploy
          revision_type: github
          access_key_id: $TRAVIS_AWS_ACCESS_KEY_ID
          secret_access_key: $TRAVIS_AWS_SECRET_ACCESS_KEY
          application: "ActionPhaseStage"
          deployment_group: "ActionPhaseStage"
          region: "us-east-2"