  env:
    global:
      - COVERALLS_PARALLEL=true
    matrix:
      - TO_TEST=BACKEND TESTS=unit
      - TO_TEST=BACKEND TESTS=integration
      - TO_TEST=FRONTEND TESTS=unit
      - TO_TEST=FRONTEND TESTS=e2e
  language: python
  python:
    - "3.6"
  services: mysql
  cache:
    directories:
      - ~/.npm
      - ~/.cache
  install:
    - ./travis-scripts/install.sh
  before_script:
    - ./travis-scripts/before_script.sh
  script:
    - if [ "$TO_TEST" = "BACKEND" ]; then coverage run backend/manage.py test api.app.tests.$TESTS; fi
    - if [ "$TO_TEST" = "FRONTEND" ] && [ "$TESTS" = "unit" ]; then cd frontend && yarn test --coverage; fi
    - if [ "$TO_TEST" = "FRONTEND" ] && [ "$TESTS" = "e2e" ]; then cd frontend && npm run cypress:run cypress/tests; fi
  notifications:
    email: false
  after_failure:
    - cat /tmp/debug.log
  after_success:
    - codecov

  jobs:
    include:
      - stage: CodeDeploy Stage
        before_install: skip
        install: skip
        before_script: skip
        script: echo "Deploying to Stage Server..."
        deploy:
          on:
            branch: master
          provider: codedeploy
          revision_type: github
          access_key_id: $TRAVIS_AWS_ACCESS_KEY_ID
          secret_access_key: $TRAVIS_AWS_SECRET_ACCESS_KEY
          application: "ActionPhaseStage"
          deployment_group: "ActionPhaseStage"
          region: "us-east-2"