// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community_bans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCommunityBan = `-- name: CreateCommunityBan :one

INSERT INTO community_bans (
    community_id, user_id, reason, banned_by_user_id, expires_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (community_id, user_id) DO UPDATE SET
    reason            = EXCLUDED.reason,
    banned_by_user_id = EXCLUDED.banned_by_user_id,
    expires_at        = EXCLUDED.expires_at,
    banned_at         = NOW()
RETURNING id, community_id, user_id, reason, banned_by_user_id, banned_at, expires_at
`

type CreateCommunityBanParams struct {
	CommunityID    int32              `json:"community_id"`
	UserID         int32              `json:"user_id"`
	Reason         pgtype.Text        `json:"reason"`
	BannedByUserID pgtype.Int4        `json:"banned_by_user_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

// Community bans and their audit log.
//
// 🔴 EVERY read that answers "is this user banned right now" MUST carry the
// expiry test: (expires_at IS NULL OR expires_at > NOW()). An expired row stays
// in the table -- it is history, and lifting it is a separate deliberate act --
// so a query that omits the test silently enforces bans that have lapsed.
// Bans a user, or updates the existing ban if one is already recorded.
//
// UPSERT rather than INSERT because UNIQUE(community_id, user_id) means a
// moderator re-banning an already-banned user would otherwise get a constraint
// violation. Re-banning is the natural way to change a reason or extend an
// expiry, so it updates in place. banned_at is refreshed too: the new decision
// is the one that counts.
func (q *Queries) CreateCommunityBan(ctx context.Context, arg CreateCommunityBanParams) (CommunityBan, error) {
	row := q.db.QueryRow(ctx, createCommunityBan,
		arg.CommunityID,
		arg.UserID,
		arg.Reason,
		arg.BannedByUserID,
		arg.ExpiresAt,
	)
	var i CommunityBan
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.UserID,
		&i.Reason,
		&i.BannedByUserID,
		&i.BannedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createCommunityBanEvent = `-- name: CreateCommunityBanEvent :one
INSERT INTO community_ban_events (
    community_id, target_user_id, actor_user_id, action, reason, expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, community_id, target_user_id, actor_user_id, action, reason, expires_at, created_at
`

type CreateCommunityBanEventParams struct {
	CommunityID  int32              `json:"community_id"`
	TargetUserID int32              `json:"target_user_id"`
	ActorUserID  pgtype.Int4        `json:"actor_user_id"`
	Action       string             `json:"action"`
	Reason       pgtype.Text        `json:"reason"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

// Appends to the audit log. Values are SNAPSHOTS, not references: by the time
// an 'unbanned' event is read its ban row no longer exists.
func (q *Queries) CreateCommunityBanEvent(ctx context.Context, arg CreateCommunityBanEventParams) (CommunityBanEvent, error) {
	row := q.db.QueryRow(ctx, createCommunityBanEvent,
		arg.CommunityID,
		arg.TargetUserID,
		arg.ActorUserID,
		arg.Action,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i CommunityBanEvent
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.TargetUserID,
		&i.ActorUserID,
		&i.Action,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCommunityBan = `-- name: DeleteCommunityBan :one
DELETE FROM community_bans
WHERE community_id = $1 AND user_id = $2
RETURNING id, community_id, user_id, reason, banned_by_user_id, banned_at, expires_at
`

type DeleteCommunityBanParams struct {
	CommunityID int32 `json:"community_id"`
	UserID      int32 `json:"user_id"`
}

// Lifts a ban. Returns the deleted row so the caller can snapshot its values
// into an 'unbanned' audit event -- after this the row is gone, and the log is
// the only remaining record of what the ban said.
func (q *Queries) DeleteCommunityBan(ctx context.Context, arg DeleteCommunityBanParams) (CommunityBan, error) {
	row := q.db.QueryRow(ctx, deleteCommunityBan, arg.CommunityID, arg.UserID)
	var i CommunityBan
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.UserID,
		&i.Reason,
		&i.BannedByUserID,
		&i.BannedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCommunityBan = `-- name: GetCommunityBan :one
SELECT id, community_id, user_id, reason, banned_by_user_id, banned_at, expires_at FROM community_bans
WHERE community_id = $1 AND user_id = $2
`

type GetCommunityBanParams struct {
	CommunityID int32 `json:"community_id"`
	UserID      int32 `json:"user_id"`
}

// Fetches one ban row REGARDLESS of expiry, for management surfaces that need
// to show an expired ban still sitting on the list. Not for enforcement.
func (q *Queries) GetCommunityBan(ctx context.Context, arg GetCommunityBanParams) (CommunityBan, error) {
	row := q.db.QueryRow(ctx, getCommunityBan, arg.CommunityID, arg.UserID)
	var i CommunityBan
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.UserID,
		&i.Reason,
		&i.BannedByUserID,
		&i.BannedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const isUserBannedFromCommunity = `-- name: IsUserBannedFromCommunity :one
SELECT EXISTS(
    SELECT 1 FROM community_bans
    WHERE community_id = $1
      AND user_id = $2
      AND (expires_at IS NULL OR expires_at > NOW())
) AS banned
`

type IsUserBannedFromCommunityParams struct {
	CommunityID int32 `json:"community_id"`
	UserID      int32 `json:"user_id"`
}

// The enforcement primitive. Carries the expiry test.
func (q *Queries) IsUserBannedFromCommunity(ctx context.Context, arg IsUserBannedFromCommunityParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserBannedFromCommunity, arg.CommunityID, arg.UserID)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const isUserBannedFromGameCommunity = `-- name: IsUserBannedFromGameCommunity :one
SELECT EXISTS(
    SELECT 1
    FROM games g
    JOIN community_bans cb ON cb.community_id = g.community_id
    WHERE g.id = $1
      AND cb.user_id = $2
      AND (cb.expires_at IS NULL OR cb.expires_at > NOW())
) AS banned
`

type IsUserBannedFromGameCommunityParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

// Enforcement for a path that knows a game but not a community.
//
// The join is INNER on communities via games.community_id, so a game with
// community_id IS NULL produces no row and EXISTS is false. That is the
// grandfathering guarantee expressed in SQL: a legacy game is never blocked,
// and it holds here rather than depending on every caller remembering to check.
func (q *Queries) IsUserBannedFromGameCommunity(ctx context.Context, arg IsUserBannedFromGameCommunityParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserBannedFromGameCommunity, arg.GameID, arg.UserID)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const listBannedCommunityIDsForUser = `-- name: ListBannedCommunityIDsForUser :many
SELECT community_id FROM community_bans
WHERE user_id = $1
  AND (expires_at IS NULL OR expires_at > NOW())
`

// Every community the user is currently banned from, for filtering the
// community picker on game creation. Carries the expiry test.
func (q *Queries) ListBannedCommunityIDsForUser(ctx context.Context, userID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, listBannedCommunityIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var community_id int32
		if err := rows.Scan(&community_id); err != nil {
			return nil, err
		}
		items = append(items, community_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityBanEvents = `-- name: ListCommunityBanEvents :many
SELECT
    e.id, e.community_id, e.target_user_id, e.actor_user_id, e.action, e.reason, e.expires_at, e.created_at,
    t.username AS target_username,
    a.username AS actor_username
FROM community_ban_events e
LEFT JOIN users t ON t.id = e.target_user_id
LEFT JOIN users a ON a.id = e.actor_user_id
WHERE e.community_id = $1
ORDER BY e.created_at DESC, e.id DESC
LIMIT $2 OFFSET $3
`

type ListCommunityBanEventsParams struct {
	CommunityID int32 `json:"community_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

type ListCommunityBanEventsRow struct {
	ID             int32              `json:"id"`
	CommunityID    int32              `json:"community_id"`
	TargetUserID   int32              `json:"target_user_id"`
	ActorUserID    pgtype.Int4        `json:"actor_user_id"`
	Action         string             `json:"action"`
	Reason         pgtype.Text        `json:"reason"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TargetUsername pgtype.Text        `json:"target_username"`
	ActorUsername  pgtype.Text        `json:"actor_username"`
}

// The audit log for one community, newest first.
//
// Usernames come from a LEFT JOIN on both sides: actor_user_id is nullable
// (ON DELETE SET NULL, so a deleted moderator's events survive with no actor),
// and the target user may likewise be gone. The event must still render.
func (q *Queries) ListCommunityBanEvents(ctx context.Context, arg ListCommunityBanEventsParams) ([]ListCommunityBanEventsRow, error) {
	rows, err := q.db.Query(ctx, listCommunityBanEvents, arg.CommunityID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommunityBanEventsRow
	for rows.Next() {
		var i ListCommunityBanEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.TargetUserID,
			&i.ActorUserID,
			&i.Action,
			&i.Reason,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.TargetUsername,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityBans = `-- name: ListCommunityBans :many
SELECT
    cb.id, cb.community_id, cb.user_id, cb.reason, cb.banned_by_user_id, cb.banned_at, cb.expires_at,
    u.username     AS username,
    u.display_name AS display_name,
    u.avatar_url   AS avatar_url,
    b.username     AS banned_by_username
FROM community_bans cb
JOIN users u ON u.id = cb.user_id
LEFT JOIN users b ON b.id = cb.banned_by_user_id
WHERE cb.community_id = $1
ORDER BY cb.banned_at DESC
`

type ListCommunityBansRow struct {
	ID               int32              `json:"id"`
	CommunityID      int32              `json:"community_id"`
	UserID           int32              `json:"user_id"`
	Reason           pgtype.Text        `json:"reason"`
	BannedByUserID   pgtype.Int4        `json:"banned_by_user_id"`
	BannedAt         pgtype.Timestamptz `json:"banned_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Username         string             `json:"username"`
	DisplayName      pgtype.Text        `json:"display_name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	BannedByUsername pgtype.Text        `json:"banned_by_username"`
}

// The management view. Returns EXPIRED bans too, ordered newest first, so a
// moderator can see that a temporary ban has lapsed rather than watching it
// vanish from the list with no explanation. Callers render expiry state from
// expires_at.
func (q *Queries) ListCommunityBans(ctx context.Context, communityID int32) ([]ListCommunityBansRow, error) {
	rows, err := q.db.Query(ctx, listCommunityBans, communityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommunityBansRow
	for rows.Next() {
		var i ListCommunityBansRow
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.UserID,
			&i.Reason,
			&i.BannedByUserID,
			&i.BannedAt,
			&i.ExpiresAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.BannedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
