// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: communications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationParticipant = `-- name: AddConversationParticipant :one
INSERT INTO conversation_participants (conversation_id, user_id, character_id)
VALUES ($1, $2, $3)
ON CONFLICT (conversation_id, user_id, character_id) DO NOTHING
RETURNING id, conversation_id, user_id, character_id, joined_at, last_read_at
`

type AddConversationParticipantParams struct {
	ConversationID int32       `json:"conversation_id"`
	UserID         int32       `json:"user_id"`
	CharacterID    pgtype.Int4 `json:"character_id"`
}

func (q *Queries) AddConversationParticipant(ctx context.Context, arg AddConversationParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRow(ctx, addConversationParticipant, arg.ConversationID, arg.UserID, arg.CharacterID)
	var i ConversationParticipant
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.CharacterID,
		&i.JoinedAt,
		&i.LastReadAt,
	)
	return i, err
}

const countCharacterPostsAndComments = `-- name: CountCharacterPostsAndComments :one
SELECT COUNT(*) as total
FROM messages m
JOIN characters c ON m.character_id = c.id
WHERE m.character_id = $1
  AND m.visibility = 'game'
  AND m.is_deleted = false
  AND m.deleted_at IS NULL
  AND NOT (c.character_type = 'npc' AND m.message_type = 'post')
`

// Count all public non-deleted posts and comments by a character
// NPCs only count comments (not top-level posts)
func (q *Queries) CountCharacterPostsAndComments(ctx context.Context, characterID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countCharacterPostsAndComments, characterID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (game_id, conversation_type, title, created_by_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, game_id, conversation_type, title, created_by_user_id, created_at, updated_at
`

type CreateConversationParams struct {
	GameID           int32       `json:"game_id"`
	ConversationType string      `json:"conversation_type"`
	Title            pgtype.Text `json:"title"`
	CreatedByUserID  int32       `json:"created_by_user_id"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.GameID,
		arg.ConversationType,
		arg.Title,
		arg.CreatedByUserID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.ConversationType,
		&i.Title,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO threads (game_id, phase_id, created_by_user_id, title, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, game_id, phase_id, title, content, created_by_user_id, is_pinned, created_at, updated_at
`

type CreateThreadParams struct {
	GameID          int32       `json:"game_id"`
	PhaseID         pgtype.Int4 `json:"phase_id"`
	CreatedByUserID int32       `json:"created_by_user_id"`
	Title           string      `json:"title"`
	Content         pgtype.Text `json:"content"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.GameID,
		arg.PhaseID,
		arg.CreatedByUserID,
		arg.Title,
		arg.Content,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.Title,
		&i.Content,
		&i.CreatedByUserID,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createThreadPost = `-- name: CreateThreadPost :one
INSERT INTO thread_posts (thread_id, parent_post_id, user_id, character_id, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, thread_id, parent_post_id, user_id, character_id, content, created_at, updated_at
`

type CreateThreadPostParams struct {
	ThreadID     int32       `json:"thread_id"`
	ParentPostID pgtype.Int4 `json:"parent_post_id"`
	UserID       int32       `json:"user_id"`
	CharacterID  pgtype.Int4 `json:"character_id"`
	Content      string      `json:"content"`
}

func (q *Queries) CreateThreadPost(ctx context.Context, arg CreateThreadPostParams) (ThreadPost, error) {
	row := q.db.QueryRow(ctx, createThreadPost,
		arg.ThreadID,
		arg.ParentPostID,
		arg.UserID,
		arg.CharacterID,
		arg.Content,
	)
	var i ThreadPost
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ParentPostID,
		&i.UserID,
		&i.CharacterID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :exec
DELETE FROM threads WHERE id = $1
`

func (q *Queries) DeleteThread(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteThread, id)
	return err
}

const deleteThreadPost = `-- name: DeleteThreadPost :exec
DELETE FROM thread_posts WHERE id = $1
`

func (q *Queries) DeleteThreadPost(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteThreadPost, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, game_id, conversation_type, title, created_by_user_id, created_at, updated_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id int32) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.ConversationType,
		&i.Title,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT pm.id,
       pm.conversation_id,
       pm.sender_user_id,
       pm.sender_character_id,
       pm.content,
       pm.created_at,
       pm.updated_at,
       pm.deleted_at,
       pm.is_deleted,
       pm.is_edited,
       pm.edited_at,
       pm.edit_count,
       u.username as sender_username,
       c.name as sender_character_name,
       c.avatar_url as sender_avatar_url
FROM private_messages pm
JOIN users u ON pm.sender_user_id = u.id
LEFT JOIN characters c ON pm.sender_character_id = c.id
WHERE pm.conversation_id = $1
ORDER BY pm.created_at
`

type GetConversationMessagesRow struct {
	ID                  int32              `json:"id"`
	ConversationID      int32              `json:"conversation_id"`
	SenderUserID        int32              `json:"sender_user_id"`
	SenderCharacterID   pgtype.Int4        `json:"sender_character_id"`
	Content             string             `json:"content"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	IsDeleted           pgtype.Bool        `json:"is_deleted"`
	IsEdited            bool               `json:"is_edited"`
	EditedAt            pgtype.Timestamptz `json:"edited_at"`
	EditCount           int32              `json:"edit_count"`
	SenderUsername      string             `json:"sender_username"`
	SenderCharacterName pgtype.Text        `json:"sender_character_name"`
	SenderAvatarUrl     pgtype.Text        `json:"sender_avatar_url"`
}

func (q *Queries) GetConversationMessages(ctx context.Context, conversationID int32) ([]GetConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, getConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesRow
	for rows.Next() {
		var i GetConversationMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderUserID,
			&i.SenderCharacterID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsDeleted,
			&i.IsEdited,
			&i.EditedAt,
			&i.EditCount,
			&i.SenderUsername,
			&i.SenderCharacterName,
			&i.SenderAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationParticipants = `-- name: GetConversationParticipants :many
SELECT cp.id, cp.conversation_id, cp.user_id, cp.character_id, cp.joined_at, cp.last_read_at, u.username, c.name as character_name
FROM conversation_participants cp
JOIN users u ON cp.user_id = u.id
LEFT JOIN characters c ON cp.character_id = c.id
WHERE cp.conversation_id = $1
ORDER BY cp.joined_at
`

type GetConversationParticipantsRow struct {
	ID             int32              `json:"id"`
	ConversationID int32              `json:"conversation_id"`
	UserID         int32              `json:"user_id"`
	CharacterID    pgtype.Int4        `json:"character_id"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	LastReadAt     pgtype.Timestamptz `json:"last_read_at"`
	Username       string             `json:"username"`
	CharacterName  pgtype.Text        `json:"character_name"`
}

func (q *Queries) GetConversationParticipants(ctx context.Context, conversationID int32) ([]GetConversationParticipantsRow, error) {
	rows, err := q.db.Query(ctx, getConversationParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationParticipantsRow
	for rows.Next() {
		var i GetConversationParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.CharacterID,
			&i.JoinedAt,
			&i.LastReadAt,
			&i.Username,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameThreads = `-- name: GetGameThreads :many
SELECT t.id, t.game_id, t.phase_id, t.title, t.content, t.created_by_user_id, t.is_pinned, t.created_at, t.updated_at, u.username as creator_username,
       (SELECT COUNT(*) FROM thread_posts WHERE thread_id = t.id) as post_count
FROM threads t
JOIN users u ON t.created_by_user_id = u.id
WHERE t.game_id = $1
ORDER BY t.is_pinned DESC, t.updated_at DESC
`

type GetGameThreadsRow struct {
	ID              int32              `json:"id"`
	GameID          int32              `json:"game_id"`
	PhaseID         pgtype.Int4        `json:"phase_id"`
	Title           string             `json:"title"`
	Content         pgtype.Text        `json:"content"`
	CreatedByUserID int32              `json:"created_by_user_id"`
	IsPinned        pgtype.Bool        `json:"is_pinned"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatorUsername string             `json:"creator_username"`
	PostCount       int64              `json:"post_count"`
}

func (q *Queries) GetGameThreads(ctx context.Context, gameID int32) ([]GetGameThreadsRow, error) {
	rows, err := q.db.Query(ctx, getGameThreads, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameThreadsRow
	for rows.Next() {
		var i GetGameThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.Title,
			&i.Content,
			&i.CreatedByUserID,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorUsername,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhaseThreads = `-- name: GetPhaseThreads :many
SELECT t.id, t.game_id, t.phase_id, t.title, t.content, t.created_by_user_id, t.is_pinned, t.created_at, t.updated_at, u.username as creator_username,
       (SELECT COUNT(*) FROM thread_posts WHERE thread_id = t.id) as post_count
FROM threads t
JOIN users u ON t.created_by_user_id = u.id
WHERE t.phase_id = $1
ORDER BY t.is_pinned DESC, t.updated_at DESC
`

type GetPhaseThreadsRow struct {
	ID              int32              `json:"id"`
	GameID          int32              `json:"game_id"`
	PhaseID         pgtype.Int4        `json:"phase_id"`
	Title           string             `json:"title"`
	Content         pgtype.Text        `json:"content"`
	CreatedByUserID int32              `json:"created_by_user_id"`
	IsPinned        pgtype.Bool        `json:"is_pinned"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatorUsername string             `json:"creator_username"`
	PostCount       int64              `json:"post_count"`
}

func (q *Queries) GetPhaseThreads(ctx context.Context, phaseID pgtype.Int4) ([]GetPhaseThreadsRow, error) {
	rows, err := q.db.Query(ctx, getPhaseThreads, phaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhaseThreadsRow
	for rows.Next() {
		var i GetPhaseThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.Title,
			&i.Content,
			&i.CreatedByUserID,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorUsername,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrivateMessage = `-- name: GetPrivateMessage :one
SELECT id, conversation_id, sender_user_id, sender_character_id, content, created_at, updated_at, deleted_at, is_deleted, is_edited, edited_at, edit_count FROM private_messages WHERE id = $1
`

func (q *Queries) GetPrivateMessage(ctx context.Context, id int32) (PrivateMessage, error) {
	row := q.db.QueryRow(ctx, getPrivateMessage, id)
	var i PrivateMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.SenderCharacterID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDeleted,
		&i.IsEdited,
		&i.EditedAt,
		&i.EditCount,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT t.id, t.game_id, t.phase_id, t.title, t.content, t.created_by_user_id, t.is_pinned, t.created_at, t.updated_at, u.username as creator_username
FROM threads t
JOIN users u ON t.created_by_user_id = u.id
WHERE t.id = $1
`

type GetThreadRow struct {
	ID              int32              `json:"id"`
	GameID          int32              `json:"game_id"`
	PhaseID         pgtype.Int4        `json:"phase_id"`
	Title           string             `json:"title"`
	Content         pgtype.Text        `json:"content"`
	CreatedByUserID int32              `json:"created_by_user_id"`
	IsPinned        pgtype.Bool        `json:"is_pinned"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatorUsername string             `json:"creator_username"`
}

func (q *Queries) GetThread(ctx context.Context, id int32) (GetThreadRow, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i GetThreadRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.Title,
		&i.Content,
		&i.CreatedByUserID,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorUsername,
	)
	return i, err
}

const getThreadPost = `-- name: GetThreadPost :one
SELECT tp.id, tp.thread_id, tp.parent_post_id, tp.user_id, tp.character_id, tp.content, tp.created_at, tp.updated_at, u.username, c.name as character_name
FROM thread_posts tp
JOIN users u ON tp.user_id = u.id
LEFT JOIN characters c ON tp.character_id = c.id
WHERE tp.id = $1
`

type GetThreadPostRow struct {
	ID            int32              `json:"id"`
	ThreadID      int32              `json:"thread_id"`
	ParentPostID  pgtype.Int4        `json:"parent_post_id"`
	UserID        int32              `json:"user_id"`
	CharacterID   pgtype.Int4        `json:"character_id"`
	Content       string             `json:"content"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Username      string             `json:"username"`
	CharacterName pgtype.Text        `json:"character_name"`
}

func (q *Queries) GetThreadPost(ctx context.Context, id int32) (GetThreadPostRow, error) {
	row := q.db.QueryRow(ctx, getThreadPost, id)
	var i GetThreadPostRow
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ParentPostID,
		&i.UserID,
		&i.CharacterID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.CharacterName,
	)
	return i, err
}

const getThreadPosts = `-- name: GetThreadPosts :many
SELECT tp.id, tp.thread_id, tp.parent_post_id, tp.user_id, tp.character_id, tp.content, tp.created_at, tp.updated_at, u.username, c.name as character_name
FROM thread_posts tp
JOIN users u ON tp.user_id = u.id
LEFT JOIN characters c ON tp.character_id = c.id
WHERE tp.thread_id = $1
ORDER BY tp.created_at
`

type GetThreadPostsRow struct {
	ID            int32              `json:"id"`
	ThreadID      int32              `json:"thread_id"`
	ParentPostID  pgtype.Int4        `json:"parent_post_id"`
	UserID        int32              `json:"user_id"`
	CharacterID   pgtype.Int4        `json:"character_id"`
	Content       string             `json:"content"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Username      string             `json:"username"`
	CharacterName pgtype.Text        `json:"character_name"`
}

func (q *Queries) GetThreadPosts(ctx context.Context, threadID int32) ([]GetThreadPostsRow, error) {
	rows, err := q.db.Query(ctx, getThreadPosts, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetThreadPostsRow
	for rows.Next() {
		var i GetThreadPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.ParentPostID,
			&i.UserID,
			&i.CharacterID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalCommentCount = `-- name: GetTotalCommentCount :one
SELECT COUNT(*) as total
FROM messages
WHERE game_id = $1
  AND message_type = 'comment'
  AND is_deleted = false
  AND deleted_at IS NULL
`

// Get total count of comments in a game
func (q *Queries) GetTotalCommentCount(ctx context.Context, gameID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalCommentCount, gameID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getTotalUnreadCommentCount = `-- name: GetTotalUnreadCommentCount :one
SELECT COUNT(*) as total
FROM messages m
WHERE m.game_id = $1
  AND m.message_type = 'comment'
  AND m.is_deleted = false
  AND m.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM user_comment_reads ucr
      WHERE ucr.comment_id = m.id AND ucr.user_id = $2
  )
`

type GetTotalUnreadCommentCountParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

// Count of comments in a game the user has not manually marked as read
func (q *Queries) GetTotalUnreadCommentCount(ctx context.Context, arg GetTotalUnreadCommentCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalUnreadCommentCount, arg.GameID, arg.UserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getUnreadMessageCount = `-- name: GetUnreadMessageCount :one
SELECT COUNT(*)
FROM private_messages pm
WHERE pm.conversation_id = $2
  AND pm.created_at > COALESCE(
    (SELECT last_read_at FROM conversation_reads WHERE user_id = $1 AND conversation_id = $2),
    '1970-01-01'::timestamptz
  )
  AND pm.sender_user_id != $1
`

type GetUnreadMessageCountParams struct {
	UserID         int32 `json:"user_id"`
	ConversationID int32 `json:"conversation_id"`
}

func (q *Queries) GetUnreadMessageCount(ctx context.Context, arg GetUnreadMessageCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadMessageCount, arg.UserID, arg.ConversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserConversations = `-- name: GetUserConversations :many
SELECT c.id, c.game_id, c.conversation_type, c.title, c.created_by_user_id, c.created_at, c.updated_at,
       (SELECT COUNT(*) FROM conversation_participants WHERE conversation_id = c.id) as participant_count,
       COALESCE(lm.last_message, '') as last_message,
       lm.last_message_at,
       COALESCE(
           (SELECT STRING_AGG(name, ', ')
            FROM (
                SELECT DISTINCT chars.name
                FROM conversation_participants cps
                LEFT JOIN characters chars ON cps.character_id = chars.id
                LEFT JOIN games g ON c.game_id = g.id
                WHERE cps.conversation_id = c.id
                  AND chars.id IS NOT NULL
                  AND (
                      -- GM sees all participants
                      g.gm_user_id = $1
                      -- Non-GM sees only other people's characters
                      OR (chars.user_id IS NOT NULL AND chars.user_id != $1)
                      -- Non-GM sees NPCs (characters without user_id)
                      OR chars.user_id IS NULL
                  )
                ORDER BY chars.name
            ) unique_participants),
           ''
       )::text as participant_names,
       COALESCE(
           (SELECT COUNT(*)
            FROM private_messages pm
            WHERE pm.conversation_id = c.id
              AND pm.created_at > COALESCE(cr.last_read_at, '1970-01-01'::timestamptz)),
           0
       )::bigint as unread_count,
       cr.last_read_message_id,
       cr.last_read_at
FROM conversations c
JOIN conversation_participants cp ON c.id = cp.conversation_id
LEFT JOIN conversation_reads cr ON c.id = cr.conversation_id AND cr.user_id = $1
LEFT JOIN LATERAL (
    SELECT content as last_message, created_at as last_message_at
    FROM private_messages
    WHERE conversation_id = c.id
      AND is_deleted = false
      AND deleted_at IS NULL
    ORDER BY created_at DESC
    LIMIT 1
) lm ON true
WHERE cp.user_id = $1 AND c.game_id = $2
ORDER BY COALESCE(
    (SELECT COUNT(*)
     FROM private_messages pm
     WHERE pm.conversation_id = c.id
       AND pm.created_at > COALESCE(cr.last_read_at, '1970-01-01'::timestamptz)),
    0
)::bigint DESC NULLS LAST, c.updated_at DESC
`

type GetUserConversationsParams struct {
	GmUserID int32 `json:"gm_user_id"`
	GameID   int32 `json:"game_id"`
}

type GetUserConversationsRow struct {
	ID                int32              `json:"id"`
	GameID            int32              `json:"game_id"`
	ConversationType  string             `json:"conversation_type"`
	Title             pgtype.Text        `json:"title"`
	CreatedByUserID   int32              `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ParticipantCount  int64              `json:"participant_count"`
	LastMessage       string             `json:"last_message"`
	LastMessageAt     pgtype.Timestamptz `json:"last_message_at"`
	ParticipantNames  string             `json:"participant_names"`
	UnreadCount       int64              `json:"unread_count"`
	LastReadMessageID pgtype.Int4        `json:"last_read_message_id"`
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
}

func (q *Queries) GetUserConversations(ctx context.Context, arg GetUserConversationsParams) ([]GetUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, getUserConversations, arg.GmUserID, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserConversationsRow
	for rows.Next() {
		var i GetUserConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.ConversationType,
			&i.Title,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantCount,
			&i.LastMessage,
			&i.LastMessageAt,
			&i.ParticipantNames,
			&i.UnreadCount,
			&i.LastReadMessageID,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUnreadConversations = `-- name: GetUserUnreadConversations :many
SELECT c.id, c.game_id, c.conversation_type, c.title, c.created_by_user_id, c.created_at, c.updated_at,
       (SELECT COUNT(*) FROM conversation_participants WHERE conversation_id = c.id) as participant_count,
       COALESCE(lm.last_message, '') as last_message,
       lm.last_message_at,
       COALESCE(
           (SELECT STRING_AGG(name, ', ')
            FROM (
                SELECT DISTINCT chars.name
                FROM conversation_participants cps
                LEFT JOIN characters chars ON cps.character_id = chars.id
                LEFT JOIN games g ON c.game_id = g.id
                WHERE cps.conversation_id = c.id
                  AND chars.id IS NOT NULL
                  AND (
                      g.gm_user_id = $1
                      OR (chars.user_id IS NOT NULL AND chars.user_id != $1)
                      OR chars.user_id IS NULL
                  )
                ORDER BY chars.name
            ) unique_participants),
           ''
       )::text as participant_names,
       unread.unread_count::bigint,
       cr.last_read_message_id,
       cr.last_read_at
FROM conversations c
JOIN conversation_participants cp ON c.id = cp.conversation_id
LEFT JOIN conversation_reads cr ON c.id = cr.conversation_id AND cr.user_id = $1
LEFT JOIN LATERAL (
    SELECT content as last_message, created_at as last_message_at
    FROM private_messages
    WHERE conversation_id = c.id
      AND is_deleted = false
      AND deleted_at IS NULL
    ORDER BY created_at DESC
    LIMIT 1
) lm ON true
LEFT JOIN LATERAL (
    SELECT COUNT(*) as unread_count
    FROM private_messages pm
    WHERE pm.conversation_id = c.id
      AND pm.created_at > COALESCE(cr.last_read_at, '1970-01-01'::timestamptz)
      AND pm.sender_user_id != $1
) unread ON true
WHERE cp.user_id = $1
  AND c.game_id = $2
  AND unread.unread_count > 0
ORDER BY unread.unread_count DESC, c.updated_at DESC
LIMIT $3
`

type GetUserUnreadConversationsParams struct {
	UserID     int32 `json:"user_id"`
	GameID     int32 `json:"game_id"`
	MaxResults int32 `json:"max_results"`
}

type GetUserUnreadConversationsRow struct {
	ID                int32              `json:"id"`
	GameID            int32              `json:"game_id"`
	ConversationType  string             `json:"conversation_type"`
	Title             pgtype.Text        `json:"title"`
	CreatedByUserID   int32              `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ParticipantCount  int64              `json:"participant_count"`
	LastMessage       string             `json:"last_message"`
	LastMessageAt     pgtype.Timestamptz `json:"last_message_at"`
	ParticipantNames  string             `json:"participant_names"`
	UnreadUnreadCount int64              `json:"unread_unread_count"`
	LastReadMessageID pgtype.Int4        `json:"last_read_message_id"`
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
}

// Get conversations with unread messages for a user in a game, capped at a limit.
// Used by the dashboard PM preview to avoid fetching the full conversation list.
func (q *Queries) GetUserUnreadConversations(ctx context.Context, arg GetUserUnreadConversationsParams) ([]GetUserUnreadConversationsRow, error) {
	rows, err := q.db.Query(ctx, getUserUnreadConversations, arg.UserID, arg.GameID, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserUnreadConversationsRow
	for rows.Next() {
		var i GetUserUnreadConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.ConversationType,
			&i.Title,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantCount,
			&i.LastMessage,
			&i.LastMessageAt,
			&i.ParticipantNames,
			&i.UnreadUnreadCount,
			&i.LastReadMessageID,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserInConversation = `-- name: IsUserInConversation :one
SELECT EXISTS(
    SELECT 1 FROM conversation_participants
    WHERE conversation_id = $1 AND user_id = $2
)
`

type IsUserInConversationParams struct {
	ConversationID int32 `json:"conversation_id"`
	UserID         int32 `json:"user_id"`
}

func (q *Queries) IsUserInConversation(ctx context.Context, arg IsUserInConversationParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInConversation, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCharacterPostsAndComments = `-- name: ListCharacterPostsAndComments :many
WITH character_messages AS (
    SELECT
        m.id,
        m.game_id,
        m.parent_id,
        m.author_id,
        m.character_id,
        m.content,
        m.message_type,
        m.created_at,
        m.edited_at,
        m.edit_count,
        m.deleted_at,
        m.is_deleted,
        u.username as author_username,
        c.name as character_name,
        c.avatar_url as character_avatar_url
    FROM messages m
    JOIN users u ON m.author_id = u.id
    JOIN characters c ON m.character_id = c.id
    WHERE m.character_id = $1
      AND m.visibility = 'game'
      AND m.is_deleted = false
      AND m.deleted_at IS NULL
      AND NOT (c.character_type = 'npc' AND m.message_type = 'post')
    ORDER BY m.created_at DESC
    LIMIT $2 OFFSET $3
),
parent_messages AS (
    SELECT
        m.id,
        m.content,
        m.created_at,
        m.deleted_at,
        m.is_deleted,
        m.message_type,
        u.username as author_username,
        c.name as character_name,
        c.avatar_url as character_avatar_url
    FROM messages m
    JOIN users u ON m.author_id = u.id
    LEFT JOIN characters c ON m.character_id = c.id
    WHERE m.id IN (
        SELECT parent_id FROM character_messages
        WHERE parent_id IS NOT NULL
    )
)
SELECT
    cm.id,
    cm.game_id,
    cm.parent_id,
    cm.author_id,
    cm.character_id,
    cm.content,
    cm.message_type,
    cm.created_at,
    cm.edited_at,
    cm.edit_count,
    cm.deleted_at,
    cm.is_deleted,
    cm.author_username,
    cm.character_name,
    cm.character_avatar_url,
    pm.content as parent_content,
    pm.created_at as parent_created_at,
    pm.deleted_at as parent_deleted_at,
    pm.is_deleted as parent_is_deleted,
    pm.message_type as parent_message_type,
    pm.author_username as parent_author_username,
    pm.character_name as parent_character_name,
    pm.character_avatar_url as parent_character_avatar_url
FROM character_messages cm
LEFT JOIN parent_messages pm ON cm.parent_id = pm.id
ORDER BY cm.created_at DESC
`

type ListCharacterPostsAndCommentsParams struct {
	CharacterID int32 `json:"character_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

type ListCharacterPostsAndCommentsRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	MessageType              MessageType        `json:"message_type"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	IsDeleted                bool               `json:"is_deleted"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            string             `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	ParentContent            pgtype.Text        `json:"parent_content"`
	ParentCreatedAt          pgtype.Timestamp   `json:"parent_created_at"`
	ParentDeletedAt          pgtype.Timestamp   `json:"parent_deleted_at"`
	ParentIsDeleted          pgtype.Bool        `json:"parent_is_deleted"`
	ParentMessageType        NullMessageType    `json:"parent_message_type"`
	ParentAuthorUsername     pgtype.Text        `json:"parent_author_username"`
	ParentCharacterName      pgtype.Text        `json:"parent_character_name"`
	ParentCharacterAvatarUrl pgtype.Text        `json:"parent_character_avatar_url"`
}

// Get all posts and comments by a specific character (for Character Page)
// Returns both posts and comments with parent context for comments
// Only returns public (game-visibility) messages, not deleted ones
// NPCs only show comments (not top-level posts)
func (q *Queries) ListCharacterPostsAndComments(ctx context.Context, arg ListCharacterPostsAndCommentsParams) ([]ListCharacterPostsAndCommentsRow, error) {
	rows, err := q.db.Query(ctx, listCharacterPostsAndComments, arg.CharacterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterPostsAndCommentsRow
	for rows.Next() {
		var i ListCharacterPostsAndCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.ParentID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.MessageType,
			&i.CreatedAt,
			&i.EditedAt,
			&i.EditCount,
			&i.DeletedAt,
			&i.IsDeleted,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.CharacterAvatarUrl,
			&i.ParentContent,
			&i.ParentCreatedAt,
			&i.ParentDeletedAt,
			&i.ParentIsDeleted,
			&i.ParentMessageType,
			&i.ParentAuthorUsername,
			&i.ParentCharacterName,
			&i.ParentCharacterAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCommentsWithParents = `-- name: ListRecentCommentsWithParents :many
WITH RECURSIVE recent_comments AS (
    SELECT
        m.id,
        m.game_id,
        m.parent_id,
        m.author_id,
        m.character_id,
        m.content,
        m.created_at,
        m.edited_at,
        m.edit_count,
        m.deleted_at,
        m.is_deleted,
        u.username as author_username,
        c.name as character_name,
        c.avatar_url as character_avatar_url
    FROM messages m
    JOIN users u ON m.author_id = u.id
    LEFT JOIN characters c ON m.character_id = c.id
    WHERE m.game_id = $1
      AND m.message_type = 'comment'
      AND m.is_deleted = false
      AND m.deleted_at IS NULL
    ORDER BY m.created_at DESC
    LIMIT $2 OFFSET $3
),
root_posts AS (
    -- Base: walk up from each recent comment, tracking the original comment's id
    SELECT rc.id AS comment_id, rc.parent_id AS current_id
    FROM recent_comments rc
    WHERE rc.parent_id IS NOT NULL
    UNION ALL
    -- Recursive step: keep walking up until we hit a post
    SELECT rp.comment_id, m.parent_id AS current_id
    FROM root_posts rp
    JOIN messages m ON m.id = rp.current_id AND m.message_type = 'comment'
    WHERE m.parent_id IS NOT NULL
),
root_post_ids AS (
    SELECT rp.comment_id, rp.current_id AS post_id
    FROM root_posts rp
    JOIN messages m ON m.id = rp.current_id AND m.message_type = 'post'
),
parent_messages AS (
    SELECT
        m.id,
        m.content,
        m.created_at,
        m.deleted_at,
        m.is_deleted,
        m.message_type,
        u.username as author_username,
        c.name as character_name,
        c.avatar_url as character_avatar_url
    FROM messages m
    JOIN users u ON m.author_id = u.id
    LEFT JOIN characters c ON m.character_id = c.id
    WHERE m.id IN (
        SELECT parent_id FROM recent_comments
        WHERE parent_id IS NOT NULL
    )
)
SELECT
    rc.id,
    rc.game_id,
    rc.parent_id,
    rp.post_id,
    rc.author_id,
    rc.character_id,
    rc.content,
    rc.created_at,
    rc.edited_at,
    rc.edit_count,
    rc.deleted_at,
    rc.is_deleted,
    rc.author_username,
    rc.character_name,
    rc.character_avatar_url,
    pm.content as parent_content,
    pm.created_at as parent_created_at,
    pm.deleted_at as parent_deleted_at,
    pm.is_deleted as parent_is_deleted,
    pm.message_type as parent_message_type,
    pm.author_username as parent_author_username,
    pm.character_name as parent_character_name,
    pm.character_avatar_url as parent_character_avatar_url
FROM recent_comments rc
LEFT JOIN root_post_ids rp ON rp.comment_id = rc.id
LEFT JOIN parent_messages pm ON rc.parent_id = pm.id
ORDER BY rc.created_at DESC
`

type ListRecentCommentsWithParentsParams struct {
	GameID int32 `json:"game_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRecentCommentsWithParentsRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	PostID                   pgtype.Int4        `json:"post_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	IsDeleted                bool               `json:"is_deleted"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	ParentContent            pgtype.Text        `json:"parent_content"`
	ParentCreatedAt          pgtype.Timestamp   `json:"parent_created_at"`
	ParentDeletedAt          pgtype.Timestamp   `json:"parent_deleted_at"`
	ParentIsDeleted          pgtype.Bool        `json:"parent_is_deleted"`
	ParentMessageType        NullMessageType    `json:"parent_message_type"`
	ParentAuthorUsername     pgtype.Text        `json:"parent_author_username"`
	ParentCharacterName      pgtype.Text        `json:"parent_character_name"`
	ParentCharacterAvatarUrl pgtype.Text        `json:"parent_character_avatar_url"`
}

// Get recent comments with their parent comments/posts for New Comments view
// Walk up the message tree recursively to find the root post for each comment
// Pick the post at the top of each comment's chain
func (q *Queries) ListRecentCommentsWithParents(ctx context.Context, arg ListRecentCommentsWithParentsParams) ([]ListRecentCommentsWithParentsRow, error) {
	rows, err := q.db.Query(ctx, listRecentCommentsWithParents, arg.GameID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentCommentsWithParentsRow
	for rows.Next() {
		var i ListRecentCommentsWithParentsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.ParentID,
			&i.PostID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.CreatedAt,
			&i.EditedAt,
			&i.EditCount,
			&i.DeletedAt,
			&i.IsDeleted,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.CharacterAvatarUrl,
			&i.ParentContent,
			&i.ParentCreatedAt,
			&i.ParentDeletedAt,
			&i.ParentIsDeleted,
			&i.ParentMessageType,
			&i.ParentAuthorUsername,
			&i.ParentCharacterName,
			&i.ParentCharacterAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentUnreadCommentsWithParents = `-- name: ListRecentUnreadCommentsWithParents :many
WITH RECURSIVE recent_comments AS (
    SELECT
        m.id,
        m.game_id,
        m.parent_id,
        m.author_id,
        m.character_id,
        m.content,
        m.created_at,
        m.edited_at,
        m.edit_count,
        m.deleted_at,
        m.is_deleted,
        u.username as author_username,
        c.name as character_name,
        c.avatar_url as character_avatar_url
    FROM messages m
    JOIN users u ON m.author_id = u.id
    LEFT JOIN characters c ON m.character_id = c.id
    WHERE m.game_id = $1
      AND m.message_type = 'comment'
      AND m.is_deleted = false
      AND m.deleted_at IS NULL
      AND NOT EXISTS (
          SELECT 1 FROM user_comment_reads ucr
          WHERE ucr.comment_id = m.id AND ucr.user_id = $4
      )
    ORDER BY m.created_at DESC
    LIMIT $2 OFFSET $3
),
root_posts AS (
    -- Base: walk up from each recent comment, tracking the original comment's id
    SELECT rc.id AS comment_id, rc.parent_id AS current_id
    FROM recent_comments rc
    WHERE rc.parent_id IS NOT NULL
    UNION ALL
    -- Recursive step: keep walking up until we hit a post
    SELECT rp.comment_id, m.parent_id AS current_id
    FROM root_posts rp
    JOIN messages m ON m.id = rp.current_id AND m.message_type = 'comment'
    WHERE m.parent_id IS NOT NULL
),
root_post_ids AS (
    SELECT rp.comment_id, rp.current_id AS post_id
    FROM root_posts rp
    JOIN messages m ON m.id = rp.current_id AND m.message_type = 'post'
),
parent_messages AS (
    SELECT
        m.id,
        m.content,
        m.created_at,
        m.deleted_at,
        m.is_deleted,
        m.message_type,
        u.username as author_username,
        c.name as character_name,
        c.avatar_url as character_avatar_url
    FROM messages m
    JOIN users u ON m.author_id = u.id
    LEFT JOIN characters c ON m.character_id = c.id
    WHERE m.id IN (
        SELECT parent_id FROM recent_comments
        WHERE parent_id IS NOT NULL
    )
)
SELECT
    rc.id,
    rc.game_id,
    rc.parent_id,
    rp.post_id,
    rc.author_id,
    rc.character_id,
    rc.content,
    rc.created_at,
    rc.edited_at,
    rc.edit_count,
    rc.deleted_at,
    rc.is_deleted,
    rc.author_username,
    rc.character_name,
    rc.character_avatar_url,
    pm.content as parent_content,
    pm.created_at as parent_created_at,
    pm.deleted_at as parent_deleted_at,
    pm.is_deleted as parent_is_deleted,
    pm.message_type as parent_message_type,
    pm.author_username as parent_author_username,
    pm.character_name as parent_character_name,
    pm.character_avatar_url as parent_character_avatar_url
FROM recent_comments rc
LEFT JOIN root_post_ids rp ON rp.comment_id = rc.id
LEFT JOIN parent_messages pm ON rc.parent_id = pm.id
ORDER BY rc.created_at DESC
`

type ListRecentUnreadCommentsWithParentsParams struct {
	GameID int32 `json:"game_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
	UserID int32 `json:"user_id"`
}

type ListRecentUnreadCommentsWithParentsRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	PostID                   pgtype.Int4        `json:"post_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	IsDeleted                bool               `json:"is_deleted"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	ParentContent            pgtype.Text        `json:"parent_content"`
	ParentCreatedAt          pgtype.Timestamp   `json:"parent_created_at"`
	ParentDeletedAt          pgtype.Timestamp   `json:"parent_deleted_at"`
	ParentIsDeleted          pgtype.Bool        `json:"parent_is_deleted"`
	ParentMessageType        NullMessageType    `json:"parent_message_type"`
	ParentAuthorUsername     pgtype.Text        `json:"parent_author_username"`
	ParentCharacterName      pgtype.Text        `json:"parent_character_name"`
	ParentCharacterAvatarUrl pgtype.Text        `json:"parent_character_avatar_url"`
}

// Same as ListRecentCommentsWithParents, but excludes comments the user has
// manually marked as read. Used by the "New Comments" view's unread-only filter
// in manual read mode. Filtering happens before LIMIT/OFFSET so pagination
// counts stay accurate.
// Walk up the message tree recursively to find the root post for each comment
// Pick the post at the top of each comment's chain
func (q *Queries) ListRecentUnreadCommentsWithParents(ctx context.Context, arg ListRecentUnreadCommentsWithParentsParams) ([]ListRecentUnreadCommentsWithParentsRow, error) {
	rows, err := q.db.Query(ctx, listRecentUnreadCommentsWithParents,
		arg.GameID,
		arg.Limit,
		arg.Offset,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentUnreadCommentsWithParentsRow
	for rows.Next() {
		var i ListRecentUnreadCommentsWithParentsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.ParentID,
			&i.PostID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.CreatedAt,
			&i.EditedAt,
			&i.EditCount,
			&i.DeletedAt,
			&i.IsDeleted,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.CharacterAvatarUrl,
			&i.ParentContent,
			&i.ParentCreatedAt,
			&i.ParentDeletedAt,
			&i.ParentIsDeleted,
			&i.ParentMessageType,
			&i.ParentAuthorUsername,
			&i.ParentCharacterName,
			&i.ParentCharacterAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeConversationParticipant = `-- name: RemoveConversationParticipant :exec
DELETE FROM conversation_participants
WHERE conversation_id = $1 AND user_id = $2 AND
      (character_id = $3 OR ($3 IS NULL AND character_id IS NULL))
`

type RemoveConversationParticipantParams struct {
	ConversationID int32       `json:"conversation_id"`
	UserID         int32       `json:"user_id"`
	CharacterID    pgtype.Int4 `json:"character_id"`
}

func (q *Queries) RemoveConversationParticipant(ctx context.Context, arg RemoveConversationParticipantParams) error {
	_, err := q.db.Exec(ctx, removeConversationParticipant, arg.ConversationID, arg.UserID, arg.CharacterID)
	return err
}

const sendPrivateMessage = `-- name: SendPrivateMessage :one
INSERT INTO private_messages (conversation_id, sender_user_id, sender_character_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_user_id, sender_character_id, content, created_at, updated_at, deleted_at, is_deleted, is_edited, edited_at, edit_count
`

type SendPrivateMessageParams struct {
	ConversationID    int32       `json:"conversation_id"`
	SenderUserID      int32       `json:"sender_user_id"`
	SenderCharacterID pgtype.Int4 `json:"sender_character_id"`
	Content           string      `json:"content"`
}

func (q *Queries) SendPrivateMessage(ctx context.Context, arg SendPrivateMessageParams) (PrivateMessage, error) {
	row := q.db.QueryRow(ctx, sendPrivateMessage,
		arg.ConversationID,
		arg.SenderUserID,
		arg.SenderCharacterID,
		arg.Content,
	)
	var i PrivateMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.SenderCharacterID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDeleted,
		&i.IsEdited,
		&i.EditedAt,
		&i.EditCount,
	)
	return i, err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE messages
SET deleted_at = NOW(), is_deleted = true
WHERE id = $1
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteMessage, id)
	return err
}

const softDeletePrivateMessage = `-- name: SoftDeletePrivateMessage :exec
UPDATE private_messages
SET deleted_at = NOW(), is_deleted = true
WHERE id = $1 AND sender_user_id = $2
`

type SoftDeletePrivateMessageParams struct {
	ID           int32 `json:"id"`
	SenderUserID int32 `json:"sender_user_id"`
}

func (q *Queries) SoftDeletePrivateMessage(ctx context.Context, arg SoftDeletePrivateMessageParams) error {
	_, err := q.db.Exec(ctx, softDeletePrivateMessage, arg.ID, arg.SenderUserID)
	return err
}

const toggleThreadPin = `-- name: ToggleThreadPin :one
UPDATE threads
SET is_pinned = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, game_id, phase_id, title, content, created_by_user_id, is_pinned, created_at, updated_at
`

type ToggleThreadPinParams struct {
	ID       int32       `json:"id"`
	IsPinned pgtype.Bool `json:"is_pinned"`
}

func (q *Queries) ToggleThreadPin(ctx context.Context, arg ToggleThreadPinParams) (Thread, error) {
	row := q.db.QueryRow(ctx, toggleThreadPin, arg.ID, arg.IsPinned)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.Title,
		&i.Content,
		&i.CreatedByUserID,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConversationActivity = `-- name: UpdateConversationActivity :exec
UPDATE conversations
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateConversationActivity(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateConversationActivity, id)
	return err
}

const updateLastReadTime = `-- name: UpdateLastReadTime :exec
UPDATE conversation_participants
SET last_read_at = NOW()
WHERE conversation_id = $1 AND user_id = $2
`

type UpdateLastReadTimeParams struct {
	ConversationID int32 `json:"conversation_id"`
	UserID         int32 `json:"user_id"`
}

func (q *Queries) UpdateLastReadTime(ctx context.Context, arg UpdateLastReadTimeParams) error {
	_, err := q.db.Exec(ctx, updateLastReadTime, arg.ConversationID, arg.UserID)
	return err
}

const updatePrivateMessage = `-- name: UpdatePrivateMessage :one
UPDATE private_messages
SET content = $2,
    is_edited = true,
    edited_at = NOW(),
    edit_count = edit_count + 1
WHERE id = $1
  AND sender_user_id = $3
  AND is_deleted = false
RETURNING id, conversation_id, sender_user_id, sender_character_id, content, created_at, updated_at, deleted_at, is_deleted, is_edited, edited_at, edit_count
`

type UpdatePrivateMessageParams struct {
	ID           int32  `json:"id"`
	Content      string `json:"content"`
	SenderUserID int32  `json:"sender_user_id"`
}

func (q *Queries) UpdatePrivateMessage(ctx context.Context, arg UpdatePrivateMessageParams) (PrivateMessage, error) {
	row := q.db.QueryRow(ctx, updatePrivateMessage, arg.ID, arg.Content, arg.SenderUserID)
	var i PrivateMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.SenderCharacterID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDeleted,
		&i.IsEdited,
		&i.EditedAt,
		&i.EditCount,
	)
	return i, err
}

const updateThread = `-- name: UpdateThread :one
UPDATE threads
SET title = $2, content = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, game_id, phase_id, title, content, created_by_user_id, is_pinned, created_at, updated_at
`

type UpdateThreadParams struct {
	ID      int32       `json:"id"`
	Title   string      `json:"title"`
	Content pgtype.Text `json:"content"`
}

func (q *Queries) UpdateThread(ctx context.Context, arg UpdateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, updateThread, arg.ID, arg.Title, arg.Content)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.Title,
		&i.Content,
		&i.CreatedByUserID,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateThreadActivity = `-- name: UpdateThreadActivity :exec
UPDATE threads
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateThreadActivity(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateThreadActivity, id)
	return err
}

const updateThreadPost = `-- name: UpdateThreadPost :one
UPDATE thread_posts
SET content = $2, is_edited = true, updated_at = NOW()
WHERE id = $1
RETURNING id, thread_id, parent_post_id, user_id, character_id, content, created_at, updated_at
`

type UpdateThreadPostParams struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateThreadPost(ctx context.Context, arg UpdateThreadPostParams) (ThreadPost, error) {
	row := q.db.QueryRow(ctx, updateThreadPost, arg.ID, arg.Content)
	var i ThreadPost
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ParentPostID,
		&i.UserID,
		&i.CharacterID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
