// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserGames = `-- name: CountUserGames :one
SELECT COUNT(DISTINCT g.id) as game_count
FROM games g
LEFT JOIN game_participants gp ON g.id = gp.game_id AND gp.user_id = $1 AND gp.status = 'active'
WHERE (gp.user_id = $1 AND gp.status = 'active') OR g.gm_user_id = $1
`

// Count total games user participates in OR is GM of
func (q *Queries) CountUserGames(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUserGames, userID)
	var game_count int64
	err := row.Scan(&game_count)
	return game_count, err
}

const getDashboardUnreadCount = `-- name: GetDashboardUnreadCount :one

SELECT COUNT(*) as count
FROM notifications
WHERE user_id = $1 AND is_read = false
`

// GetUnreadCommentCountsForDashboard is implemented as a raw query in dashboard.go
// due to sqlc limitations with recursive CTEs (same pattern as GetPostCommentsWithThreads).
// See getUnreadCommentCountsForDashboard() in backend/pkg/db/services/dashboard.go.
// Get count of all unread notifications for user (dashboard-specific)
func (q *Queries) GetDashboardUnreadCount(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getDashboardUnreadCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserDashboardGames = `-- name: GetUserDashboardGames :many

SELECT
  g.id,
  g.title,
  g.description,
  g.state,
  g.genre,
  g.gm_user_id,
  COALESCE(gp.role, 'gm') as user_role,
  COALESCE(gp.status, 'active') as participant_status,
  -- Current phase information
  current_phase.id as current_phase_id,
  current_phase.phase_type as current_phase_type,
  current_phase.title as current_phase_title,
  current_phase.deadline as current_phase_deadline,
  -- Game Master information
  gm_user.username as gm_username,
  -- Counts and metrics
  (SELECT COUNT(*)
   FROM game_applications
   WHERE game_id = g.id AND status = 'pending') as pending_applications_count,
  -- Active polls with no vote from this user
  (SELECT COUNT(*)
   FROM common_room_polls crp
   WHERE crp.game_id = g.id
     AND crp.deadline > NOW()
     AND crp.is_deleted = false
     AND NOT EXISTS (
       SELECT 1 FROM poll_votes pv
       WHERE pv.poll_id = crp.id AND pv.user_id = $1
     )) as unvoted_polls_count,
  -- Action submission status for current phase
  CASE
    WHEN current_phase.id IS NOT NULL AND current_phase.phase_type = 'action' THEN
      (SELECT CASE WHEN COUNT(*) = 0 THEN true
                   WHEN bool_or(is_draft = true) THEN true
                   ELSE false END
       FROM action_submissions
       WHERE game_id = g.id
         AND user_id = $1
         AND phase_id = current_phase.id)
    ELSE false
  END as has_pending_action,
  g.updated_at,
  g.created_at
FROM games g
LEFT JOIN game_participants gp ON g.id = gp.game_id AND gp.user_id = $1 AND gp.status = 'active'
LEFT JOIN game_phases current_phase ON g.id = current_phase.game_id AND current_phase.is_active = true
LEFT JOIN users gm_user ON g.gm_user_id = gm_user.id
WHERE ((gp.user_id = $1 AND gp.status = 'active') OR g.gm_user_id = $1)
  AND g.state != 'completed'
ORDER BY
  -- Urgent games first: action phases with pending submissions and near deadlines
  CASE
    WHEN current_phase.phase_type = 'action'
         AND current_phase.deadline IS NOT NULL
         AND current_phase.deadline < NOW() + INTERVAL '24 hours'
         AND (SELECT CASE WHEN COUNT(*) = 0 THEN true
                          WHEN bool_or(is_draft = true) THEN true
                          ELSE false END
              FROM action_submissions
              WHERE game_id = g.id
                AND user_id = $1
                AND phase_id = current_phase.id) THEN 0
    ELSE 1
  END,
  -- Then by approaching deadlines
  current_phase.deadline ASC NULLS LAST,
  -- Then by unread activity
  (SELECT COUNT(*)
   FROM notifications n
   WHERE n.game_id = g.id AND n.user_id = $1 AND n.is_read = false) DESC,
  -- Finally by recently updated
  g.updated_at DESC
LIMIT 15
`

type GetUserDashboardGamesRow struct {
	ID                       int32              `json:"id"`
	Title                    string             `json:"title"`
	Description              pgtype.Text        `json:"description"`
	State                    pgtype.Text        `json:"state"`
	Genre                    pgtype.Text        `json:"genre"`
	GmUserID                 int32              `json:"gm_user_id"`
	UserRole                 string             `json:"user_role"`
	ParticipantStatus        string             `json:"participant_status"`
	CurrentPhaseID           pgtype.Int4        `json:"current_phase_id"`
	CurrentPhaseType         pgtype.Text        `json:"current_phase_type"`
	CurrentPhaseTitle        pgtype.Text        `json:"current_phase_title"`
	CurrentPhaseDeadline     pgtype.Timestamptz `json:"current_phase_deadline"`
	GmUsername               pgtype.Text        `json:"gm_username"`
	PendingApplicationsCount int64              `json:"pending_applications_count"`
	UnvotedPollsCount        int64              `json:"unvoted_polls_count"`
	HasPendingAction         bool               `json:"has_pending_action"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

// Dashboard Queries
// Comprehensive queries for user dashboard with game status, deadlines, and activity
// Get all games user participates in OR is GM of, with enriched metadata for dashboard
func (q *Queries) GetUserDashboardGames(ctx context.Context, userID int32) ([]GetUserDashboardGamesRow, error) {
	rows, err := q.db.Query(ctx, getUserDashboardGames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserDashboardGamesRow
	for rows.Next() {
		var i GetUserDashboardGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.State,
			&i.Genre,
			&i.GmUserID,
			&i.UserRole,
			&i.ParticipantStatus,
			&i.CurrentPhaseID,
			&i.CurrentPhaseType,
			&i.CurrentPhaseTitle,
			&i.CurrentPhaseDeadline,
			&i.GmUsername,
			&i.PendingApplicationsCount,
			&i.UnvotedPollsCount,
			&i.HasPendingAction,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecentMessages = `-- name: GetUserRecentMessages :many
SELECT
  m.id as message_id,
  m.game_id,
  m.content,
  m.created_at,
  g.title as game_title,
  g.is_anonymous,
  COALESCE(gp.role, 'gm') as viewer_role,
  author.username as author_name,
  character.name as character_name,
  m.message_type,
  m.phase_id
FROM messages m
INNER JOIN games g ON m.game_id = g.id
LEFT JOIN game_participants gp ON g.id = gp.game_id AND gp.user_id = $1 AND gp.status = 'active'
INNER JOIN users author ON m.author_id = author.id
LEFT JOIN characters character ON m.character_id = character.id
WHERE ((gp.user_id = $1 AND gp.status = 'active' AND gp.role != 'audience') OR g.gm_user_id = $1)
  AND m.created_at > NOW() - INTERVAL '7 days'
  AND m.author_id != $1
  AND m.is_deleted = false
  AND m.is_draft = false
ORDER BY m.created_at DESC
LIMIT $2
`

type GetUserRecentMessagesParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type GetUserRecentMessagesRow struct {
	MessageID     int32            `json:"message_id"`
	GameID        int32            `json:"game_id"`
	Content       string           `json:"content"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	GameTitle     string           `json:"game_title"`
	IsAnonymous   bool             `json:"is_anonymous"`
	ViewerRole    string           `json:"viewer_role"`
	AuthorName    string           `json:"author_name"`
	CharacterName pgtype.Text      `json:"character_name"`
	MessageType   MessageType      `json:"message_type"`
	PhaseID       pgtype.Int4      `json:"phase_id"`
}

// Get recent messages from games user participates in OR is GM of (excluding their own messages)
func (q *Queries) GetUserRecentMessages(ctx context.Context, arg GetUserRecentMessagesParams) ([]GetUserRecentMessagesRow, error) {
	rows, err := q.db.Query(ctx, getUserRecentMessages, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRecentMessagesRow
	for rows.Next() {
		var i GetUserRecentMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.GameID,
			&i.Content,
			&i.CreatedAt,
			&i.GameTitle,
			&i.IsAnonymous,
			&i.ViewerRole,
			&i.AuthorName,
			&i.CharacterName,
			&i.MessageType,
			&i.PhaseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUnreadNotificationsByType = `-- name: GetUserUnreadNotificationsByType :many
SELECT type, COUNT(*) as count
FROM notifications
WHERE user_id = $1 AND is_read = false
GROUP BY type
ORDER BY count DESC
`

type GetUserUnreadNotificationsByTypeRow struct {
	Type  string `json:"type"`
	Count int64  `json:"count"`
}

// Get unread notification counts grouped by type for the dashboard digest
func (q *Queries) GetUserUnreadNotificationsByType(ctx context.Context, userID int32) ([]GetUserUnreadNotificationsByTypeRow, error) {
	rows, err := q.db.Query(ctx, getUserUnreadNotificationsByType, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserUnreadNotificationsByTypeRow
	for rows.Next() {
		var i GetUserUnreadNotificationsByTypeRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUpcomingDeadlines = `-- name: GetUserUpcomingDeadlines :many

SELECT
  'phase' as deadline_type,
  gp.id as source_id,
  gp.id as phase_id,
  g.id as game_id,
  g.title as game_title,
  gp.title as title,
  gp.phase_type,
  gp.title as phase_title,
  gp.phase_number,
  gp.deadline as end_time,
  CASE
    WHEN gp.phase_type = 'action' AND part.user_id IS NOT NULL THEN
      (SELECT CASE WHEN COUNT(*) = 0 THEN true
                   WHEN bool_or(is_draft = true) THEN true
                   ELSE false END
       FROM action_submissions acts
       WHERE acts.game_id = g.id
         AND acts.user_id = $1
         AND acts.phase_id = gp.id)
    ELSE false
  END as has_pending_submission
FROM game_phases gp
INNER JOIN games g ON gp.game_id = g.id
LEFT JOIN game_participants part ON g.id = part.game_id AND part.user_id = $1 AND part.status = 'active'
WHERE ((part.user_id = $1 AND part.status = 'active' AND part.role != 'audience') OR g.gm_user_id = $1)
  AND gp.is_active = true
  AND gp.deadline IS NOT NULL
  AND gp.deadline > NOW()

UNION ALL

SELECT
  'deadline' as deadline_type,
  gd.id as source_id,
  0 as phase_id,
  g.id as game_id,
  g.title as game_title,
  gd.title as title,
  '' as phase_type,
  '' as phase_title,
  0 as phase_number,
  gd.deadline as end_time,
  false as has_pending_submission
FROM game_deadlines gd
INNER JOIN games g ON gd.game_id = g.id
LEFT JOIN game_participants part ON g.id = part.game_id AND part.user_id = $1 AND part.status = 'active'
WHERE ((part.user_id = $1 AND part.status = 'active' AND part.role != 'audience') OR g.gm_user_id = $1)
  AND gd.deleted_at IS NULL
  AND gd.deadline > NOW()

UNION ALL

SELECT
  'poll' as deadline_type,
  crp.id as source_id,
  0 as phase_id,
  g.id as game_id,
  g.title as game_title,
  crp.question as title,
  '' as phase_type,
  '' as phase_title,
  0 as phase_number,
  crp.deadline as end_time,
  false as has_pending_submission
FROM common_room_polls crp
INNER JOIN games g ON crp.game_id = g.id
LEFT JOIN game_participants part ON g.id = part.game_id AND part.user_id = $1 AND part.status = 'active'
WHERE ((part.user_id = $1 AND part.status = 'active' AND part.role != 'audience') OR g.gm_user_id = $1)
  AND crp.is_deleted = false
  AND crp.deadline IS NOT NULL
  AND crp.deadline > NOW()

ORDER BY end_time ASC
LIMIT $2
`

type GetUserUpcomingDeadlinesParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type GetUserUpcomingDeadlinesRow struct {
	DeadlineType         string             `json:"deadline_type"`
	SourceID             int32              `json:"source_id"`
	PhaseID              int32              `json:"phase_id"`
	GameID               int32              `json:"game_id"`
	GameTitle            string             `json:"game_title"`
	Title                string             `json:"title"`
	PhaseType            string             `json:"phase_type"`
	PhaseTitle           string             `json:"phase_title"`
	PhaseNumber          int32              `json:"phase_number"`
	EndTime              pgtype.Timestamptz `json:"end_time"`
	HasPendingSubmission bool               `json:"has_pending_submission"`
}

// Get upcoming deadlines across all user's games: phase, arbitrary, and poll deadlines.
// Excludes audience-only participants (they don't have actionable deadlines).
// Phase deadlines
// Arbitrary deadlines (GM-created)
// Poll deadlines
func (q *Queries) GetUserUpcomingDeadlines(ctx context.Context, arg GetUserUpcomingDeadlinesParams) ([]GetUserUpcomingDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, getUserUpcomingDeadlines, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserUpcomingDeadlinesRow
	for rows.Next() {
		var i GetUserUpcomingDeadlinesRow
		if err := rows.Scan(
			&i.DeadlineType,
			&i.SourceID,
			&i.PhaseID,
			&i.GameID,
			&i.GameTitle,
			&i.Title,
			&i.PhaseType,
			&i.PhaseTitle,
			&i.PhaseNumber,
			&i.EndTime,
			&i.HasPendingSubmission,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
