// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextGameExport = `-- name: ClaimNextGameExport :one
UPDATE game_exports
SET status = 'running', started_at = NOW()
WHERE id = (
    SELECT id FROM game_exports
    WHERE status = 'pending'
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, game_id, requested_by_user_id, status, content_fingerprint, storage_path, size_bytes, file_count, error_message, progress_note, started_at, completed_at, expires_at, created_at
`

// Atomically claim the oldest pending job. SKIP LOCKED keeps this correct
// when several backend replicas poll concurrently.
func (q *Queries) ClaimNextGameExport(ctx context.Context) (GameExport, error) {
	row := q.db.QueryRow(ctx, claimNextGameExport)
	var i GameExport
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.RequestedByUserID,
		&i.Status,
		&i.ContentFingerprint,
		&i.StoragePath,
		&i.SizeBytes,
		&i.FileCount,
		&i.ErrorMessage,
		&i.ProgressNote,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createGameExport = `-- name: CreateGameExport :one


INSERT INTO game_exports (game_id, requested_by_user_id, status)
VALUES ($1, $2, 'pending')
RETURNING id, game_id, requested_by_user_id, status, content_fingerprint, storage_path, size_bytes, file_count, error_message, progress_note, started_at, completed_at, expires_at, created_at
`

type CreateGameExportParams struct {
	GameID            int32       `json:"game_id"`
	RequestedByUserID pgtype.Int4 `json:"requested_by_user_id"`
}

// =============================================================================
// GAME EXPORT QUERIES
// =============================================================================
// Async archive exports for completed games. See pkg/db/services/exports/.
//
// Content queries here intentionally return EVERYTHING a completed game holds:
// completed games are a public archive readable by any authenticated user
// (CanUserViewGame), so there is no per-viewer filtering. The only exclusions
// are drafts (is_draft) and soft-deleted rows (is_deleted / deleted_at), which
// were never visible to anyone but their author.
// =============================================================================
// JOB LIFECYCLE
// =============================================================================
// Enqueue an export. The partial unique index idx_game_exports_one_active
// makes this fail if an export for this game is already pending/running,
// which is how concurrent requests coalesce onto a single job.
func (q *Queries) CreateGameExport(ctx context.Context, arg CreateGameExportParams) (GameExport, error) {
	row := q.db.QueryRow(ctx, createGameExport, arg.GameID, arg.RequestedByUserID)
	var i GameExport
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.RequestedByUserID,
		&i.Status,
		&i.ContentFingerprint,
		&i.StoragePath,
		&i.SizeBytes,
		&i.FileCount,
		&i.ErrorMessage,
		&i.ProgressNote,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveGameExport = `-- name: GetActiveGameExport :one
SELECT id, game_id, requested_by_user_id, status, content_fingerprint, storage_path, size_bytes, file_count, error_message, progress_note, started_at, completed_at, expires_at, created_at FROM game_exports
WHERE game_id = $1 AND status IN ('pending', 'running')
LIMIT 1
`

// The in-flight export for a game, if any.
func (q *Queries) GetActiveGameExport(ctx context.Context, gameID int32) (GameExport, error) {
	row := q.db.QueryRow(ctx, getActiveGameExport, gameID)
	var i GameExport
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.RequestedByUserID,
		&i.Status,
		&i.ContentFingerprint,
		&i.StoragePath,
		&i.SizeBytes,
		&i.FileCount,
		&i.ErrorMessage,
		&i.ProgressNote,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGameContentFingerprint = `-- name: GetGameContentFingerprint :one

SELECT
    (SELECT COUNT(*) FROM messages m WHERE m.game_id = $1)::bigint AS message_count,
    (SELECT MAX(GREATEST(m.created_at, COALESCE(m.edited_at::timestamp, m.created_at)))
       FROM messages m WHERE m.game_id = $1)::timestamptz AS message_max_ts,
    (SELECT COUNT(*) FROM action_submissions s WHERE s.game_id = $1)::bigint AS submission_count,
    (SELECT MAX(s.updated_at) FROM action_submissions s WHERE s.game_id = $1)::timestamptz AS submission_max_ts,
    (SELECT COUNT(*) FROM action_results r WHERE r.game_id = $1)::bigint AS result_count,
    (SELECT MAX(r.sent_at) FROM action_results r WHERE r.game_id = $1)::timestamptz AS result_max_ts,
    (SELECT COUNT(*) FROM private_messages pm
       JOIN conversations pc ON pm.conversation_id = pc.id
      WHERE pc.game_id = $1)::bigint AS private_message_count,
    (SELECT MAX(pm.updated_at) FROM private_messages pm
       JOIN conversations pc ON pm.conversation_id = pc.id
      WHERE pc.game_id = $1)::timestamptz AS private_message_max_ts,
    (SELECT COUNT(*) FROM game_phases ph WHERE ph.game_id = $1)::bigint AS phase_count,
    (SELECT COUNT(*) FROM characters ch WHERE ch.game_id = $1)::bigint AS character_count,
    (SELECT MAX(ch.updated_at) FROM characters ch WHERE ch.game_id = $1)::timestamptz AS character_max_ts,
    (SELECT COUNT(*) FROM handouts h WHERE h.game_id = $1)::bigint AS handout_count,
    (SELECT MAX(h.updated_at) FROM handouts h WHERE h.game_id = $1)::timestamptz AS handout_max_ts,
    (SELECT COUNT(*) FROM common_room_polls p WHERE p.game_id = $1 AND p.is_deleted = FALSE)::bigint AS poll_count,
    (SELECT MAX(p.updated_at) FROM common_room_polls p WHERE p.game_id = $1)::timestamptz AS poll_max_ts,
    (SELECT g.updated_at FROM games g WHERE g.id = $1)::timestamptz AS game_updated_at
`

type GetGameContentFingerprintRow struct {
	MessageCount        int64              `json:"message_count"`
	MessageMaxTs        pgtype.Timestamptz `json:"message_max_ts"`
	SubmissionCount     int64              `json:"submission_count"`
	SubmissionMaxTs     pgtype.Timestamptz `json:"submission_max_ts"`
	ResultCount         int64              `json:"result_count"`
	ResultMaxTs         pgtype.Timestamptz `json:"result_max_ts"`
	PrivateMessageCount int64              `json:"private_message_count"`
	PrivateMessageMaxTs pgtype.Timestamptz `json:"private_message_max_ts"`
	PhaseCount          int64              `json:"phase_count"`
	CharacterCount      int64              `json:"character_count"`
	CharacterMaxTs      pgtype.Timestamptz `json:"character_max_ts"`
	HandoutCount        int64              `json:"handout_count"`
	HandoutMaxTs        pgtype.Timestamptz `json:"handout_max_ts"`
	PollCount           int64              `json:"poll_count"`
	PollMaxTs           pgtype.Timestamptz `json:"poll_max_ts"`
	GameUpdatedAt       pgtype.Timestamptz `json:"game_updated_at"`
}

// =============================================================================
// CONTENT FINGERPRINT
// =============================================================================
// Cheap change-detection across every table the archive draws from. Completed
// games are mostly immutable, but a GM can still edit after completion, so a
// cached artifact is only reusable while this value is unchanged.
func (q *Queries) GetGameContentFingerprint(ctx context.Context, gameID int32) (GetGameContentFingerprintRow, error) {
	row := q.db.QueryRow(ctx, getGameContentFingerprint, gameID)
	var i GetGameContentFingerprintRow
	err := row.Scan(
		&i.MessageCount,
		&i.MessageMaxTs,
		&i.SubmissionCount,
		&i.SubmissionMaxTs,
		&i.ResultCount,
		&i.ResultMaxTs,
		&i.PrivateMessageCount,
		&i.PrivateMessageMaxTs,
		&i.PhaseCount,
		&i.CharacterCount,
		&i.CharacterMaxTs,
		&i.HandoutCount,
		&i.HandoutMaxTs,
		&i.PollCount,
		&i.PollMaxTs,
		&i.GameUpdatedAt,
	)
	return i, err
}

const getGameExport = `-- name: GetGameExport :one
SELECT ge.id, ge.game_id, ge.requested_by_user_id, ge.status, ge.content_fingerprint, ge.storage_path, ge.size_bytes, ge.file_count, ge.error_message, ge.progress_note, ge.started_at, ge.completed_at, ge.expires_at, ge.created_at, g.title AS game_title
FROM game_exports ge
JOIN games g ON g.id = ge.game_id
WHERE ge.id = $1
`

type GetGameExportRow struct {
	ID                 int32              `json:"id"`
	GameID             int32              `json:"game_id"`
	RequestedByUserID  pgtype.Int4        `json:"requested_by_user_id"`
	Status             string             `json:"status"`
	ContentFingerprint pgtype.Text        `json:"content_fingerprint"`
	StoragePath        pgtype.Text        `json:"storage_path"`
	SizeBytes          pgtype.Int8        `json:"size_bytes"`
	FileCount          pgtype.Int4        `json:"file_count"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	ProgressNote       pgtype.Text        `json:"progress_note"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	GameTitle          string             `json:"game_title"`
}

// Joins the game title so the download handler can name the file after the
// game rather than its numeric export id.
func (q *Queries) GetGameExport(ctx context.Context, id int32) (GetGameExportRow, error) {
	row := q.db.QueryRow(ctx, getGameExport, id)
	var i GetGameExportRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.RequestedByUserID,
		&i.Status,
		&i.ContentFingerprint,
		&i.StoragePath,
		&i.SizeBytes,
		&i.FileCount,
		&i.ErrorMessage,
		&i.ProgressNote,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.GameTitle,
	)
	return i, err
}

const getLatestGameExport = `-- name: GetLatestGameExport :one
SELECT id, game_id, requested_by_user_id, status, content_fingerprint, storage_path, size_bytes, file_count, error_message, progress_note, started_at, completed_at, expires_at, created_at FROM game_exports
WHERE game_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// Newest export for a game in any state, for status polling.
func (q *Queries) GetLatestGameExport(ctx context.Context, gameID int32) (GameExport, error) {
	row := q.db.QueryRow(ctx, getLatestGameExport, gameID)
	var i GameExport
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.RequestedByUserID,
		&i.Status,
		&i.ContentFingerprint,
		&i.StoragePath,
		&i.SizeBytes,
		&i.FileCount,
		&i.ErrorMessage,
		&i.ProgressNote,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReusableGameExport = `-- name: GetReusableGameExport :one
SELECT id, game_id, requested_by_user_id, status, content_fingerprint, storage_path, size_bytes, file_count, error_message, progress_note, started_at, completed_at, expires_at, created_at FROM game_exports
WHERE game_id = $1
  AND status = 'complete'
  AND storage_path IS NOT NULL
  AND (expires_at IS NULL OR expires_at > NOW())
  AND content_fingerprint = $2
ORDER BY completed_at DESC
LIMIT 1
`

type GetReusableGameExportParams struct {
	GameID             int32       `json:"game_id"`
	ContentFingerprint pgtype.Text `json:"content_fingerprint"`
}

// Newest completed export that is still usable: artifact present, not expired,
// and fingerprint still matching current content.
//
// Completed games are effectively immutable, so the fingerprint should always
// match; it is kept as a safety check rather than a cache key. If it ever
// mismatches (a future GM tool, an admin action), the archive is rebuilt
// instead of serving stale content.
func (q *Queries) GetReusableGameExport(ctx context.Context, arg GetReusableGameExportParams) (GameExport, error) {
	row := q.db.QueryRow(ctx, getReusableGameExport, arg.GameID, arg.ContentFingerprint)
	var i GameExport
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.RequestedByUserID,
		&i.Status,
		&i.ContentFingerprint,
		&i.StoragePath,
		&i.SizeBytes,
		&i.FileCount,
		&i.ErrorMessage,
		&i.ProgressNote,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredGameExports = `-- name: ListExpiredGameExports :many
SELECT id, game_id, storage_path
FROM game_exports
WHERE status = 'complete'
  AND storage_path IS NOT NULL
  AND expires_at IS NOT NULL
  AND expires_at <= NOW()
ORDER BY expires_at
LIMIT $1
`

type ListExpiredGameExportsRow struct {
	ID          int32       `json:"id"`
	GameID      int32       `json:"game_id"`
	StoragePath pgtype.Text `json:"storage_path"`
}

// Complete exports whose retention window has passed but whose artifact is
// still in storage. The worker deletes each artifact, then calls
// MarkGameExportExpired to clear the path.
func (q *Queries) ListExpiredGameExports(ctx context.Context, resultLimit int32) ([]ListExpiredGameExportsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredGameExports, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredGameExportsRow
	for rows.Next() {
		var i ListExpiredGameExportsRow
		if err := rows.Scan(&i.ID, &i.GameID, &i.StoragePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportActionResults = `-- name: ListExportActionResults :many
SELECT r.id, r.phase_id, r.user_id, r.action_submission_id, r.content, r.sent_at,
       u.username AS recipient_username, ch.name AS character_name,
       gm.username AS gm_username
FROM action_results r
JOIN users u ON r.user_id = u.id
JOIN users gm ON r.gm_user_id = gm.id
LEFT JOIN characters ch ON r.character_id = ch.id
WHERE r.game_id = $1 AND r.is_published = TRUE
ORDER BY r.phase_id, r.sent_at
`

type ListExportActionResultsRow struct {
	ID                 int32              `json:"id"`
	PhaseID            int32              `json:"phase_id"`
	UserID             int32              `json:"user_id"`
	ActionSubmissionID pgtype.Int4        `json:"action_submission_id"`
	Content            string             `json:"content"`
	SentAt             pgtype.Timestamptz `json:"sent_at"`
	RecipientUsername  string             `json:"recipient_username"`
	CharacterName      pgtype.Text        `json:"character_name"`
	GmUsername         string             `json:"gm_username"`
}

// Published results only: unpublished ones never reached the player.
//
// action_submission_id is frequently NULL in practice even when the matching
// submission exists, so the archive pairs results to submissions by
// (phase_id, user_id) — the tuple action_submissions enforces as unique via
// UNIQUE(game_id, user_id, phase_id). user_id is selected for that join;
// action_submission_id is kept as a preferred hint when it is set.
func (q *Queries) ListExportActionResults(ctx context.Context, gameID int32) ([]ListExportActionResultsRow, error) {
	rows, err := q.db.Query(ctx, listExportActionResults, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportActionResultsRow
	for rows.Next() {
		var i ListExportActionResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.PhaseID,
			&i.UserID,
			&i.ActionSubmissionID,
			&i.Content,
			&i.SentAt,
			&i.RecipientUsername,
			&i.CharacterName,
			&i.GmUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportActionSubmissions = `-- name: ListExportActionSubmissions :many
SELECT a.id, a.phase_id, a.user_id, a.content, a.submitted_at,
       u.username, ch.name AS character_name
FROM action_submissions a
JOIN users u ON a.user_id = u.id
LEFT JOIN characters ch ON a.character_id = ch.id
WHERE a.game_id = $1 AND a.is_draft = FALSE
ORDER BY a.phase_id, a.submitted_at
`

type ListExportActionSubmissionsRow struct {
	ID            int32              `json:"id"`
	PhaseID       int32              `json:"phase_id"`
	UserID        int32              `json:"user_id"`
	Content       string             `json:"content"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	Username      string             `json:"username"`
	CharacterName pgtype.Text        `json:"character_name"`
}

// Submitted actions only; drafts were never visible to anyone but their author.
// user_id is selected so results can be paired by (phase_id, user_id): see
// ListExportActionResults for why the FK alone is not reliable.
func (q *Queries) ListExportActionSubmissions(ctx context.Context, gameID int32) ([]ListExportActionSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listExportActionSubmissions, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportActionSubmissionsRow
	for rows.Next() {
		var i ListExportActionSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PhaseID,
			&i.UserID,
			&i.Content,
			&i.SubmittedAt,
			&i.Username,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportCharacterData = `-- name: ListExportCharacterData :many
SELECT cd.character_id, cd.module_type, cd.field_name, cd.field_value,
       cd.field_type, cd.is_public
FROM character_data cd
JOIN characters c ON cd.character_id = c.id
WHERE c.game_id = $1
ORDER BY cd.character_id, cd.module_type, cd.field_name
`

type ListExportCharacterDataRow struct {
	CharacterID int32       `json:"character_id"`
	ModuleType  string      `json:"module_type"`
	FieldName   string      `json:"field_name"`
	FieldValue  pgtype.Text `json:"field_value"`
	FieldType   pgtype.Text `json:"field_type"`
	IsPublic    pgtype.Bool `json:"is_public"`
}

// Character sheet fields for the whole game, grouped by character in Go.
func (q *Queries) ListExportCharacterData(ctx context.Context, gameID int32) ([]ListExportCharacterDataRow, error) {
	rows, err := q.db.Query(ctx, listExportCharacterData, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportCharacterDataRow
	for rows.Next() {
		var i ListExportCharacterDataRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.ModuleType,
			&i.FieldName,
			&i.FieldValue,
			&i.FieldType,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportCharacters = `-- name: ListExportCharacters :many
SELECT c.id, c.name, c.character_type, c.status, c.is_active,
       c.created_at, u.username AS player_username
FROM characters c
LEFT JOIN users u ON c.user_id = u.id
WHERE c.game_id = $1
ORDER BY c.character_type, c.name
`

type ListExportCharactersRow struct {
	ID             int32              `json:"id"`
	Name           string             `json:"name"`
	CharacterType  string             `json:"character_type"`
	Status         pgtype.Text        `json:"status"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	PlayerUsername pgtype.Text        `json:"player_username"`
}

// Roster. avatar_url is deliberately NOT selected: archives are text-only.
func (q *Queries) ListExportCharacters(ctx context.Context, gameID int32) ([]ListExportCharactersRow, error) {
	rows, err := q.db.Query(ctx, listExportCharacters, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportCharactersRow
	for rows.Next() {
		var i ListExportCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CharacterType,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
			&i.PlayerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportCommentTree = `-- name: ListExportCommentTree :many
WITH RECURSIVE tree AS (
    SELECT m.id, m.parent_id, m.character_id, m.author_id, m.content,
           m.created_at, m.is_edited, m.edit_count, m.thread_depth,
           ARRAY[m.created_at]::timestamp[] AS path
    FROM messages m
    WHERE m.parent_id = $1
      AND m.is_draft = FALSE
      AND m.is_deleted = FALSE
    UNION ALL
    SELECT child.id, child.parent_id, child.character_id, child.author_id,
           child.content, child.created_at, child.is_edited, child.edit_count,
           child.thread_depth, t.path || child.created_at
    FROM messages child
    JOIN tree t ON child.parent_id = t.id
    WHERE child.is_draft = FALSE
      AND child.is_deleted = FALSE
)
SELECT t.id, t.parent_id, t.content, t.created_at, t.is_edited, t.edit_count,
       t.thread_depth, t.path,
       c.name AS character_name, u.username AS author_username
FROM tree t
JOIN characters c ON t.character_id = c.id
JOIN users u ON t.author_id = u.id
ORDER BY t.path
`

type ListExportCommentTreeRow struct {
	ID             int32              `json:"id"`
	ParentID       pgtype.Int4        `json:"parent_id"`
	Content        string             `json:"content"`
	CreatedAt      pgtype.Timestamp   `json:"created_at"`
	IsEdited       bool               `json:"is_edited"`
	EditCount      int32              `json:"edit_count"`
	ThreadDepth    int32              `json:"thread_depth"`
	Path           []pgtype.Timestamp `json:"path"`
	CharacterName  string             `json:"character_name"`
	AuthorUsername string             `json:"author_username"`
}

// Entire descendant tree of one post in a single recursive pass, ordered by
// materialized path so parents always precede their children. Avoids the
// N+1-per-level walk that deep threads (100+ replies) would otherwise cause.
func (q *Queries) ListExportCommentTree(ctx context.Context, parentID pgtype.Int4) ([]ListExportCommentTreeRow, error) {
	rows, err := q.db.Query(ctx, listExportCommentTree, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportCommentTreeRow
	for rows.Next() {
		var i ListExportCommentTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.IsEdited,
			&i.EditCount,
			&i.ThreadDepth,
			&i.Path,
			&i.CharacterName,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportConversationParticipants = `-- name: ListExportConversationParticipants :many
SELECT cp.conversation_id, u.username, ch.name AS character_name
FROM conversation_participants cp
JOIN conversations c ON cp.conversation_id = c.id
JOIN users u ON cp.user_id = u.id
LEFT JOIN characters ch ON cp.character_id = ch.id
WHERE c.game_id = $1
ORDER BY cp.conversation_id, cp.id
`

type ListExportConversationParticipantsRow struct {
	ConversationID int32       `json:"conversation_id"`
	Username       string      `json:"username"`
	CharacterName  pgtype.Text `json:"character_name"`
}

func (q *Queries) ListExportConversationParticipants(ctx context.Context, gameID int32) ([]ListExportConversationParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listExportConversationParticipants, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportConversationParticipantsRow
	for rows.Next() {
		var i ListExportConversationParticipantsRow
		if err := rows.Scan(&i.ConversationID, &i.Username, &i.CharacterName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportConversations = `-- name: ListExportConversations :many
SELECT c.id, c.title, c.conversation_type, c.created_at
FROM conversations c
WHERE c.game_id = $1
ORDER BY c.created_at
`

type ListExportConversationsRow struct {
	ID               int32              `json:"id"`
	Title            pgtype.Text        `json:"title"`
	ConversationType string             `json:"conversation_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// All private conversations in the game. No participant filter: the audience
// view already exposes these, and a completed game is a public archive.
func (q *Queries) ListExportConversations(ctx context.Context, gameID int32) ([]ListExportConversationsRow, error) {
	rows, err := q.db.Query(ctx, listExportConversations, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportConversationsRow
	for rows.Next() {
		var i ListExportConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ConversationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportHandouts = `-- name: ListExportHandouts :many
SELECT id, title, content, status, created_at, updated_at
FROM handouts
WHERE game_id = $1 AND status = 'published'
ORDER BY created_at
`

type ListExportHandoutsRow struct {
	ID        int32              `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListExportHandouts(ctx context.Context, gameID int32) ([]ListExportHandoutsRow, error) {
	rows, err := q.db.Query(ctx, listExportHandouts, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportHandoutsRow
	for rows.Next() {
		var i ListExportHandoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportParticipants = `-- name: ListExportParticipants :many
SELECT user_id, role, status, joined_at, is_former_player, username
FROM (
    SELECT gp.user_id, gp.role, gp.status, gp.joined_at, gp.is_former_player,
           u.username,
           2 AS sort_rank
    FROM game_participants gp
    JOIN users u ON gp.user_id = u.id
    WHERE gp.game_id = $1
      AND gp.user_id <> (SELECT g.gm_user_id FROM games g WHERE g.id = $1)

    UNION ALL

    SELECT g.gm_user_id AS user_id,
           'gm' AS role,
           'active'::varchar AS status,
           g.created_at AS joined_at,
           FALSE AS is_former_player,
           u.username,
           1 AS sort_rank
    FROM games g
    JOIN users u ON g.gm_user_id = u.id
    WHERE g.id = $1
) roster
ORDER BY sort_rank, role, username
`

type ListExportParticipantsRow struct {
	UserID         int32              `json:"user_id"`
	Role           string             `json:"role"`
	Status         pgtype.Text        `json:"status"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	IsFormerPlayer bool               `json:"is_former_player"`
	Username       string             `json:"username"`
}

// Roster for the archive README.
//
// The primary GM is games.gm_user_id and is NOT guaranteed to have a
// game_participants row, so a plain join silently omits them. Union the GM in
// explicitly, and de-duplicate in case they also hold a participant row.
func (q *Queries) ListExportParticipants(ctx context.Context, gameID int32) ([]ListExportParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listExportParticipants, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportParticipantsRow
	for rows.Next() {
		var i ListExportParticipantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.IsFormerPlayer,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportPhases = `-- name: ListExportPhases :many

SELECT id, phase_type, phase_number, title, description,
       start_time, end_time, deadline, activated_at, created_at
FROM game_phases
WHERE game_id = $1
ORDER BY phase_number
`

type ListExportPhasesRow struct {
	ID          int32              `json:"id"`
	PhaseType   string             `json:"phase_type"`
	PhaseNumber int32              `json:"phase_number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// =============================================================================
// ARCHIVE CONTENT
// =============================================================================
// Every phase that actually ran, in order.
//
// Do NOT filter on is_published: that column means "GM has published this
// ACTION phase's results" and is documented as always FALSE for common_room
// and interlude phases (migration 20251015001708). Filtering on it drops every
// discussion phase and misfiles their content as unfiled.
//
// All phases are exported, including any never activated: a phase row is part
// of the game's structure, an empty phase directory is self-describing, and
// filtering risks orphaning content into "unfiled" the way is_published did.
func (q *Queries) ListExportPhases(ctx context.Context, gameID int32) ([]ListExportPhasesRow, error) {
	rows, err := q.db.Query(ctx, listExportPhases, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportPhasesRow
	for rows.Next() {
		var i ListExportPhasesRow
		if err := rows.Scan(
			&i.ID,
			&i.PhaseType,
			&i.PhaseNumber,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.Deadline,
			&i.ActivatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportPollOptions = `-- name: ListExportPollOptions :many
SELECT o.id, o.poll_id, o.option_text, o.display_order
FROM poll_options o
JOIN common_room_polls p ON o.poll_id = p.id
WHERE p.game_id = $1
  AND p.is_deleted = FALSE
  AND p.hide_results_from_players = FALSE
ORDER BY o.poll_id, o.display_order
`

type ListExportPollOptionsRow struct {
	ID           int32  `json:"id"`
	PollID       int32  `json:"poll_id"`
	OptionText   string `json:"option_text"`
	DisplayOrder int32  `json:"display_order"`
}

// Mirrors the hide_results_from_players exclusion in ListExportPolls.
func (q *Queries) ListExportPollOptions(ctx context.Context, gameID int32) ([]ListExportPollOptionsRow, error) {
	rows, err := q.db.Query(ctx, listExportPollOptions, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportPollOptionsRow
	for rows.Next() {
		var i ListExportPollOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.OptionText,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportPollVotes = `-- name: ListExportPollVotes :many
SELECT v.poll_id, v.selected_option_id, v.other_response, v.created_at,
       u.username AS voter_username
FROM poll_votes v
JOIN common_room_polls p ON v.poll_id = p.id
JOIN users u ON v.user_id = u.id
WHERE p.game_id = $1
  AND p.is_deleted = FALSE
  AND p.hide_results_from_players = FALSE
ORDER BY v.poll_id, v.created_at
`

type ListExportPollVotesRow struct {
	PollID           int32              `json:"poll_id"`
	SelectedOptionID pgtype.Int4        `json:"selected_option_id"`
	OtherResponse    pgtype.Text        `json:"other_response"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	VoterUsername    string             `json:"voter_username"`
}

// Vote tallies WITH voter identity: in a completed game every authenticated
// user sees individual votes regardless of the poll's show_individual_votes
// setting (checkPollViewAccess, backend/pkg/polls/api_polls.go:241). The
// archive therefore matches the completed-game web view.
//
// Hidden-results polls are excluded, matching ListExportPolls.
func (q *Queries) ListExportPollVotes(ctx context.Context, gameID int32) ([]ListExportPollVotesRow, error) {
	rows, err := q.db.Query(ctx, listExportPollVotes, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportPollVotesRow
	for rows.Next() {
		var i ListExportPollVotesRow
		if err := rows.Scan(
			&i.PollID,
			&i.SelectedOptionID,
			&i.OtherResponse,
			&i.CreatedAt,
			&i.VoterUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportPolls = `-- name: ListExportPolls :many
SELECT p.id, p.phase_id, p.question, p.description, p.deadline,
       p.show_individual_votes, p.hide_results_from_players, p.created_at,
       u.username AS creator_username, ch.name AS creator_character_name
FROM common_room_polls p
JOIN users u ON p.created_by_user_id = u.id
LEFT JOIN characters ch ON p.created_by_character_id = ch.id
WHERE p.game_id = $1
  AND p.is_deleted = FALSE
  AND p.hide_results_from_players = FALSE
ORDER BY p.created_at
`

type ListExportPollsRow struct {
	ID                     int32              `json:"id"`
	PhaseID                pgtype.Int4        `json:"phase_id"`
	Question               string             `json:"question"`
	Description            pgtype.Text        `json:"description"`
	Deadline               pgtype.Timestamptz `json:"deadline"`
	ShowIndividualVotes    pgtype.Bool        `json:"show_individual_votes"`
	HideResultsFromPlayers bool               `json:"hide_results_from_players"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	CreatorUsername        string             `json:"creator_username"`
	CreatorCharacterName   pgtype.Text        `json:"creator_character_name"`
}

// Polls flagged hide_results_from_players are EXCLUDED entirely. Completing a
// game does not lift that flag: checkPollViewAccess grants completed-game
// viewers canSeeIndividualVotes but NOT isPrivileged, and the results handler
// refuses hidden-results polls to anyone unprivileged
// (backend/pkg/polls/api_polls.go:553). Only GM/co-GM/audience may ever see
// them, so they must not appear in an archive any authenticated user can read.
func (q *Queries) ListExportPolls(ctx context.Context, gameID int32) ([]ListExportPollsRow, error) {
	rows, err := q.db.Query(ctx, listExportPolls, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportPollsRow
	for rows.Next() {
		var i ListExportPollsRow
		if err := rows.Scan(
			&i.ID,
			&i.PhaseID,
			&i.Question,
			&i.Description,
			&i.Deadline,
			&i.ShowIndividualVotes,
			&i.HideResultsFromPlayers,
			&i.CreatedAt,
			&i.CreatorUsername,
			&i.CreatorCharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportPosts = `-- name: ListExportPosts :many
SELECT m.id, m.phase_id, m.content, m.created_at, m.is_edited, m.edit_count,
       m.mentioned_character_ids,
       c.name AS character_name, u.username AS author_username
FROM messages m
JOIN characters c ON m.character_id = c.id
JOIN users u ON m.author_id = u.id
WHERE m.game_id = $1
  AND m.message_type = 'post'
  AND m.visibility = 'game'
  AND m.is_draft = FALSE
  AND m.is_deleted = FALSE
ORDER BY m.created_at
`

type ListExportPostsRow struct {
	ID                    int32            `json:"id"`
	PhaseID               pgtype.Int4      `json:"phase_id"`
	Content               string           `json:"content"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	IsEdited              bool             `json:"is_edited"`
	EditCount             int32            `json:"edit_count"`
	MentionedCharacterIds []int32          `json:"mentioned_character_ids"`
	CharacterName         string           `json:"character_name"`
	AuthorUsername        string           `json:"author_username"`
}

// Top-level common room posts. Comments are fetched per-post as a tree.
func (q *Queries) ListExportPosts(ctx context.Context, gameID int32) ([]ListExportPostsRow, error) {
	rows, err := q.db.Query(ctx, listExportPosts, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportPostsRow
	for rows.Next() {
		var i ListExportPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.PhaseID,
			&i.Content,
			&i.CreatedAt,
			&i.IsEdited,
			&i.EditCount,
			&i.MentionedCharacterIds,
			&i.CharacterName,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportPrivateMessages = `-- name: ListExportPrivateMessages :many
SELECT pm.id, pm.conversation_id, pm.content, pm.created_at,
       pm.is_edited, pm.edit_count,
       u.username AS sender_username, ch.name AS sender_character_name
FROM private_messages pm
JOIN conversations c ON pm.conversation_id = c.id
JOIN users u ON pm.sender_user_id = u.id
LEFT JOIN characters ch ON pm.sender_character_id = ch.id
WHERE c.game_id = $1 AND pm.is_deleted = FALSE
ORDER BY pm.conversation_id, pm.created_at
`

type ListExportPrivateMessagesRow struct {
	ID                  int32              `json:"id"`
	ConversationID      int32              `json:"conversation_id"`
	Content             string             `json:"content"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	IsEdited            bool               `json:"is_edited"`
	EditCount           int32              `json:"edit_count"`
	SenderUsername      string             `json:"sender_username"`
	SenderCharacterName pgtype.Text        `json:"sender_character_name"`
}

func (q *Queries) ListExportPrivateMessages(ctx context.Context, gameID int32) ([]ListExportPrivateMessagesRow, error) {
	rows, err := q.db.Query(ctx, listExportPrivateMessages, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportPrivateMessagesRow
	for rows.Next() {
		var i ListExportPrivateMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Content,
			&i.CreatedAt,
			&i.IsEdited,
			&i.EditCount,
			&i.SenderUsername,
			&i.SenderCharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGameExportComplete = `-- name: MarkGameExportComplete :one
UPDATE game_exports
SET status = 'complete',
    storage_path = $2,
    size_bytes = $3,
    file_count = $4,
    content_fingerprint = $5,
    progress_note = NULL,
    completed_at = NOW(),
    expires_at = NOW() + $6::interval
WHERE id = $1
RETURNING id, game_id, requested_by_user_id, status, content_fingerprint, storage_path, size_bytes, file_count, error_message, progress_note, started_at, completed_at, expires_at, created_at
`

type MarkGameExportCompleteParams struct {
	ID                 int32           `json:"id"`
	StoragePath        pgtype.Text     `json:"storage_path"`
	SizeBytes          pgtype.Int8     `json:"size_bytes"`
	FileCount          pgtype.Int4     `json:"file_count"`
	ContentFingerprint pgtype.Text     `json:"content_fingerprint"`
	RetentionPeriod    pgtype.Interval `json:"retention_period"`
}

// retention_period sets how long the artifact is kept before the sweep
// reclaims it; the row itself is retained as history.
func (q *Queries) MarkGameExportComplete(ctx context.Context, arg MarkGameExportCompleteParams) (GameExport, error) {
	row := q.db.QueryRow(ctx, markGameExportComplete,
		arg.ID,
		arg.StoragePath,
		arg.SizeBytes,
		arg.FileCount,
		arg.ContentFingerprint,
		arg.RetentionPeriod,
	)
	var i GameExport
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.RequestedByUserID,
		&i.Status,
		&i.ContentFingerprint,
		&i.StoragePath,
		&i.SizeBytes,
		&i.FileCount,
		&i.ErrorMessage,
		&i.ProgressNote,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markGameExportExpired = `-- name: MarkGameExportExpired :exec
UPDATE game_exports
SET storage_path = NULL
WHERE id = $1
`

// Clears the artifact pointer after the file has been deleted from storage.
// The row is kept so export history survives; size/file counts stay for
// reference. Regeneration happens on the next request.
func (q *Queries) MarkGameExportExpired(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markGameExportExpired, id)
	return err
}

const markGameExportFailed = `-- name: MarkGameExportFailed :one
UPDATE game_exports
SET status = 'failed',
    error_message = $2,
    progress_note = NULL,
    completed_at = NOW()
WHERE id = $1
RETURNING id, game_id, requested_by_user_id, status, content_fingerprint, storage_path, size_bytes, file_count, error_message, progress_note, started_at, completed_at, expires_at, created_at
`

type MarkGameExportFailedParams struct {
	ID           int32       `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkGameExportFailed(ctx context.Context, arg MarkGameExportFailedParams) (GameExport, error) {
	row := q.db.QueryRow(ctx, markGameExportFailed, arg.ID, arg.ErrorMessage)
	var i GameExport
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.RequestedByUserID,
		&i.Status,
		&i.ContentFingerprint,
		&i.StoragePath,
		&i.SizeBytes,
		&i.FileCount,
		&i.ErrorMessage,
		&i.ProgressNote,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markGameExportProgress = `-- name: MarkGameExportProgress :exec
UPDATE game_exports SET progress_note = $2 WHERE id = $1
`

type MarkGameExportProgressParams struct {
	ID           int32       `json:"id"`
	ProgressNote pgtype.Text `json:"progress_note"`
}

func (q *Queries) MarkGameExportProgress(ctx context.Context, arg MarkGameExportProgressParams) error {
	_, err := q.db.Exec(ctx, markGameExportProgress, arg.ID, arg.ProgressNote)
	return err
}

const requeueStalledGameExports = `-- name: RequeueStalledGameExports :execrows
UPDATE game_exports
SET status = 'pending', started_at = NULL, progress_note = NULL
WHERE status = 'running'
  AND started_at < NOW() - $1::interval
`

// Startup crash recovery: return jobs left 'running' by a dead process to
// 'pending'. Bounded by age so a job actively running elsewhere is untouched.
func (q *Queries) RequeueStalledGameExports(ctx context.Context, staleAfter pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, requeueStalledGameExports, staleAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
