// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games_listing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFilteredGames = `-- name: CountFilteredGames :one
SELECT COUNT(*)
FROM games g
WHERE
  -- Show public games, OR games user is in, OR all games if admin mode enabled and user is admin
  (g.is_public = true OR
   ($5::boolean IS TRUE AND $6::int IS NOT NULL AND EXISTS(SELECT 1 FROM users WHERE id = $6 AND is_admin = true)) OR
   ($1::int IS NOT NULL AND (g.gm_user_id = $1 OR EXISTS(SELECT 1 FROM game_participants WHERE game_id = g.id AND user_id = $1 AND status = 'active'))))

  -- Filter by states (optional array of states)
  AND ($2::text[] IS NULL OR g.state = ANY($2::text[]))

  -- Filter by user participation (optional)
  AND (
    $3::text IS NULL OR $3 = '' OR
    ($3 = 'my_games' AND ($1::int IS NOT NULL AND (g.gm_user_id = $1 OR EXISTS(SELECT 1 FROM game_participants WHERE game_id = g.id AND user_id = $1 AND status = 'active')))) OR
    ($3 = 'applied' AND ($1::int IS NOT NULL AND EXISTS(SELECT 1 FROM game_applications WHERE game_id = g.id AND user_id = $1 AND status = 'pending'))) OR
    ($3 = 'not_joined' AND ($1::int IS NOT NULL AND g.gm_user_id != $1 AND NOT EXISTS(SELECT 1 FROM game_participants WHERE game_id = g.id AND user_id = $1)))
  )

  -- Filter by open spots (only recruiting games with available spots)
  AND (
    $4::boolean IS NOT true OR
    (
      g.state = 'recruitment' AND
      (g.max_players IS NULL OR (SELECT COUNT(*) FROM game_participants WHERE game_id = g.id AND status = 'active' AND role = 'player') < g.max_players)
    )
  )

  -- Filter by search text (case-insensitive search in title and description)
  AND (
    $7::text IS NULL OR $7 = '' OR
    g.title ILIKE '%' || $7 || '%' OR
    g.description::text ILIKE '%' || $7 || '%'
  )

  -- Filter by community. Must mirror GetFilteredGames exactly or the count and
  -- the page disagree and pagination breaks.
  AND ($8::int IS NULL OR $8 = 0 OR g.community_id = $8)
`

type CountFilteredGamesParams struct {
	Column1 int32    `json:"column_1"`
	Column2 []string `json:"column_2"`
	Column3 string   `json:"column_3"`
	Column4 bool     `json:"column_4"`
	Column5 bool     `json:"column_5"`
	Column6 int32    `json:"column_6"`
	Column7 string   `json:"column_7"`
	Column8 int32    `json:"column_8"`
}

// Count games matching the same filters as GetFilteredGames (for pagination metadata)
func (q *Queries) CountFilteredGames(ctx context.Context, arg CountFilteredGamesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredGames,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicGames = `-- name: CountPublicGames :one

SELECT COUNT(*) FROM games WHERE is_public = true
`

// Parameters:
// $1: user_id (int, nullable) - for participation enrichment
// $2: states (text[], nullable) - array of game states to filter
// $3: participation_filter (text, nullable) - 'my_games', 'applied', 'not_joined'
// $4: has_open_spots (boolean, nullable) - only games with available spots
// $5: sort_by (text) - 'recent_activity', 'created', 'start_date', 'alphabetical'
// $6: admin_mode (boolean) - bypass is_public filter if user is admin
// $7: admin_user_id (int, nullable) - user ID to validate admin status
// $8: search (text, nullable) - case-insensitive search in title and description
// $9: limit (int) - number of records per page
// $10: offset (int) - number of records to skip
func (q *Queries) CountPublicGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicGames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAvailableStates = `-- name: GetAvailableStates :many

SELECT DISTINCT state
FROM games
WHERE is_public = true
ORDER BY state ASC
`

// Parameters:
// $1: user_id (int, nullable) - for participation enrichment
// $2: states (text[], nullable) - array of game states to filter
// $3: participation_filter (text, nullable) - 'my_games', 'applied', 'not_joined'
// $4: has_open_spots (boolean, nullable) - only games with available spots
// $5: admin_mode (boolean) - bypass is_public filter if user is admin
// $6: admin_user_id (int, nullable) - user ID to validate admin status
// $7: search (text, nullable) - case-insensitive search in title and description
// $8: community_id (int, nullable) - 0/NULL means every community
func (q *Queries) GetAvailableStates(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getAvailableStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var state pgtype.Text
		if err := rows.Scan(&state); err != nil {
			return nil, err
		}
		items = append(items, state)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilteredGames = `-- name: GetFilteredGames :many
SELECT
  g.id,
  g.title,
  g.description,
  g.gm_user_id,
  u.username as gm_username,
  g.state,
  g.genre,
  g.start_date,
  g.end_date,
  g.recruitment_deadline,
  g.max_players,
  g.is_public,
  g.is_anonymous,
  g.auto_accept_audience,
  g.allow_group_conversations,
  g.portrait_avatars,
  g.banner_url,
  g.community_id,
  -- LEFT JOIN, not INNER: games predating communities have community_id NULL
  -- (req 5) and must still appear in every listing.
  c.name as community_name,
  c.slug as community_slug,
  g.created_at,
  g.updated_at,

  -- Computed fields
  (SELECT COUNT(*) FROM game_participants WHERE game_id = g.id AND status = 'active' AND role = 'player') as current_players,

  -- User participation status (empty string if not logged in)
  COALESCE(
    CASE
      WHEN $1::int IS NULL OR $1 = 0 THEN NULL
      WHEN g.gm_user_id = $1 THEN 'gm'
      -- Split by role: the badge in the games list distinguishes Player from
      -- Audience from Co-GM, so collapsing them into 'participant' would show
      -- an audience member "Player".
      WHEN EXISTS(SELECT 1 FROM game_participants WHERE game_id = g.id AND user_id = $1 AND status = 'active' AND role = 'co_gm') THEN 'co_gm'
      WHEN EXISTS(SELECT 1 FROM game_participants WHERE game_id = g.id AND user_id = $1 AND status = 'active' AND role = 'audience') THEN 'audience'
      WHEN EXISTS(SELECT 1 FROM game_participants WHERE game_id = g.id AND user_id = $1 AND status = 'active') THEN 'participant'
      WHEN EXISTS(SELECT 1 FROM game_applications WHERE game_id = g.id AND user_id = $1) THEN 'applied'
      ELSE 'none'
    END,
    ''
  ) as user_relationship,

  -- Current phase info for in-progress games (empty string if none)
  COALESCE((SELECT phase_type FROM game_phases WHERE game_id = g.id AND is_active = true), '') as current_phase_type,
  (SELECT end_time FROM game_phases WHERE game_id = g.id AND is_active = true) as current_phase_deadline,

  -- Deadline urgency calculation
  CASE
    WHEN g.state = 'recruitment' AND g.recruitment_deadline IS NOT NULL THEN
      CASE
        WHEN g.recruitment_deadline < NOW() + INTERVAL '24 hours' THEN 'critical'
        WHEN g.recruitment_deadline < NOW() + INTERVAL '3 days' THEN 'warning'
        ELSE 'normal'
      END
    WHEN g.state = 'in_progress' THEN
      CASE
        WHEN (SELECT end_time FROM game_phases WHERE game_id = g.id AND is_active = true) < NOW() + INTERVAL '24 hours' THEN 'critical'
        WHEN (SELECT end_time FROM game_phases WHERE game_id = g.id AND is_active = true) < NOW() + INTERVAL '3 days' THEN 'warning'
        ELSE 'normal'
      END
    ELSE 'normal'
  END as deadline_urgency,

  -- Recent activity flag (updated in last 24h)
  (g.updated_at > NOW() - INTERVAL '24 hours') as has_recent_activity

FROM games g
INNER JOIN users u ON g.gm_user_id = u.id
LEFT JOIN communities c ON c.id = g.community_id
WHERE
  -- Show public games, OR games user is in, OR all games if admin mode enabled and user is admin
  (g.is_public = true OR
   ($6::boolean IS TRUE AND $7::int IS NOT NULL AND EXISTS(SELECT 1 FROM users WHERE id = $7 AND is_admin = true)) OR
   ($1::int IS NOT NULL AND (g.gm_user_id = $1 OR EXISTS(SELECT 1 FROM game_participants WHERE game_id = g.id AND user_id = $1 AND status = 'active'))))

  -- Filter by states (optional array of states)
  AND ($2::text[] IS NULL OR g.state = ANY($2::text[]))

  -- Filter by user participation (optional)
  AND (
    $3::text IS NULL OR $3 = '' OR
    ($3 = 'my_games' AND ($1::int IS NOT NULL AND (g.gm_user_id = $1 OR EXISTS(SELECT 1 FROM game_participants WHERE game_id = g.id AND user_id = $1 AND status = 'active')))) OR
    ($3 = 'applied' AND ($1::int IS NOT NULL AND EXISTS(SELECT 1 FROM game_applications WHERE game_id = g.id AND user_id = $1 AND status = 'pending'))) OR
    ($3 = 'not_joined' AND ($1::int IS NOT NULL AND g.gm_user_id != $1 AND NOT EXISTS(SELECT 1 FROM game_participants WHERE game_id = g.id AND user_id = $1)))
  )

  -- Filter by open spots (only recruiting games with available spots)
  AND (
    $4::boolean IS NOT true OR
    (
      g.state = 'recruitment' AND
      (g.max_players IS NULL OR (SELECT COUNT(*) FROM game_participants WHERE game_id = g.id AND status = 'active' AND role = 'player') < g.max_players)
    )
  )

  -- Filter by search text (case-insensitive search in title and description)
  AND (
    $8::text IS NULL OR $8 = '' OR
    g.title ILIKE '%' || $8 || '%' OR
    g.description::text ILIKE '%' || $8 || '%'
  )

  -- Filter by community (0 or NULL means "every community"). Legacy games with
  -- community_id NULL are excluded when a community IS named -- they belong to
  -- none, so they are not in it.
  AND ($11::int IS NULL OR $11 = 0 OR g.community_id = $11)

ORDER BY
  -- Dynamic sorting based on $5 parameter
  CASE
    WHEN $5 = 'recent_activity' THEN g.updated_at
    WHEN $5 = 'created' THEN g.created_at
    WHEN $5 = 'start_date' THEN g.start_date
    WHEN $5 = 'alphabetical' THEN NULL
    ELSE g.updated_at
  END DESC NULLS LAST,

  CASE
    WHEN $5 = 'alphabetical' THEN g.title
    ELSE NULL
  END ASC NULLS LAST,

  -- Secondary sort by ID for consistency
  g.id DESC

LIMIT $9::int
OFFSET $10::int
`

type GetFilteredGamesParams struct {
	Column1  int32       `json:"column_1"`
	Column2  []string    `json:"column_2"`
	Column3  string      `json:"column_3"`
	Column4  bool        `json:"column_4"`
	Column5  interface{} `json:"column_5"`
	Column6  bool        `json:"column_6"`
	Column7  int32       `json:"column_7"`
	Column8  string      `json:"column_8"`
	Column9  int32       `json:"column_9"`
	Column10 int32       `json:"column_10"`
	Column11 int32       `json:"column_11"`
}

type GetFilteredGamesRow struct {
	ID                      int32              `json:"id"`
	Title                   string             `json:"title"`
	Description             pgtype.Text        `json:"description"`
	GmUserID                int32              `json:"gm_user_id"`
	GmUsername              string             `json:"gm_username"`
	State                   pgtype.Text        `json:"state"`
	Genre                   pgtype.Text        `json:"genre"`
	StartDate               pgtype.Timestamptz `json:"start_date"`
	EndDate                 pgtype.Timestamptz `json:"end_date"`
	RecruitmentDeadline     pgtype.Timestamptz `json:"recruitment_deadline"`
	MaxPlayers              pgtype.Int4        `json:"max_players"`
	IsPublic                pgtype.Bool        `json:"is_public"`
	IsAnonymous             bool               `json:"is_anonymous"`
	AutoAcceptAudience      bool               `json:"auto_accept_audience"`
	AllowGroupConversations bool               `json:"allow_group_conversations"`
	PortraitAvatars         bool               `json:"portrait_avatars"`
	BannerUrl               pgtype.Text        `json:"banner_url"`
	CommunityID             pgtype.Int4        `json:"community_id"`
	CommunityName           pgtype.Text        `json:"community_name"`
	CommunitySlug           pgtype.Text        `json:"community_slug"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	CurrentPlayers          int64              `json:"current_players"`
	UserRelationship        interface{}        `json:"user_relationship"`
	CurrentPhaseType        interface{}        `json:"current_phase_type"`
	CurrentPhaseDeadline    pgtype.Timestamptz `json:"current_phase_deadline"`
	DeadlineUrgency         string             `json:"deadline_urgency"`
	HasRecentActivity       bool               `json:"has_recent_activity"`
}

// Get games with filters, sorting, and user participation enrichment
// Pagination
func (q *Queries) GetFilteredGames(ctx context.Context, arg GetFilteredGamesParams) ([]GetFilteredGamesRow, error) {
	rows, err := q.db.Query(ctx, getFilteredGames,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilteredGamesRow
	for rows.Next() {
		var i GetFilteredGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GmUserID,
			&i.GmUsername,
			&i.State,
			&i.Genre,
			&i.StartDate,
			&i.EndDate,
			&i.RecruitmentDeadline,
			&i.MaxPlayers,
			&i.IsPublic,
			&i.IsAnonymous,
			&i.AutoAcceptAudience,
			&i.AllowGroupConversations,
			&i.PortraitAvatars,
			&i.BannerUrl,
			&i.CommunityID,
			&i.CommunityName,
			&i.CommunitySlug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentPlayers,
			&i.UserRelationship,
			&i.CurrentPhaseType,
			&i.CurrentPhaseDeadline,
			&i.DeadlineUrgency,
			&i.HasRecentActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
