// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_loot_tables.sql

package db

import (
	"context"
)

const createLootTable = `-- name: CreateLootTable :one
INSERT INTO game_loot_tables (
    game_id, name
) VALUES (
    $1, $2
) RETURNING id, game_id, name, created_at, updated_at
`

type CreateLootTableParams struct {
	GameID int32  `json:"game_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateLootTable(ctx context.Context, arg CreateLootTableParams) (GameLootTable, error) {
	row := q.db.QueryRow(ctx, createLootTable, arg.GameID, arg.Name)
	var i GameLootTable
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLootTable = `-- name: DeleteLootTable :exec
DELETE FROM game_loot_tables WHERE id = $1
`

func (q *Queries) DeleteLootTable(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLootTable, id)
	return err
}

const getLootTables = `-- name: GetLootTables :many
SELECT
    id, game_id, name, created_at, updated_at
FROM game_loot_tables
WHERE game_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetLootTables(ctx context.Context, gameID int32) ([]GameLootTable, error) {
	rows, err := q.db.Query(ctx, getLootTables, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameLootTable
	for rows.Next() {
		var i GameLootTable
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isLootTableInGame = `-- name: IsLootTableInGame :one
SELECT
    EXISTS(SELECT 1 FROM game_loot_tables WHERE game_id = $1 AND id = $2)
    AS is_game_loot_table
`

type IsLootTableInGameParams struct {
	GameID int32 `json:"game_id"`
	ID     int32 `json:"id"`
}

// Handlers MUST call this before mutating a loot table by ID: the update and
// delete below are keyed on id alone, so this is what enforces game ownership.
// Covered by TestLootTableEndpointsRejectCrossGameAccess.
func (q *Queries) IsLootTableInGame(ctx context.Context, arg IsLootTableInGameParams) (bool, error) {
	row := q.db.QueryRow(ctx, isLootTableInGame, arg.GameID, arg.ID)
	var is_game_loot_table bool
	err := row.Scan(&is_game_loot_table)
	return is_game_loot_table, err
}

const touchLootTable = `-- name: TouchLootTable :exec
UPDATE game_loot_tables
SET updated_at = NOW()
WHERE id = $1
`

// Contents live in a child table, so rewriting them leaves the parent row
// untouched and updated_at stale. Handlers that change contents MUST call this
// so "Updated" reflects item edits, which are the common operation — renaming is
// comparatively rare.
func (q *Queries) TouchLootTable(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, touchLootTable, id)
	return err
}

const updateLootTable = `-- name: UpdateLootTable :one
UPDATE game_loot_tables
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, game_id, name, created_at, updated_at
`

type UpdateLootTableParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateLootTable(ctx context.Context, arg UpdateLootTableParams) (GameLootTable, error) {
	row := q.db.QueryRow(ctx, updateLootTable, arg.ID, arg.Name)
	var i GameLootTable
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
