// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGameParticipant = `-- name: AddGameParticipant :one
INSERT INTO game_participants (game_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (game_id, user_id) DO UPDATE
SET role = EXCLUDED.role,
    status = 'active',
    removed_at = NULL,
    removed_by_user_id = NULL,
    is_former_player = game_participants.is_former_player,
    joined_at = NOW()
WHERE game_participants.status != 'active'
RETURNING id, game_id, user_id, role, status, joined_at, removed_at, removed_by_user_id, is_former_player
`

type AddGameParticipantParams struct {
	GameID int32  `json:"game_id"`
	UserID int32  `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) AddGameParticipant(ctx context.Context, arg AddGameParticipantParams) (GameParticipant, error) {
	row := q.db.QueryRow(ctx, addGameParticipant, arg.GameID, arg.UserID, arg.Role)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.IsFormerPlayer,
	)
	return i, err
}

const addParticipantWithRole = `-- name: AddParticipantWithRole :one
INSERT INTO game_participants (game_id, user_id, role, status)
VALUES ($1, $2, $3, 'active')
ON CONFLICT (game_id, user_id) DO UPDATE
SET removed_at = NULL,
    removed_by_user_id = NULL,
    status = 'active',
    role = EXCLUDED.role,
    joined_at = NOW()
WHERE game_participants.removed_at IS NOT NULL
RETURNING id, game_id, user_id, role, status, joined_at, removed_at, removed_by_user_id, is_former_player
`

type AddParticipantWithRoleParams struct {
	GameID int32  `json:"game_id"`
	UserID int32  `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) AddParticipantWithRole(ctx context.Context, arg AddParticipantWithRoleParams) (GameParticipant, error) {
	row := q.db.QueryRow(ctx, addParticipantWithRole, arg.GameID, arg.UserID, arg.Role)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.IsFormerPlayer,
	)
	return i, err
}

const canUserJoinGame = `-- name: CanUserJoinGame :one
SELECT
    CASE
        WHEN g.state != 'recruitment' THEN 'game_not_recruiting'
        WHEN g.recruitment_deadline IS NOT NULL AND g.recruitment_deadline < NOW() THEN 'deadline_passed'
        WHEN COALESCE(pc.player_count, 0) >= g.max_players THEN 'game_full'
        WHEN EXISTS(SELECT 1 FROM game_participants gp WHERE gp.game_id = $1 AND gp.user_id = $2 AND gp.status = 'active') THEN 'already_joined'
        ELSE 'can_join'
    END as join_status
FROM games g
LEFT JOIN (
    SELECT game_id, COUNT(*) as player_count
    FROM game_participants
    WHERE role = 'player' AND status = 'active'
    GROUP BY game_id
) pc ON g.id = pc.game_id
WHERE g.id = $1
`

type CanUserJoinGameParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) CanUserJoinGame(ctx context.Context, arg CanUserJoinGameParams) (string, error) {
	row := q.db.QueryRow(ctx, canUserJoinGame, arg.GameID, arg.UserID)
	var join_status string
	err := row.Scan(&join_status)
	return join_status, err
}

const checkAudienceAccess = `-- name: CheckAudienceAccess :one
SELECT EXISTS(
    SELECT 1 FROM game_participants
    WHERE game_id = $1 AND user_id = $2 AND role IN ('audience', 'co_gm') AND status = 'active'
) OR EXISTS(
    SELECT 1 FROM games
    WHERE id = $1 AND gm_user_id = $2
)
`

type CheckAudienceAccessParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) CheckAudienceAccess(ctx context.Context, arg CheckAudienceAccessParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, checkAudienceAccess, arg.GameID, arg.UserID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkParticipantExists = `-- name: CheckParticipantExists :one
SELECT EXISTS(
    SELECT 1 FROM game_participants
    WHERE game_id = $1 AND user_id = $2 AND removed_at IS NULL AND status = 'active'
)
`

type CheckParticipantExistsParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) CheckParticipantExists(ctx context.Context, arg CheckParticipantExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkParticipantExists, arg.GameID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCoGMsInGame = `-- name: CountCoGMsInGame :one
SELECT COUNT(*) FROM game_participants
WHERE game_id = $1 AND role = 'co_gm' AND status = 'active'
`

func (q *Queries) CountCoGMsInGame(ctx context.Context, gameID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countCoGMsInGame, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAudienceApplication = `-- name: CreateAudienceApplication :one
INSERT INTO game_participants (game_id, user_id, role, status)
VALUES ($1, $2, 'audience', $3)
ON CONFLICT (game_id, user_id) DO UPDATE
SET removed_at = NULL,
    removed_by_user_id = NULL,
    status = EXCLUDED.status,
    role = 'audience',
    joined_at = NOW()
WHERE game_participants.removed_at IS NOT NULL OR game_participants.status = 'removed'
RETURNING id, game_id, user_id, role, status, joined_at, removed_at, removed_by_user_id, is_former_player
`

type CreateAudienceApplicationParams struct {
	GameID int32       `json:"game_id"`
	UserID int32       `json:"user_id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) CreateAudienceApplication(ctx context.Context, arg CreateAudienceApplicationParams) (GameParticipant, error) {
	row := q.db.QueryRow(ctx, createAudienceApplication, arg.GameID, arg.UserID, arg.Status)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.IsFormerPlayer,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (
    title, description, gm_user_id, genre, start_date, end_date,
    recruitment_deadline, max_players, is_public, is_anonymous, auto_accept_audience, allow_group_conversations, portrait_avatars, banner_url,
    common_room_open_day, common_room_open_time, common_room_close_day, common_room_close_time, schedule_timezone,
    character_sheet
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19,
    -- COALESCE so a caller that builds CreateGameParams directly and leaves
    -- CharacterSheet nil gets '{}' rather than a NOT NULL violation. Naming the
    -- column in the INSERT disables the column DEFAULT, so the default has to be
    -- restated here.
    COALESCE($20::jsonb, '{}'::jsonb)
) RETURNING id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, is_anonymous, auto_accept_audience, allow_group_conversations, portrait_avatars, banner_url, common_room_open_day, common_room_open_time, common_room_close_day, common_room_close_time, schedule_timezone, character_sheet, created_at, updated_at
`

type CreateGameParams struct {
	Title                   string             `json:"title"`
	Description             pgtype.Text        `json:"description"`
	GmUserID                int32              `json:"gm_user_id"`
	Genre                   pgtype.Text        `json:"genre"`
	StartDate               pgtype.Timestamptz `json:"start_date"`
	EndDate                 pgtype.Timestamptz `json:"end_date"`
	RecruitmentDeadline     pgtype.Timestamptz `json:"recruitment_deadline"`
	MaxPlayers              pgtype.Int4        `json:"max_players"`
	IsPublic                pgtype.Bool        `json:"is_public"`
	IsAnonymous             bool               `json:"is_anonymous"`
	AutoAcceptAudience      bool               `json:"auto_accept_audience"`
	AllowGroupConversations bool               `json:"allow_group_conversations"`
	PortraitAvatars         bool               `json:"portrait_avatars"`
	BannerUrl               pgtype.Text        `json:"banner_url"`
	CommonRoomOpenDay       pgtype.Int2        `json:"common_room_open_day"`
	CommonRoomOpenTime      pgtype.Time        `json:"common_room_open_time"`
	CommonRoomCloseDay      pgtype.Int2        `json:"common_room_close_day"`
	CommonRoomCloseTime     pgtype.Time        `json:"common_room_close_time"`
	ScheduleTimezone        pgtype.Text        `json:"schedule_timezone"`
	CharacterSheet          []byte             `json:"character_sheet"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.Title,
		arg.Description,
		arg.GmUserID,
		arg.Genre,
		arg.StartDate,
		arg.EndDate,
		arg.RecruitmentDeadline,
		arg.MaxPlayers,
		arg.IsPublic,
		arg.IsAnonymous,
		arg.AutoAcceptAudience,
		arg.AllowGroupConversations,
		arg.PortraitAvatars,
		arg.BannerUrl,
		arg.CommonRoomOpenDay,
		arg.CommonRoomOpenTime,
		arg.CommonRoomCloseDay,
		arg.CommonRoomCloseTime,
		arg.ScheduleTimezone,
		arg.CharacterSheet,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GmUserID,
		&i.State,
		&i.Genre,
		&i.StartDate,
		&i.EndDate,
		&i.RecruitmentDeadline,
		&i.MaxPlayers,
		&i.IsPublic,
		&i.IsAnonymous,
		&i.AutoAcceptAudience,
		&i.AllowGroupConversations,
		&i.PortraitAvatars,
		&i.BannerUrl,
		&i.CommonRoomOpenDay,
		&i.CommonRoomOpenTime,
		&i.CommonRoomCloseDay,
		&i.CommonRoomCloseTime,
		&i.ScheduleTimezone,
		&i.CharacterSheet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games WHERE id = $1 AND state = 'cancelled'
`

// Only allow deletion of cancelled games
// Foreign key constraints will cascade delete related data
func (q *Queries) DeleteGame(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const disableAnonymousMode = `-- name: DisableAnonymousMode :exec
UPDATE games
SET is_anonymous = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DisableAnonymousMode(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, disableAnonymousMode, id)
	return err
}

const getActiveParticipants = `-- name: GetActiveParticipants :many
SELECT gp.id, gp.game_id, gp.user_id, gp.role, gp.status, gp.joined_at, gp.removed_at, gp.removed_by_user_id, gp.is_former_player, u.username, u.email
FROM game_participants gp
JOIN users u ON gp.user_id = u.id
WHERE gp.game_id = $1 AND gp.removed_at IS NULL AND gp.status = 'active'
ORDER BY gp.joined_at
`

type GetActiveParticipantsRow struct {
	ID              int32              `json:"id"`
	GameID          int32              `json:"game_id"`
	UserID          int32              `json:"user_id"`
	Role            string             `json:"role"`
	Status          pgtype.Text        `json:"status"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
	RemovedAt       pgtype.Timestamptz `json:"removed_at"`
	RemovedByUserID pgtype.Int4        `json:"removed_by_user_id"`
	IsFormerPlayer  bool               `json:"is_former_player"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
}

func (q *Queries) GetActiveParticipants(ctx context.Context, gameID int32) ([]GetActiveParticipantsRow, error) {
	rows, err := q.db.Query(ctx, getActiveParticipants, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveParticipantsRow
	for rows.Next() {
		var i GetActiveParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.RemovedAt,
			&i.RemovedByUserID,
			&i.IsFormerPlayer,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGame = `-- name: GetGame :one
SELECT id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, is_anonymous, auto_accept_audience, allow_group_conversations, portrait_avatars, banner_url, common_room_open_day, common_room_open_time, common_room_close_day, common_room_close_time, schedule_timezone, character_sheet, created_at, updated_at FROM games WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GmUserID,
		&i.State,
		&i.Genre,
		&i.StartDate,
		&i.EndDate,
		&i.RecruitmentDeadline,
		&i.MaxPlayers,
		&i.IsPublic,
		&i.IsAnonymous,
		&i.AutoAcceptAudience,
		&i.AllowGroupConversations,
		&i.PortraitAvatars,
		&i.BannerUrl,
		&i.CommonRoomOpenDay,
		&i.CommonRoomOpenTime,
		&i.CommonRoomCloseDay,
		&i.CommonRoomCloseTime,
		&i.ScheduleTimezone,
		&i.CharacterSheet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameAutoAcceptAudience = `-- name: GetGameAutoAcceptAudience :one

SELECT auto_accept_audience FROM games WHERE id = $1
`

// Audience Participation Queries
func (q *Queries) GetGameAutoAcceptAudience(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, getGameAutoAcceptAudience, id)
	var auto_accept_audience bool
	err := row.Scan(&auto_accept_audience)
	return auto_accept_audience, err
}

const getGameCoGMs = `-- name: GetGameCoGMs :many
SELECT user_id FROM game_participants
WHERE game_id = $1 AND role = 'co_gm' AND status = 'active'
`

func (q *Queries) GetGameCoGMs(ctx context.Context, gameID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getGameCoGMs, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var user_id int32
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameParticipantCount = `-- name: GetGameParticipantCount :one
SELECT COUNT(*) FROM game_participants
WHERE game_id = $1 AND role = 'player' AND status = 'active'
`

func (q *Queries) GetGameParticipantCount(ctx context.Context, gameID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getGameParticipantCount, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGameParticipants = `-- name: GetGameParticipants :many
SELECT gp.id, gp.game_id, gp.user_id, gp.role, gp.status, gp.joined_at, gp.removed_at, gp.removed_by_user_id, gp.is_former_player, u.username, u.avatar_url
FROM game_participants gp
JOIN users u ON gp.user_id = u.id
WHERE gp.game_id = $1 AND gp.status = 'active'
ORDER BY gp.joined_at
`

type GetGameParticipantsRow struct {
	ID              int32              `json:"id"`
	GameID          int32              `json:"game_id"`
	UserID          int32              `json:"user_id"`
	Role            string             `json:"role"`
	Status          pgtype.Text        `json:"status"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
	RemovedAt       pgtype.Timestamptz `json:"removed_at"`
	RemovedByUserID pgtype.Int4        `json:"removed_by_user_id"`
	IsFormerPlayer  bool               `json:"is_former_player"`
	Username        string             `json:"username"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetGameParticipants(ctx context.Context, gameID int32) ([]GetGameParticipantsRow, error) {
	rows, err := q.db.Query(ctx, getGameParticipants, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameParticipantsRow
	for rows.Next() {
		var i GetGameParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.RemovedAt,
			&i.RemovedByUserID,
			&i.IsFormerPlayer,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameWithDetails = `-- name: GetGameWithDetails :one
SELECT
    g.id, g.title, g.description, g.gm_user_id, g.state, g.genre, g.start_date, g.end_date, g.recruitment_deadline, g.max_players, g.is_public, g.is_anonymous, g.auto_accept_audience, g.allow_group_conversations, g.portrait_avatars, g.banner_url, g.common_room_open_day, g.common_room_open_time, g.common_room_close_day, g.common_room_close_time, g.schedule_timezone, g.character_sheet, g.created_at, g.updated_at,
    u.username as gm_username,
    COALESCE(pc.player_count, 0) as current_players
FROM games g
LEFT JOIN users u ON g.gm_user_id = u.id
LEFT JOIN (
    SELECT game_id, COUNT(*) as player_count
    FROM game_participants
    WHERE role = 'player' AND status = 'active'
    GROUP BY game_id
) pc ON g.id = pc.game_id
WHERE g.id = $1
`

type GetGameWithDetailsRow struct {
	ID                      int32              `json:"id"`
	Title                   string             `json:"title"`
	Description             pgtype.Text        `json:"description"`
	GmUserID                int32              `json:"gm_user_id"`
	State                   pgtype.Text        `json:"state"`
	Genre                   pgtype.Text        `json:"genre"`
	StartDate               pgtype.Timestamptz `json:"start_date"`
	EndDate                 pgtype.Timestamptz `json:"end_date"`
	RecruitmentDeadline     pgtype.Timestamptz `json:"recruitment_deadline"`
	MaxPlayers              pgtype.Int4        `json:"max_players"`
	IsPublic                pgtype.Bool        `json:"is_public"`
	IsAnonymous             bool               `json:"is_anonymous"`
	AutoAcceptAudience      bool               `json:"auto_accept_audience"`
	AllowGroupConversations bool               `json:"allow_group_conversations"`
	PortraitAvatars         bool               `json:"portrait_avatars"`
	BannerUrl               pgtype.Text        `json:"banner_url"`
	CommonRoomOpenDay       pgtype.Int2        `json:"common_room_open_day"`
	CommonRoomOpenTime      pgtype.Time        `json:"common_room_open_time"`
	CommonRoomCloseDay      pgtype.Int2        `json:"common_room_close_day"`
	CommonRoomCloseTime     pgtype.Time        `json:"common_room_close_time"`
	ScheduleTimezone        pgtype.Text        `json:"schedule_timezone"`
	CharacterSheet          []byte             `json:"character_sheet"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	GmUsername              pgtype.Text        `json:"gm_username"`
	CurrentPlayers          int64              `json:"current_players"`
}

func (q *Queries) GetGameWithDetails(ctx context.Context, id int32) (GetGameWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getGameWithDetails, id)
	var i GetGameWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GmUserID,
		&i.State,
		&i.Genre,
		&i.StartDate,
		&i.EndDate,
		&i.RecruitmentDeadline,
		&i.MaxPlayers,
		&i.IsPublic,
		&i.IsAnonymous,
		&i.AutoAcceptAudience,
		&i.AllowGroupConversations,
		&i.PortraitAvatars,
		&i.BannerUrl,
		&i.CommonRoomOpenDay,
		&i.CommonRoomOpenTime,
		&i.CommonRoomCloseDay,
		&i.CommonRoomCloseTime,
		&i.ScheduleTimezone,
		&i.CharacterSheet,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GmUsername,
		&i.CurrentPlayers,
	)
	return i, err
}

const getGamesByGM = `-- name: GetGamesByGM :many
SELECT id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, is_anonymous, auto_accept_audience, allow_group_conversations, portrait_avatars, banner_url, common_room_open_day, common_room_open_time, common_room_close_day, common_room_close_time, schedule_timezone, character_sheet, created_at, updated_at FROM games WHERE gm_user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetGamesByGM(ctx context.Context, gmUserID int32) ([]Game, error) {
	rows, err := q.db.Query(ctx, getGamesByGM, gmUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GmUserID,
			&i.State,
			&i.Genre,
			&i.StartDate,
			&i.EndDate,
			&i.RecruitmentDeadline,
			&i.MaxPlayers,
			&i.IsPublic,
			&i.IsAnonymous,
			&i.AutoAcceptAudience,
			&i.AllowGroupConversations,
			&i.PortraitAvatars,
			&i.BannerUrl,
			&i.CommonRoomOpenDay,
			&i.CommonRoomOpenTime,
			&i.CommonRoomCloseDay,
			&i.CommonRoomCloseTime,
			&i.ScheduleTimezone,
			&i.CharacterSheet,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesByUser = `-- name: GetGamesByUser :many
SELECT g.id, g.title, g.description, g.gm_user_id, g.state, g.genre, g.start_date, g.end_date, g.recruitment_deadline, g.max_players, g.is_public, g.is_anonymous, g.auto_accept_audience, g.allow_group_conversations, g.portrait_avatars, g.banner_url, g.common_room_open_day, g.common_room_open_time, g.common_room_close_day, g.common_room_close_time, g.schedule_timezone, g.character_sheet, g.created_at, g.updated_at, gp.role as user_role, u.username as gm_username
FROM games g
JOIN game_participants gp ON g.id = gp.game_id
JOIN users u ON g.gm_user_id = u.id
WHERE gp.user_id = $1 AND gp.status = 'active'
ORDER BY g.updated_at DESC
`

type GetGamesByUserRow struct {
	ID                      int32              `json:"id"`
	Title                   string             `json:"title"`
	Description             pgtype.Text        `json:"description"`
	GmUserID                int32              `json:"gm_user_id"`
	State                   pgtype.Text        `json:"state"`
	Genre                   pgtype.Text        `json:"genre"`
	StartDate               pgtype.Timestamptz `json:"start_date"`
	EndDate                 pgtype.Timestamptz `json:"end_date"`
	RecruitmentDeadline     pgtype.Timestamptz `json:"recruitment_deadline"`
	MaxPlayers              pgtype.Int4        `json:"max_players"`
	IsPublic                pgtype.Bool        `json:"is_public"`
	IsAnonymous             bool               `json:"is_anonymous"`
	AutoAcceptAudience      bool               `json:"auto_accept_audience"`
	AllowGroupConversations bool               `json:"allow_group_conversations"`
	PortraitAvatars         bool               `json:"portrait_avatars"`
	BannerUrl               pgtype.Text        `json:"banner_url"`
	CommonRoomOpenDay       pgtype.Int2        `json:"common_room_open_day"`
	CommonRoomOpenTime      pgtype.Time        `json:"common_room_open_time"`
	CommonRoomCloseDay      pgtype.Int2        `json:"common_room_close_day"`
	CommonRoomCloseTime     pgtype.Time        `json:"common_room_close_time"`
	ScheduleTimezone        pgtype.Text        `json:"schedule_timezone"`
	CharacterSheet          []byte             `json:"character_sheet"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UserRole                string             `json:"user_role"`
	GmUsername              string             `json:"gm_username"`
}

func (q *Queries) GetGamesByUser(ctx context.Context, userID int32) ([]GetGamesByUserRow, error) {
	rows, err := q.db.Query(ctx, getGamesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGamesByUserRow
	for rows.Next() {
		var i GetGamesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GmUserID,
			&i.State,
			&i.Genre,
			&i.StartDate,
			&i.EndDate,
			&i.RecruitmentDeadline,
			&i.MaxPlayers,
			&i.IsPublic,
			&i.IsAnonymous,
			&i.AutoAcceptAudience,
			&i.AllowGroupConversations,
			&i.PortraitAvatars,
			&i.BannerUrl,
			&i.CommonRoomOpenDay,
			&i.CommonRoomOpenTime,
			&i.CommonRoomCloseDay,
			&i.CommonRoomCloseTime,
			&i.ScheduleTimezone,
			&i.CharacterSheet,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserRole,
			&i.GmUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesNeedingStateUpdate = `-- name: GetGamesNeedingStateUpdate :many
SELECT id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, is_anonymous, auto_accept_audience, allow_group_conversations, portrait_avatars, banner_url, common_room_open_day, common_room_open_time, common_room_close_day, common_room_close_time, schedule_timezone, character_sheet, created_at, updated_at FROM games
WHERE (state = 'recruitment' AND recruitment_deadline IS NOT NULL AND recruitment_deadline < NOW())
   OR (state = 'in_progress' AND end_date IS NOT NULL AND end_date < NOW())
`

func (q *Queries) GetGamesNeedingStateUpdate(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, getGamesNeedingStateUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GmUserID,
			&i.State,
			&i.Genre,
			&i.StartDate,
			&i.EndDate,
			&i.RecruitmentDeadline,
			&i.MaxPlayers,
			&i.IsPublic,
			&i.IsAnonymous,
			&i.AutoAcceptAudience,
			&i.AllowGroupConversations,
			&i.PortraitAvatars,
			&i.BannerUrl,
			&i.CommonRoomOpenDay,
			&i.CommonRoomOpenTime,
			&i.CommonRoomCloseDay,
			&i.CommonRoomCloseTime,
			&i.ScheduleTimezone,
			&i.CharacterSheet,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipantByGameAndUser = `-- name: GetParticipantByGameAndUser :one
SELECT gp.id, gp.game_id, gp.user_id, gp.role, gp.status, gp.joined_at, gp.removed_at, gp.removed_by_user_id, gp.is_former_player, u.username, u.email
FROM game_participants gp
JOIN users u ON gp.user_id = u.id
WHERE gp.game_id = $1 AND gp.user_id = $2 AND gp.status = 'active'
`

type GetParticipantByGameAndUserParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

type GetParticipantByGameAndUserRow struct {
	ID              int32              `json:"id"`
	GameID          int32              `json:"game_id"`
	UserID          int32              `json:"user_id"`
	Role            string             `json:"role"`
	Status          pgtype.Text        `json:"status"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
	RemovedAt       pgtype.Timestamptz `json:"removed_at"`
	RemovedByUserID pgtype.Int4        `json:"removed_by_user_id"`
	IsFormerPlayer  bool               `json:"is_former_player"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
}

func (q *Queries) GetParticipantByGameAndUser(ctx context.Context, arg GetParticipantByGameAndUserParams) (GetParticipantByGameAndUserRow, error) {
	row := q.db.QueryRow(ctx, getParticipantByGameAndUser, arg.GameID, arg.UserID)
	var i GetParticipantByGameAndUserRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.IsFormerPlayer,
		&i.Username,
		&i.Email,
	)
	return i, err
}

const getParticipantRole = `-- name: GetParticipantRole :one
SELECT role FROM game_participants
WHERE game_id = $1 AND user_id = $2 AND status = 'active'
`

type GetParticipantRoleParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetParticipantRole(ctx context.Context, arg GetParticipantRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getParticipantRole, arg.GameID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getRecruitingGames = `-- name: GetRecruitingGames :many
SELECT games.id, games.title, games.description, games.gm_user_id, games.state, games.genre, games.start_date, games.end_date, games.recruitment_deadline, games.max_players, games.is_public, games.is_anonymous, games.auto_accept_audience, games.allow_group_conversations, games.portrait_avatars, games.banner_url, games.common_room_open_day, games.common_room_open_time, games.common_room_close_day, games.common_room_close_time, games.schedule_timezone, games.character_sheet, games.created_at, games.updated_at, COALESCE(users.username, 'Unknown') as gm_username,
       COALESCE(participant_count.count, 0) as current_players
FROM games
LEFT JOIN users ON games.gm_user_id = users.id
LEFT JOIN (
    SELECT game_id, COUNT(*) as count
    FROM game_participants
    WHERE role = 'player' AND status = 'active'
    GROUP BY game_id
) participant_count ON games.id = participant_count.game_id
WHERE games.is_public = true
AND games.state = 'recruitment'
AND (games.recruitment_deadline IS NULL OR games.recruitment_deadline > NOW())
ORDER BY games.created_at DESC
`

type GetRecruitingGamesRow struct {
	ID                      int32              `json:"id"`
	Title                   string             `json:"title"`
	Description             pgtype.Text        `json:"description"`
	GmUserID                int32              `json:"gm_user_id"`
	State                   pgtype.Text        `json:"state"`
	Genre                   pgtype.Text        `json:"genre"`
	StartDate               pgtype.Timestamptz `json:"start_date"`
	EndDate                 pgtype.Timestamptz `json:"end_date"`
	RecruitmentDeadline     pgtype.Timestamptz `json:"recruitment_deadline"`
	MaxPlayers              pgtype.Int4        `json:"max_players"`
	IsPublic                pgtype.Bool        `json:"is_public"`
	IsAnonymous             bool               `json:"is_anonymous"`
	AutoAcceptAudience      bool               `json:"auto_accept_audience"`
	AllowGroupConversations bool               `json:"allow_group_conversations"`
	PortraitAvatars         bool               `json:"portrait_avatars"`
	BannerUrl               pgtype.Text        `json:"banner_url"`
	CommonRoomOpenDay       pgtype.Int2        `json:"common_room_open_day"`
	CommonRoomOpenTime      pgtype.Time        `json:"common_room_open_time"`
	CommonRoomCloseDay      pgtype.Int2        `json:"common_room_close_day"`
	CommonRoomCloseTime     pgtype.Time        `json:"common_room_close_time"`
	ScheduleTimezone        pgtype.Text        `json:"schedule_timezone"`
	CharacterSheet          []byte             `json:"character_sheet"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	GmUsername              string             `json:"gm_username"`
	CurrentPlayers          int64              `json:"current_players"`
}

func (q *Queries) GetRecruitingGames(ctx context.Context) ([]GetRecruitingGamesRow, error) {
	rows, err := q.db.Query(ctx, getRecruitingGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecruitingGamesRow
	for rows.Next() {
		var i GetRecruitingGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GmUserID,
			&i.State,
			&i.Genre,
			&i.StartDate,
			&i.EndDate,
			&i.RecruitmentDeadline,
			&i.MaxPlayers,
			&i.IsPublic,
			&i.IsAnonymous,
			&i.AutoAcceptAudience,
			&i.AllowGroupConversations,
			&i.PortraitAvatars,
			&i.BannerUrl,
			&i.CommonRoomOpenDay,
			&i.CommonRoomOpenTime,
			&i.CommonRoomCloseDay,
			&i.CommonRoomCloseTime,
			&i.ScheduleTimezone,
			&i.CharacterSheet,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GmUsername,
			&i.CurrentPlayers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserInGame = `-- name: IsUserInGame :one
SELECT EXISTS(
    SELECT 1 FROM game_participants
    WHERE game_id = $1 AND user_id = $2 AND status = 'active'
)
`

type IsUserInGameParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) IsUserInGame(ctx context.Context, arg IsUserInGameParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInGame, arg.GameID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAudienceMembers = `-- name: ListAudienceMembers :many
SELECT gp.id, gp.game_id, gp.user_id, gp.role, gp.status, gp.joined_at, gp.removed_at, gp.removed_by_user_id, gp.is_former_player, u.username, u.email
FROM game_participants gp
JOIN users u ON gp.user_id = u.id
WHERE gp.game_id = $1 AND gp.role = 'audience' AND gp.status = 'active'
ORDER BY gp.joined_at
`

type ListAudienceMembersRow struct {
	ID              int32              `json:"id"`
	GameID          int32              `json:"game_id"`
	UserID          int32              `json:"user_id"`
	Role            string             `json:"role"`
	Status          pgtype.Text        `json:"status"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
	RemovedAt       pgtype.Timestamptz `json:"removed_at"`
	RemovedByUserID pgtype.Int4        `json:"removed_by_user_id"`
	IsFormerPlayer  bool               `json:"is_former_player"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
}

func (q *Queries) ListAudienceMembers(ctx context.Context, gameID int32) ([]ListAudienceMembersRow, error) {
	rows, err := q.db.Query(ctx, listAudienceMembers, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAudienceMembersRow
	for rows.Next() {
		var i ListAudienceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.RemovedAt,
			&i.RemovedByUserID,
			&i.IsFormerPlayer,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGameParticipant = `-- name: RemoveGameParticipant :exec
DELETE FROM game_participants
WHERE game_id = $1 AND user_id = $2
`

type RemoveGameParticipantParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) RemoveGameParticipant(ctx context.Context, arg RemoveGameParticipantParams) error {
	_, err := q.db.Exec(ctx, removeGameParticipant, arg.GameID, arg.UserID)
	return err
}

const removeParticipant = `-- name: RemoveParticipant :exec

UPDATE game_participants
SET removed_at = NOW(),
    removed_by_user_id = $3,
    status = 'removed'
WHERE game_id = $1 AND user_id = $2 AND removed_at IS NULL
`

type RemoveParticipantParams struct {
	GameID          int32       `json:"game_id"`
	UserID          int32       `json:"user_id"`
	RemovedByUserID pgtype.Int4 `json:"removed_by_user_id"`
}

// Player Management Queries
func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.Exec(ctx, removeParticipant, arg.GameID, arg.UserID, arg.RemovedByUserID)
	return err
}

const restoreParticipant = `-- name: RestoreParticipant :one
UPDATE game_participants
SET removed_at = NULL,
    removed_by_user_id = NULL,
    status = 'active'
WHERE game_id = $1 AND user_id = $2 AND removed_at IS NOT NULL
RETURNING id, game_id, user_id, role, status, joined_at, removed_at, removed_by_user_id, is_former_player
`

type RestoreParticipantParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) RestoreParticipant(ctx context.Context, arg RestoreParticipantParams) (GameParticipant, error) {
	row := q.db.QueryRow(ctx, restoreParticipant, arg.GameID, arg.UserID)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.IsFormerPlayer,
	)
	return i, err
}

const transitionParticipantToAudience = `-- name: TransitionParticipantToAudience :one
UPDATE game_participants
SET role = 'audience', is_former_player = TRUE
WHERE game_id = $1 AND user_id = $2 AND status = 'active'
RETURNING id, game_id, user_id, role, status, joined_at, removed_at, removed_by_user_id, is_former_player
`

type TransitionParticipantToAudienceParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) TransitionParticipantToAudience(ctx context.Context, arg TransitionParticipantToAudienceParams) (GameParticipant, error) {
	row := q.db.QueryRow(ctx, transitionParticipantToAudience, arg.GameID, arg.UserID)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.IsFormerPlayer,
	)
	return i, err
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET title = $2, description = $3, genre = $4, start_date = $5,
    end_date = $6, recruitment_deadline = $7, max_players = $8,
    is_public = $9, is_anonymous = $10, auto_accept_audience = $11, allow_group_conversations = $12, portrait_avatars = $13,
    banner_url = COALESCE($14, banner_url),
    common_room_open_day = $15, common_room_open_time = $16,
    common_room_close_day = $17, common_room_close_time = $18,
    schedule_timezone = $19,
    -- COALESCE to the EXISTING value, not to '{}': a nil here means "the caller
    -- did not supply a config", and on an update that must preserve the GM's
    -- labels rather than silently wipe them. (CreateGame coalesces to '{}'
    -- instead, since there is no prior value to keep.)
    character_sheet = COALESCE($20::jsonb, games.character_sheet),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, is_anonymous, auto_accept_audience, allow_group_conversations, portrait_avatars, banner_url, common_room_open_day, common_room_open_time, common_room_close_day, common_room_close_time, schedule_timezone, character_sheet, created_at, updated_at
`

type UpdateGameParams struct {
	ID                      int32              `json:"id"`
	Title                   string             `json:"title"`
	Description             pgtype.Text        `json:"description"`
	Genre                   pgtype.Text        `json:"genre"`
	StartDate               pgtype.Timestamptz `json:"start_date"`
	EndDate                 pgtype.Timestamptz `json:"end_date"`
	RecruitmentDeadline     pgtype.Timestamptz `json:"recruitment_deadline"`
	MaxPlayers              pgtype.Int4        `json:"max_players"`
	IsPublic                pgtype.Bool        `json:"is_public"`
	IsAnonymous             bool               `json:"is_anonymous"`
	AutoAcceptAudience      bool               `json:"auto_accept_audience"`
	AllowGroupConversations bool               `json:"allow_group_conversations"`
	PortraitAvatars         bool               `json:"portrait_avatars"`
	BannerUrl               pgtype.Text        `json:"banner_url"`
	CommonRoomOpenDay       pgtype.Int2        `json:"common_room_open_day"`
	CommonRoomOpenTime      pgtype.Time        `json:"common_room_open_time"`
	CommonRoomCloseDay      pgtype.Int2        `json:"common_room_close_day"`
	CommonRoomCloseTime     pgtype.Time        `json:"common_room_close_time"`
	ScheduleTimezone        pgtype.Text        `json:"schedule_timezone"`
	CharacterSheet          []byte             `json:"character_sheet"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGame,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Genre,
		arg.StartDate,
		arg.EndDate,
		arg.RecruitmentDeadline,
		arg.MaxPlayers,
		arg.IsPublic,
		arg.IsAnonymous,
		arg.AutoAcceptAudience,
		arg.AllowGroupConversations,
		arg.PortraitAvatars,
		arg.BannerUrl,
		arg.CommonRoomOpenDay,
		arg.CommonRoomOpenTime,
		arg.CommonRoomCloseDay,
		arg.CommonRoomCloseTime,
		arg.ScheduleTimezone,
		arg.CharacterSheet,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GmUserID,
		&i.State,
		&i.Genre,
		&i.StartDate,
		&i.EndDate,
		&i.RecruitmentDeadline,
		&i.MaxPlayers,
		&i.IsPublic,
		&i.IsAnonymous,
		&i.AutoAcceptAudience,
		&i.AllowGroupConversations,
		&i.PortraitAvatars,
		&i.BannerUrl,
		&i.CommonRoomOpenDay,
		&i.CommonRoomOpenTime,
		&i.CommonRoomCloseDay,
		&i.CommonRoomCloseTime,
		&i.ScheduleTimezone,
		&i.CharacterSheet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGameAutoAcceptAudience = `-- name: UpdateGameAutoAcceptAudience :exec
UPDATE games
SET auto_accept_audience = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateGameAutoAcceptAudienceParams struct {
	ID                 int32 `json:"id"`
	AutoAcceptAudience bool  `json:"auto_accept_audience"`
}

func (q *Queries) UpdateGameAutoAcceptAudience(ctx context.Context, arg UpdateGameAutoAcceptAudienceParams) error {
	_, err := q.db.Exec(ctx, updateGameAutoAcceptAudience, arg.ID, arg.AutoAcceptAudience)
	return err
}

const updateGameBannerURL = `-- name: UpdateGameBannerURL :one
UPDATE games
SET banner_url = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, is_anonymous, auto_accept_audience, allow_group_conversations, portrait_avatars, banner_url, common_room_open_day, common_room_open_time, common_room_close_day, common_room_close_time, schedule_timezone, character_sheet, created_at, updated_at
`

type UpdateGameBannerURLParams struct {
	ID        int32       `json:"id"`
	BannerUrl pgtype.Text `json:"banner_url"`
}

func (q *Queries) UpdateGameBannerURL(ctx context.Context, arg UpdateGameBannerURLParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGameBannerURL, arg.ID, arg.BannerUrl)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GmUserID,
		&i.State,
		&i.Genre,
		&i.StartDate,
		&i.EndDate,
		&i.RecruitmentDeadline,
		&i.MaxPlayers,
		&i.IsPublic,
		&i.IsAnonymous,
		&i.AutoAcceptAudience,
		&i.AllowGroupConversations,
		&i.PortraitAvatars,
		&i.BannerUrl,
		&i.CommonRoomOpenDay,
		&i.CommonRoomOpenTime,
		&i.CommonRoomCloseDay,
		&i.CommonRoomCloseTime,
		&i.ScheduleTimezone,
		&i.CharacterSheet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGameState = `-- name: UpdateGameState :one
UPDATE games
SET state = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, is_anonymous, auto_accept_audience, allow_group_conversations, portrait_avatars, banner_url, common_room_open_day, common_room_open_time, common_room_close_day, common_room_close_time, schedule_timezone, character_sheet, created_at, updated_at
`

type UpdateGameStateParams struct {
	ID    int32       `json:"id"`
	State pgtype.Text `json:"state"`
}

func (q *Queries) UpdateGameState(ctx context.Context, arg UpdateGameStateParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGameState, arg.ID, arg.State)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GmUserID,
		&i.State,
		&i.Genre,
		&i.StartDate,
		&i.EndDate,
		&i.RecruitmentDeadline,
		&i.MaxPlayers,
		&i.IsPublic,
		&i.IsAnonymous,
		&i.AutoAcceptAudience,
		&i.AllowGroupConversations,
		&i.PortraitAvatars,
		&i.BannerUrl,
		&i.CommonRoomOpenDay,
		&i.CommonRoomOpenTime,
		&i.CommonRoomCloseDay,
		&i.CommonRoomCloseTime,
		&i.ScheduleTimezone,
		&i.CharacterSheet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParticipantRole = `-- name: UpdateParticipantRole :one

UPDATE game_participants
SET role = $3
WHERE game_id = $1 AND user_id = $2 AND status = 'active'
RETURNING id, game_id, user_id, role, status, joined_at, removed_at, removed_by_user_id, is_former_player
`

type UpdateParticipantRoleParams struct {
	GameID int32  `json:"game_id"`
	UserID int32  `json:"user_id"`
	Role   string `json:"role"`
}

// Co-GM Management Queries
func (q *Queries) UpdateParticipantRole(ctx context.Context, arg UpdateParticipantRoleParams) (GameParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantRole, arg.GameID, arg.UserID, arg.Role)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.IsFormerPlayer,
	)
	return i, err
}

const updateParticipantStatus = `-- name: UpdateParticipantStatus :one
UPDATE game_participants
SET status = $3
WHERE game_id = $1 AND user_id = $2
RETURNING id, game_id, user_id, role, status, joined_at, removed_at, removed_by_user_id, is_former_player
`

type UpdateParticipantStatusParams struct {
	GameID int32       `json:"game_id"`
	UserID int32       `json:"user_id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateParticipantStatus(ctx context.Context, arg UpdateParticipantStatusParams) (GameParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantStatus, arg.GameID, arg.UserID, arg.Status)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.RemovedAt,
		&i.RemovedByUserID,
		&i.IsFormerPlayer,
	)
	return i, err
}
