// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkApproveApplications = `-- name: BulkApproveApplications :exec
UPDATE game_applications
SET
    status = 'approved',
    reviewed_at = NOW(),
    reviewed_by_user_id = $2
WHERE game_id = $1 AND status = 'pending'
`

type BulkApproveApplicationsParams struct {
	GameID           int32       `json:"game_id"`
	ReviewedByUserID pgtype.Int4 `json:"reviewed_by_user_id"`
}

func (q *Queries) BulkApproveApplications(ctx context.Context, arg BulkApproveApplicationsParams) error {
	_, err := q.db.Exec(ctx, bulkApproveApplications, arg.GameID, arg.ReviewedByUserID)
	return err
}

const bulkRejectApplications = `-- name: BulkRejectApplications :exec
UPDATE game_applications
SET
    status = 'rejected',
    reviewed_at = NOW(),
    reviewed_by_user_id = $2
WHERE game_id = $1 AND status = 'pending'
`

type BulkRejectApplicationsParams struct {
	GameID           int32       `json:"game_id"`
	ReviewedByUserID pgtype.Int4 `json:"reviewed_by_user_id"`
}

// Reject all pending applications for a game
// This is called when GM closes recruitment
func (q *Queries) BulkRejectApplications(ctx context.Context, arg BulkRejectApplicationsParams) error {
	_, err := q.db.Exec(ctx, bulkRejectApplications, arg.GameID, arg.ReviewedByUserID)
	return err
}

const canUserApplyToGame = `-- name: CanUserApplyToGame :one
SELECT CASE
    WHEN EXISTS(SELECT 1 FROM games g WHERE g.id = $1 AND g.gm_user_id = $2) THEN 'is_game_master'
    WHEN EXISTS(SELECT 1 FROM game_participants gp WHERE gp.game_id = $1 AND gp.user_id = $2 AND gp.status = 'active') THEN 'already_participant'
    WHEN EXISTS(SELECT 1 FROM game_applications ga WHERE ga.game_id = $1 AND ga.user_id = $2 AND ga.status = 'pending') THEN 'application_pending'
    WHEN EXISTS(SELECT 1 FROM game_applications ga2 WHERE ga2.game_id = $1 AND ga2.user_id = $2 AND ga2.status = 'rejected')
         AND NOT EXISTS(SELECT 1 FROM game_participants gp2 WHERE gp2.game_id = $1 AND gp2.user_id = $2) THEN 'application_rejected'
    WHEN EXISTS(SELECT 1 FROM games g2 WHERE g2.id = $1 AND g2.state != 'recruitment') THEN 'not_recruiting'
    ELSE 'can_apply'
END AS status
`

type CanUserApplyToGameParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) CanUserApplyToGame(ctx context.Context, arg CanUserApplyToGameParams) (string, error) {
	row := q.db.QueryRow(ctx, canUserApplyToGame, arg.GameID, arg.UserID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const countPendingApplicationsForGame = `-- name: CountPendingApplicationsForGame :one
SELECT COUNT(*) FROM game_applications
WHERE game_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingApplicationsForGame(ctx context.Context, gameID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingApplicationsForGame, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGameApplication = `-- name: CreateGameApplication :one
INSERT INTO game_applications (
    game_id, user_id, role, message
) VALUES (
    $1, $2, $3, $4
) RETURNING id, game_id, user_id, role, message, status, reviewed_by_user_id, reviewed_at, applied_at, is_published
`

type CreateGameApplicationParams struct {
	GameID  int32       `json:"game_id"`
	UserID  int32       `json:"user_id"`
	Role    string      `json:"role"`
	Message pgtype.Text `json:"message"`
}

type CreateGameApplicationRow struct {
	ID               int32              `json:"id"`
	GameID           int32              `json:"game_id"`
	UserID           int32              `json:"user_id"`
	Role             string             `json:"role"`
	Message          pgtype.Text        `json:"message"`
	Status           pgtype.Text        `json:"status"`
	ReviewedByUserID pgtype.Int4        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
	IsPublished      bool               `json:"is_published"`
}

func (q *Queries) CreateGameApplication(ctx context.Context, arg CreateGameApplicationParams) (CreateGameApplicationRow, error) {
	row := q.db.QueryRow(ctx, createGameApplication,
		arg.GameID,
		arg.UserID,
		arg.Role,
		arg.Message,
	)
	var i CreateGameApplicationRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.IsPublished,
	)
	return i, err
}

const deleteGameApplication = `-- name: DeleteGameApplication :exec
DELETE FROM game_applications WHERE id = $1 AND user_id = $2
`

type DeleteGameApplicationParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteGameApplication(ctx context.Context, arg DeleteGameApplicationParams) error {
	_, err := q.db.Exec(ctx, deleteGameApplication, arg.ID, arg.UserID)
	return err
}

const deleteRejectedApplicationForUser = `-- name: DeleteRejectedApplicationForUser :exec
DELETE FROM game_applications WHERE game_id = $1 AND user_id = $2 AND status = 'rejected'
`

type DeleteRejectedApplicationForUserParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteRejectedApplicationForUser(ctx context.Context, arg DeleteRejectedApplicationForUserParams) error {
	_, err := q.db.Exec(ctx, deleteRejectedApplicationForUser, arg.GameID, arg.UserID)
	return err
}

const deleteRejectedApplications = `-- name: DeleteRejectedApplications :exec
DELETE FROM game_applications
WHERE game_id = $1 AND status = 'rejected'
`

// Delete all rejected applications for a game
// This is called when transitioning out of recruitment to clean up rejected applications
func (q *Queries) DeleteRejectedApplications(ctx context.Context, gameID int32) error {
	_, err := q.db.Exec(ctx, deleteRejectedApplications, gameID)
	return err
}

const deleteStaleApprovedApplicationForUser = `-- name: DeleteStaleApprovedApplicationForUser :exec
DELETE FROM game_applications ga
WHERE ga.game_id = $1 AND ga.user_id = $2 AND ga.status = 'approved' AND ga.role = 'audience'
  AND NOT EXISTS (
    SELECT 1 FROM game_participants gp
    WHERE gp.game_id = ga.game_id AND gp.user_id = ga.user_id AND gp.status = 'active'
  )
`

type DeleteStaleApprovedApplicationForUserParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

// Deletes a leftover 'approved' audience application for a user who is no longer an
// active participant in the game (e.g. they left or were removed after approval).
// Scoped to role = 'audience' because audience approval creates a game_participants row
// immediately (see ApproveGameApplication), unlike player applications, whose approved
// application row is intentionally kept until recruitment closes. Without this, the
// UNIQUE(game_id, user_id) constraint permanently blocks an audience member from
// re-applying after leaving.
func (q *Queries) DeleteStaleApprovedApplicationForUser(ctx context.Context, arg DeleteStaleApprovedApplicationForUserParams) error {
	_, err := q.db.Exec(ctx, deleteStaleApprovedApplicationForUser, arg.GameID, arg.UserID)
	return err
}

const getApprovedApplicationsForGame = `-- name: GetApprovedApplicationsForGame :many
SELECT
    ga.id, ga.game_id, ga.user_id, ga.role, ga.message, ga.status, ga.reviewed_by_user_id, ga.reviewed_at, ga.applied_at, ga.is_published,
    u.username,
    u.avatar_url
FROM game_applications ga
JOIN users u ON ga.user_id = u.id
WHERE ga.game_id = $1 AND ga.status = 'approved'
ORDER BY ga.reviewed_at ASC
`

type GetApprovedApplicationsForGameRow struct {
	ID               int32              `json:"id"`
	GameID           int32              `json:"game_id"`
	UserID           int32              `json:"user_id"`
	Role             string             `json:"role"`
	Message          pgtype.Text        `json:"message"`
	Status           pgtype.Text        `json:"status"`
	ReviewedByUserID pgtype.Int4        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
	IsPublished      bool               `json:"is_published"`
	Username         string             `json:"username"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetApprovedApplicationsForGame(ctx context.Context, gameID int32) ([]GetApprovedApplicationsForGameRow, error) {
	rows, err := q.db.Query(ctx, getApprovedApplicationsForGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApprovedApplicationsForGameRow
	for rows.Next() {
		var i GetApprovedApplicationsForGameRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Message,
			&i.Status,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.AppliedAt,
			&i.IsPublished,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameApplication = `-- name: GetGameApplication :one
SELECT id, game_id, user_id, role, message, status, reviewed_by_user_id, reviewed_at, applied_at, is_published
FROM game_applications WHERE id = $1
`

type GetGameApplicationRow struct {
	ID               int32              `json:"id"`
	GameID           int32              `json:"game_id"`
	UserID           int32              `json:"user_id"`
	Role             string             `json:"role"`
	Message          pgtype.Text        `json:"message"`
	Status           pgtype.Text        `json:"status"`
	ReviewedByUserID pgtype.Int4        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
	IsPublished      bool               `json:"is_published"`
}

func (q *Queries) GetGameApplication(ctx context.Context, id int32) (GetGameApplicationRow, error) {
	row := q.db.QueryRow(ctx, getGameApplication, id)
	var i GetGameApplicationRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.IsPublished,
	)
	return i, err
}

const getGameApplicationByUserAndGame = `-- name: GetGameApplicationByUserAndGame :one
SELECT id, game_id, user_id, role, message, status, reviewed_by_user_id, reviewed_at, applied_at, is_published
FROM game_applications
WHERE game_id = $1 AND user_id = $2
`

type GetGameApplicationByUserAndGameParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

type GetGameApplicationByUserAndGameRow struct {
	ID               int32              `json:"id"`
	GameID           int32              `json:"game_id"`
	UserID           int32              `json:"user_id"`
	Role             string             `json:"role"`
	Message          pgtype.Text        `json:"message"`
	Status           pgtype.Text        `json:"status"`
	ReviewedByUserID pgtype.Int4        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
	IsPublished      bool               `json:"is_published"`
}

func (q *Queries) GetGameApplicationByUserAndGame(ctx context.Context, arg GetGameApplicationByUserAndGameParams) (GetGameApplicationByUserAndGameRow, error) {
	row := q.db.QueryRow(ctx, getGameApplicationByUserAndGame, arg.GameID, arg.UserID)
	var i GetGameApplicationByUserAndGameRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.IsPublished,
	)
	return i, err
}

const getGameApplications = `-- name: GetGameApplications :many
SELECT
    ga.id, ga.game_id, ga.user_id, ga.role, ga.message, ga.status, ga.reviewed_by_user_id, ga.reviewed_at, ga.applied_at, ga.is_published,
    u.username,
    u.avatar_url
FROM game_applications ga
JOIN users u ON ga.user_id = u.id
WHERE ga.game_id = $1
ORDER BY ga.applied_at ASC
`

type GetGameApplicationsRow struct {
	ID               int32              `json:"id"`
	GameID           int32              `json:"game_id"`
	UserID           int32              `json:"user_id"`
	Role             string             `json:"role"`
	Message          pgtype.Text        `json:"message"`
	Status           pgtype.Text        `json:"status"`
	ReviewedByUserID pgtype.Int4        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
	IsPublished      bool               `json:"is_published"`
	Username         string             `json:"username"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetGameApplications(ctx context.Context, gameID int32) ([]GetGameApplicationsRow, error) {
	rows, err := q.db.Query(ctx, getGameApplications, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameApplicationsRow
	for rows.Next() {
		var i GetGameApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Message,
			&i.Status,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.AppliedAt,
			&i.IsPublished,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameApplicationsByStatus = `-- name: GetGameApplicationsByStatus :many
SELECT
    ga.id, ga.game_id, ga.user_id, ga.role, ga.message, ga.status, ga.reviewed_by_user_id, ga.reviewed_at, ga.applied_at, ga.is_published,
    u.username,
    u.avatar_url
FROM game_applications ga
JOIN users u ON ga.user_id = u.id
WHERE ga.game_id = $1 AND ga.status = $2
ORDER BY ga.applied_at ASC
`

type GetGameApplicationsByStatusParams struct {
	GameID int32       `json:"game_id"`
	Status pgtype.Text `json:"status"`
}

type GetGameApplicationsByStatusRow struct {
	ID               int32              `json:"id"`
	GameID           int32              `json:"game_id"`
	UserID           int32              `json:"user_id"`
	Role             string             `json:"role"`
	Message          pgtype.Text        `json:"message"`
	Status           pgtype.Text        `json:"status"`
	ReviewedByUserID pgtype.Int4        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
	IsPublished      bool               `json:"is_published"`
	Username         string             `json:"username"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetGameApplicationsByStatus(ctx context.Context, arg GetGameApplicationsByStatusParams) ([]GetGameApplicationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getGameApplicationsByStatus, arg.GameID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameApplicationsByStatusRow
	for rows.Next() {
		var i GetGameApplicationsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Message,
			&i.Status,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.AppliedAt,
			&i.IsPublished,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicGameApplicants = `-- name: GetPublicGameApplicants :many
SELECT
    ga.id, ga.game_id, ga.user_id, ga.role, ga.applied_at,
    u.username,
    u.avatar_url
FROM game_applications ga
JOIN users u ON ga.user_id = u.id
WHERE ga.game_id = $1
ORDER BY ga.applied_at ASC
`

type GetPublicGameApplicantsRow struct {
	ID        int32              `json:"id"`
	GameID    int32              `json:"game_id"`
	UserID    int32              `json:"user_id"`
	Role      string             `json:"role"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
	Username  string             `json:"username"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
}

// Public endpoint: Get list of applicants for a game (no approval/rejection status)
// Available to anyone when game is in recruiting state
// Returns only username and role, NOT status or review information
func (q *Queries) GetPublicGameApplicants(ctx context.Context, gameID int32) ([]GetPublicGameApplicantsRow, error) {
	rows, err := q.db.Query(ctx, getPublicGameApplicants, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicGameApplicantsRow
	for rows.Next() {
		var i GetPublicGameApplicantsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.AppliedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGameApplications = `-- name: GetUserGameApplications :many
SELECT
    ga.id, ga.game_id, ga.user_id, ga.role, ga.message, ga.status, ga.reviewed_by_user_id, ga.reviewed_at, ga.applied_at, ga.is_published,
    g.title AS game_title,
    g.state AS game_state
FROM game_applications ga
JOIN games g ON ga.game_id = g.id
WHERE ga.user_id = $1
ORDER BY ga.applied_at DESC
`

type GetUserGameApplicationsRow struct {
	ID               int32              `json:"id"`
	GameID           int32              `json:"game_id"`
	UserID           int32              `json:"user_id"`
	Role             string             `json:"role"`
	Message          pgtype.Text        `json:"message"`
	Status           pgtype.Text        `json:"status"`
	ReviewedByUserID pgtype.Int4        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
	IsPublished      bool               `json:"is_published"`
	GameTitle        string             `json:"game_title"`
	GameState        pgtype.Text        `json:"game_state"`
}

func (q *Queries) GetUserGameApplications(ctx context.Context, userID int32) ([]GetUserGameApplicationsRow, error) {
	rows, err := q.db.Query(ctx, getUserGameApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserGameApplicationsRow
	for rows.Next() {
		var i GetUserGameApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Message,
			&i.Status,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.AppliedAt,
			&i.IsPublished,
			&i.GameTitle,
			&i.GameState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserAppliedToGame = `-- name: HasUserAppliedToGame :one
SELECT EXISTS(
    SELECT 1 FROM game_applications
    WHERE game_id = $1 AND user_id = $2
)
`

type HasUserAppliedToGameParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) HasUserAppliedToGame(ctx context.Context, arg HasUserAppliedToGameParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserAppliedToGame, arg.GameID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const publishApplicationStatuses = `-- name: PublishApplicationStatuses :exec
UPDATE game_applications
SET is_published = TRUE
WHERE game_id = $1
`

// Mark all application statuses as published for a game
// This is called when GM closes recruitment
func (q *Queries) PublishApplicationStatuses(ctx context.Context, gameID int32) error {
	_, err := q.db.Exec(ctx, publishApplicationStatuses, gameID)
	return err
}

const updateGameApplicationStatus = `-- name: UpdateGameApplicationStatus :one
UPDATE game_applications
SET
    status = $2,
    reviewed_at = NOW(),
    reviewed_by_user_id = $3
WHERE id = $1
RETURNING id, game_id, user_id, role, message, status, reviewed_by_user_id, reviewed_at, applied_at, is_published
`

type UpdateGameApplicationStatusParams struct {
	ID               int32       `json:"id"`
	Status           pgtype.Text `json:"status"`
	ReviewedByUserID pgtype.Int4 `json:"reviewed_by_user_id"`
}

type UpdateGameApplicationStatusRow struct {
	ID               int32              `json:"id"`
	GameID           int32              `json:"game_id"`
	UserID           int32              `json:"user_id"`
	Role             string             `json:"role"`
	Message          pgtype.Text        `json:"message"`
	Status           pgtype.Text        `json:"status"`
	ReviewedByUserID pgtype.Int4        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
	IsPublished      bool               `json:"is_published"`
}

func (q *Queries) UpdateGameApplicationStatus(ctx context.Context, arg UpdateGameApplicationStatusParams) (UpdateGameApplicationStatusRow, error) {
	row := q.db.QueryRow(ctx, updateGameApplicationStatus, arg.ID, arg.Status, arg.ReviewedByUserID)
	var i UpdateGameApplicationStatusRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.IsPublished,
	)
	return i, err
}
