// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReaction = `-- name: AddReaction :one

INSERT INTO message_reactions (message_id, user_id, reaction_type)
VALUES ($1, $2, $3)
ON CONFLICT (message_id, user_id, reaction_type) DO NOTHING
RETURNING id, message_id, user_id, reaction_type, created_at
`

type AddReactionParams struct {
	MessageID    int32  `json:"message_id"`
	UserID       int32  `json:"user_id"`
	ReactionType string `json:"reaction_type"`
}

// ============================================================================
// REACTIONS (Optional - for future use)
// ============================================================================
func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (MessageReaction, error) {
	row := q.db.QueryRow(ctx, addReaction, arg.MessageID, arg.UserID, arg.ReactionType)
	var i MessageReaction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.ReactionType,
		&i.CreatedAt,
	)
	return i, err
}

const checkCommentOwnership = `-- name: CheckCommentOwnership :one
SELECT author_id, deleted_at
FROM messages
WHERE id = $1 AND message_type = 'comment'
`

type CheckCommentOwnershipRow struct {
	AuthorID  int32            `json:"author_id"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

func (q *Queries) CheckCommentOwnership(ctx context.Context, id int32) (CheckCommentOwnershipRow, error) {
	row := q.db.QueryRow(ctx, checkCommentOwnership, id)
	var i CheckCommentOwnershipRow
	err := row.Scan(&i.AuthorID, &i.DeletedAt)
	return i, err
}

const checkPostOwnership = `-- name: CheckPostOwnership :one
SELECT author_id, deleted_at
FROM messages
WHERE id = $1 AND message_type = 'post'
`

type CheckPostOwnershipRow struct {
	AuthorID  int32            `json:"author_id"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

func (q *Queries) CheckPostOwnership(ctx context.Context, id int32) (CheckPostOwnershipRow, error) {
	row := q.db.QueryRow(ctx, checkPostOwnership, id)
	var i CheckPostOwnershipRow
	err := row.Scan(&i.AuthorID, &i.DeletedAt)
	return i, err
}

const countAllPrivateConversations = `-- name: CountAllPrivateConversations :one
WITH participants_agg AS (
  SELECT
    cp.conversation_id,
    array_agg(COALESCE(ch.name, u.username) ORDER BY cp.id) as participant_names
  FROM (
    SELECT DISTINCT ON (conversation_id, character_id)
      id, conversation_id, user_id, character_id
    FROM conversation_participants
    ORDER BY conversation_id, character_id, id
  ) cp
  JOIN users u ON cp.user_id = u.id
  LEFT JOIN characters ch ON cp.character_id = ch.id
  GROUP BY cp.conversation_id
)
SELECT COUNT(*)
FROM conversations c
LEFT JOIN participants_agg pa ON c.id = pa.conversation_id
WHERE c.game_id = $1
  AND (
    CASE
      WHEN $2::text[] IS NULL OR array_length($2::text[], 1) IS NULL THEN true
      ELSE pa.participant_names::text[] @> $2::text[]
    END
  )
`

type CountAllPrivateConversationsParams struct {
	GameID           int32    `json:"game_id"`
	ParticipantNames []string `json:"participant_names"`
}

// Count total private conversations in a game, with optional participant filter
// Uses the same filter logic as ListAllPrivateConversations
func (q *Queries) CountAllPrivateConversations(ctx context.Context, arg CountAllPrivateConversationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllPrivateConversations, arg.GameID, arg.ParticipantNames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDraftPostsByPhase = `-- name: CountDraftPostsByPhase :one
SELECT COUNT(*)
FROM messages
WHERE phase_id = $1
  AND message_type = 'post'
  AND is_draft = true
  AND is_deleted = false
`

// Count draft posts for a phase (used to enforce one-draft-per-phase constraint).
func (q *Queries) CountDraftPostsByPhase(ctx context.Context, phaseID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countDraftPostsByPhase, phaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesByCharacter = `-- name: CountMessagesByCharacter :one
SELECT COUNT(*)
FROM messages
WHERE character_id = $1
  AND is_deleted = false
`

// Count messages (posts and comments) by a specific character
// Used to check if character can be deleted
func (q *Queries) CountMessagesByCharacter(ctx context.Context, characterID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesByCharacter, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTopLevelComments = `-- name: CountTopLevelComments :one

SELECT COUNT(*) as total
FROM messages
WHERE parent_id = $1
  AND message_type = 'comment'
`

// NOTE: GetCommentThread with recursive CTE is not supported by sqlc
// Use GetPostComments recursively on the frontend to build the tree
// This is actually more efficient for large thread trees anyway
//
// UPDATE: GetPostCommentsWithThreads uses raw SQL in service layer
// sqlc does not support recursive CTEs, so we implement this query directly in Go
// See: backend/pkg/db/services/messages/comments.go
// Count total top-level comments for a post (for pagination)
// INCLUDES deleted comments to preserve thread structure
func (q *Queries) CountTopLevelComments(ctx context.Context, parentID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countTopLevelComments, parentID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO messages (
    game_id,
    phase_id,
    author_id,
    character_id,
    content,
    message_type,
    parent_id,
    visibility,
    mentioned_character_ids,
    character_avatar_url_at_post
) VALUES (
    $1, $2, $3, $4, $5, 'comment', $6, $7, $8,
    (SELECT avatar_url FROM characters WHERE id = $4)
)
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, mentioned_character_ids, is_edited, is_deleted, is_draft, created_at, deleted_at, deleted_by_user_id, edited_at, edit_count, character_avatar_url_at_post
`

type CreateCommentParams struct {
	GameID                int32             `json:"game_id"`
	PhaseID               pgtype.Int4       `json:"phase_id"`
	AuthorID              int32             `json:"author_id"`
	CharacterID           int32             `json:"character_id"`
	Content               string            `json:"content"`
	ParentID              pgtype.Int4       `json:"parent_id"`
	Visibility            MessageVisibility `json:"visibility"`
	MentionedCharacterIds []int32           `json:"mentioned_character_ids"`
}

// ============================================================================
// COMMENT MANAGEMENT (Threaded replies)
// ============================================================================
// Pins the avatar at comment-authoring time. See CreatePost.
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Message, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.GameID,
		arg.PhaseID,
		arg.AuthorID,
		arg.CharacterID,
		arg.Content,
		arg.ParentID,
		arg.Visibility,
		arg.MentionedCharacterIds,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.MentionedCharacterIds,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsDraft,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.EditedAt,
		&i.EditCount,
		&i.CharacterAvatarUrlAtPost,
	)
	return i, err
}

const createDraftPost = `-- name: CreateDraftPost :one

INSERT INTO messages (
    game_id,
    phase_id,
    author_id,
    character_id,
    content,
    message_type,
    visibility,
    mentioned_character_ids,
    is_draft,
    character_avatar_url_at_post
) VALUES (
    $1, $2, $3, $4, $5, 'post', $6, $7, true,
    (SELECT avatar_url FROM characters WHERE id = $4)
)
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, mentioned_character_ids, is_edited, is_deleted, is_draft, created_at, deleted_at, deleted_by_user_id, edited_at, edit_count, character_avatar_url_at_post
`

type CreateDraftPostParams struct {
	GameID                int32             `json:"game_id"`
	PhaseID               pgtype.Int4       `json:"phase_id"`
	AuthorID              int32             `json:"author_id"`
	CharacterID           int32             `json:"character_id"`
	Content               string            `json:"content"`
	Visibility            MessageVisibility `json:"visibility"`
	MentionedCharacterIds []int32           `json:"mentioned_character_ids"`
}

// ============================================================================
// DRAFT POST MANAGEMENT (GM-authored posts stored before phase activation)
// ============================================================================
// Pins the avatar at draft-authoring time, matching CreatePost. A draft
// published later keeps the avatar it was written with, not the one current at
// publication.
func (q *Queries) CreateDraftPost(ctx context.Context, arg CreateDraftPostParams) (Message, error) {
	row := q.db.QueryRow(ctx, createDraftPost,
		arg.GameID,
		arg.PhaseID,
		arg.AuthorID,
		arg.CharacterID,
		arg.Content,
		arg.Visibility,
		arg.MentionedCharacterIds,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.MentionedCharacterIds,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsDraft,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.EditedAt,
		&i.EditCount,
		&i.CharacterAvatarUrlAtPost,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one


INSERT INTO messages (
    game_id,
    phase_id,
    author_id,
    character_id,
    content,
    message_type,
    visibility,
    mentioned_character_ids,
    character_avatar_url_at_post
) VALUES (
    $1, $2, $3, $4, $5, 'post', $6, $7,
    (SELECT avatar_url FROM characters WHERE id = $4)
)
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, mentioned_character_ids, is_edited, is_deleted, is_draft, created_at, deleted_at, deleted_by_user_id, edited_at, edit_count, character_avatar_url_at_post
`

type CreatePostParams struct {
	GameID                int32             `json:"game_id"`
	PhaseID               pgtype.Int4       `json:"phase_id"`
	AuthorID              int32             `json:"author_id"`
	CharacterID           int32             `json:"character_id"`
	Content               string            `json:"content"`
	Visibility            MessageVisibility `json:"visibility"`
	MentionedCharacterIds []int32           `json:"mentioned_character_ids"`
}

// Messages Queries (Common Room posts and future private messages)
// ============================================================================
// POST MANAGEMENT (Top-level messages)
// ============================================================================
// character_avatar_url_at_post pins the character's avatar as of this insert so
// the post keeps rendering the avatar it was written with. Resolved inline to
// keep the capture atomic with the insert.
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Message, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.GameID,
		arg.PhaseID,
		arg.AuthorID,
		arg.CharacterID,
		arg.Content,
		arg.Visibility,
		arg.MentionedCharacterIds,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.MentionedCharacterIds,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsDraft,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.EditedAt,
		&i.EditCount,
		&i.CharacterAvatarUrlAtPost,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
UPDATE messages
SET deleted_at = NOW(),
    deleted_by_user_id = $2,
    is_deleted = true
WHERE id = $1
  AND deleted_at IS NULL
  AND message_type = 'comment'
`

type DeleteCommentParams struct {
	ID              int32       `json:"id"`
	DeletedByUserID pgtype.Int4 `json:"deleted_by_user_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.DeletedByUserID)
	return err
}

const deleteDraftPost = `-- name: DeleteDraftPost :exec
DELETE FROM messages
WHERE id = $1
  AND is_draft = true
`

// Hard delete a single draft post by ID.
func (q *Queries) DeleteDraftPost(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDraftPost, id)
	return err
}

const deleteDraftPostsForPhase = `-- name: DeleteDraftPostsForPhase :exec
DELETE FROM messages
WHERE phase_id = $1
  AND message_type = 'post'
  AND is_draft = true
`

// Hard delete draft posts when a phase is deleted.
func (q *Queries) DeleteDraftPostsForPhase(ctx context.Context, phaseID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteDraftPostsForPhase, phaseID)
	return err
}

const deleteManualCommentReadsForGame = `-- name: DeleteManualCommentReadsForGame :exec
DELETE FROM user_comment_reads
WHERE game_id = $1
`

// Delete all manual read records for a game (called when game is completed/archived)
func (q *Queries) DeleteManualCommentReadsForGame(ctx context.Context, gameID int32) error {
	_, err := q.db.Exec(ctx, deleteManualCommentReadsForGame, gameID)
	return err
}

const deletePost = `-- name: DeletePost :one
UPDATE messages
SET is_deleted = true
WHERE id = $1
  AND message_type = 'post'
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, mentioned_character_ids, is_edited, is_deleted, is_draft, created_at, deleted_at, deleted_by_user_id, edited_at, edit_count, character_avatar_url_at_post
`

func (q *Queries) DeletePost(ctx context.Context, id int32) (Message, error) {
	row := q.db.QueryRow(ctx, deletePost, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.MentionedCharacterIds,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsDraft,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.EditedAt,
		&i.EditCount,
		&i.CharacterAvatarUrlAtPost,
	)
	return i, err
}

const deleteReadMarkersForGame = `-- name: DeleteReadMarkersForGame :exec
DELETE FROM user_common_room_reads
WHERE game_id = $1
`

// Delete all read markers for a game (e.g., when game is deleted or completed)
func (q *Queries) DeleteReadMarkersForGame(ctx context.Context, gameID int32) error {
	_, err := q.db.Exec(ctx, deleteReadMarkersForGame, gameID)
	return err
}

const deleteReadMarkersForPost = `-- name: DeleteReadMarkersForPost :exec
DELETE FROM user_common_room_reads
WHERE post_id = $1
`

// Delete all read markers for a post (e.g., when post is deleted)
func (q *Queries) DeleteReadMarkersForPost(ctx context.Context, postID int32) error {
	_, err := q.db.Exec(ctx, deleteReadMarkersForPost, postID)
	return err
}

const deleteReadMarkersForUser = `-- name: DeleteReadMarkersForUser :exec
DELETE FROM user_common_room_reads
WHERE user_id = $1
`

// Delete all read markers for a user (e.g., when user account is deleted)
func (q *Queries) DeleteReadMarkersForUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteReadMarkersForUser, userID)
	return err
}

const getAllDescendantComments = `-- name: GetAllDescendantComments :many
WITH RECURSIVE comment_tree AS (
  SELECT messages.id as comment_id
  FROM messages
  WHERE messages.parent_id = $1

  UNION ALL

  SELECT m.id as comment_id
  FROM messages m
  INNER JOIN comment_tree ct ON m.parent_id = ct.comment_id
)
SELECT comment_id as id FROM comment_tree
`

// Get all descendant comments recursively for counting
// Includes deleted comments to preserve thread structure counts
func (q *Queries) GetAllDescendantComments(ctx context.Context, parentID pgtype.Int4) ([]int32, error) {
	rows, err := q.db.Query(ctx, getAllDescendantComments, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAudienceConversationMessages = `-- name: GetAudienceConversationMessages :many
SELECT pm.id, pm.conversation_id, pm.sender_user_id, pm.sender_character_id, pm.content, pm.created_at, pm.updated_at, pm.deleted_at, pm.is_deleted, pm.is_edited, pm.edited_at, pm.edit_count,
       u.username as sender_username,
       c.name as sender_character_name
FROM private_messages pm
JOIN users u ON pm.sender_user_id = u.id
LEFT JOIN characters c ON pm.sender_character_id = c.id
WHERE pm.conversation_id = $1
ORDER BY pm.created_at ASC
`

type GetAudienceConversationMessagesRow struct {
	ID                  int32              `json:"id"`
	ConversationID      int32              `json:"conversation_id"`
	SenderUserID        int32              `json:"sender_user_id"`
	SenderCharacterID   pgtype.Int4        `json:"sender_character_id"`
	Content             string             `json:"content"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	IsDeleted           pgtype.Bool        `json:"is_deleted"`
	IsEdited            bool               `json:"is_edited"`
	EditedAt            pgtype.Timestamptz `json:"edited_at"`
	EditCount           int32              `json:"edit_count"`
	SenderUsername      string             `json:"sender_username"`
	SenderCharacterName pgtype.Text        `json:"sender_character_name"`
}

// Get all messages in a specific conversation (for audience/GM)
func (q *Queries) GetAudienceConversationMessages(ctx context.Context, conversationID int32) ([]GetAudienceConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, getAudienceConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAudienceConversationMessagesRow
	for rows.Next() {
		var i GetAudienceConversationMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderUserID,
			&i.SenderCharacterID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsDeleted,
			&i.IsEdited,
			&i.EditedAt,
			&i.EditCount,
			&i.SenderUsername,
			&i.SenderCharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComment = `-- name: GetComment :one
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.mentioned_character_ids, m.is_edited, m.is_deleted, m.is_draft, m.created_at, m.deleted_at, m.deleted_by_user_id, m.edited_at, m.edit_count, m.character_avatar_url_at_post,
       u.username as author_username,
       c.name as character_name,
       COALESCE(m.character_avatar_url_at_post, c.avatar_url) as character_avatar_url,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id) as reply_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.id = $1
`

type GetCommentRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	PhaseID                  pgtype.Int4        `json:"phase_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	MessageType              MessageType        `json:"message_type"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	ThreadDepth              int32              `json:"thread_depth"`
	Visibility               MessageVisibility  `json:"visibility"`
	MentionedCharacterIds    []int32            `json:"mentioned_character_ids"`
	IsEdited                 bool               `json:"is_edited"`
	IsDeleted                bool               `json:"is_deleted"`
	IsDraft                  bool               `json:"is_draft"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	DeletedByUserID          pgtype.Int4        `json:"deleted_by_user_id"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	CharacterAvatarUrlAtPost pgtype.Text        `json:"character_avatar_url_at_post"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	ReplyCount               int64              `json:"reply_count"`
}

func (q *Queries) GetComment(ctx context.Context, id int32) (GetCommentRow, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i GetCommentRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.MentionedCharacterIds,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsDraft,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.EditedAt,
		&i.EditCount,
		&i.CharacterAvatarUrlAtPost,
		&i.AuthorUsername,
		&i.CharacterName,
		&i.CharacterAvatarUrl,
		&i.ReplyCount,
	)
	return i, err
}

const getConversationParticipantNames = `-- name: GetConversationParticipantNames :many
WITH participants_per_conv AS (
  SELECT
    cp.conversation_id,
    array_agg(COALESCE(ch.name, u.username) ORDER BY cp.id) AS names
  FROM conversation_participants cp
  JOIN users u ON cp.user_id = u.id
  LEFT JOIN characters ch ON cp.character_id = ch.id
  JOIN conversations c ON cp.conversation_id = c.id
  WHERE c.game_id = $1
  GROUP BY cp.conversation_id
),
matching_convs AS (
  -- Conversations that contain ALL of the selected names (or all if none selected)
  SELECT conversation_id
  FROM participants_per_conv
  WHERE
    CASE
      WHEN $2::text[] IS NULL
        OR array_length($2::text[], 1) IS NULL
      THEN true
      ELSE names::text[] @> $2::text[]
    END
)
SELECT DISTINCT unnest(ppc.names) AS participant_name
FROM participants_per_conv ppc
JOIN matching_convs mc ON ppc.conversation_id = mc.conversation_id
ORDER BY participant_name
`

type GetConversationParticipantNamesParams struct {
	GameID        int32    `json:"game_id"`
	SelectedNames []string `json:"selected_names"`
}

// Get all character/user names that appear in at least one conversation in the game,
// optionally narrowed to only those who share a conversation with ALL of the given names.
// When selected_names is empty, returns every participant across all conversations.
// When selected_names is non-empty, returns names that co-appear with all selected names.
func (q *Queries) GetConversationParticipantNames(ctx context.Context, arg GetConversationParticipantNamesParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getConversationParticipantNames, arg.GameID, arg.SelectedNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var participant_name interface{}
		if err := rows.Scan(&participant_name); err != nil {
			return nil, err
		}
		items = append(items, participant_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDraftPostForPhase = `-- name: GetDraftPostForPhase :one
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.mentioned_character_ids, m.is_edited, m.is_deleted, m.is_draft, m.created_at, m.deleted_at, m.deleted_by_user_id, m.edited_at, m.edit_count, m.character_avatar_url_at_post,
       u.username as author_username,
       c.name as character_name,
       COALESCE(m.character_avatar_url_at_post, c.avatar_url) as character_avatar_url,
       0::bigint as comment_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.phase_id = $1
  AND m.message_type = 'post'
  AND m.is_draft = true
  AND m.is_deleted = false
LIMIT 1
`

type GetDraftPostForPhaseRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	PhaseID                  pgtype.Int4        `json:"phase_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	MessageType              MessageType        `json:"message_type"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	ThreadDepth              int32              `json:"thread_depth"`
	Visibility               MessageVisibility  `json:"visibility"`
	MentionedCharacterIds    []int32            `json:"mentioned_character_ids"`
	IsEdited                 bool               `json:"is_edited"`
	IsDeleted                bool               `json:"is_deleted"`
	IsDraft                  bool               `json:"is_draft"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	DeletedByUserID          pgtype.Int4        `json:"deleted_by_user_id"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	CharacterAvatarUrlAtPost pgtype.Text        `json:"character_avatar_url_at_post"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	CommentCount             int64              `json:"comment_count"`
}

// Returns the single draft post for a phase (GM only). Returns no rows if none exists.
func (q *Queries) GetDraftPostForPhase(ctx context.Context, phaseID pgtype.Int4) (GetDraftPostForPhaseRow, error) {
	row := q.db.QueryRow(ctx, getDraftPostForPhase, phaseID)
	var i GetDraftPostForPhaseRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.MentionedCharacterIds,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsDraft,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.EditedAt,
		&i.EditCount,
		&i.CharacterAvatarUrlAtPost,
		&i.AuthorUsername,
		&i.CharacterName,
		&i.CharacterAvatarUrl,
		&i.CommentCount,
	)
	return i, err
}

const getGamePostCount = `-- name: GetGamePostCount :one

SELECT COUNT(*)
FROM messages
WHERE game_id = $1
  AND message_type = 'post'
  AND is_deleted = false
  AND is_draft = false
  AND (CASE WHEN $2 = 0 THEN TRUE ELSE phase_id = $2 END)
`

type GetGamePostCountParams struct {
	GameID  int32       `json:"game_id"`
	Column2 interface{} `json:"column_2"`
}

// ============================================================================
// STATISTICS & COUNTS
// ============================================================================
func (q *Queries) GetGamePostCount(ctx context.Context, arg GetGamePostCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getGamePostCount, arg.GameID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGamePosts = `-- name: GetGamePosts :many

SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.mentioned_character_ids, m.is_edited, m.is_deleted, m.is_draft, m.created_at, m.deleted_at, m.deleted_by_user_id, m.edited_at, m.edit_count, m.character_avatar_url_at_post,
       u.username as author_username,
       c.name as character_name,
       COALESCE(m.character_avatar_url_at_post, c.avatar_url) as character_avatar_url,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id) as comment_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.game_id = $1
  AND m.message_type = 'post'
  AND m.is_deleted = false
  AND m.is_draft = false
  AND (CASE WHEN $2 = 0 THEN TRUE ELSE m.phase_id = $2 END)
ORDER BY m.created_at DESC
LIMIT $3 OFFSET $4
`

type GetGamePostsParams struct {
	GameID  int32       `json:"game_id"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type GetGamePostsRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	PhaseID                  pgtype.Int4        `json:"phase_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	MessageType              MessageType        `json:"message_type"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	ThreadDepth              int32              `json:"thread_depth"`
	Visibility               MessageVisibility  `json:"visibility"`
	MentionedCharacterIds    []int32            `json:"mentioned_character_ids"`
	IsEdited                 bool               `json:"is_edited"`
	IsDeleted                bool               `json:"is_deleted"`
	IsDraft                  bool               `json:"is_draft"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	DeletedByUserID          pgtype.Int4        `json:"deleted_by_user_id"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	CharacterAvatarUrlAtPost pgtype.Text        `json:"character_avatar_url_at_post"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	CommentCount             int64              `json:"comment_count"`
}

// Return in parent-to-child order
func (q *Queries) GetGamePosts(ctx context.Context, arg GetGamePostsParams) ([]GetGamePostsRow, error) {
	rows, err := q.db.Query(ctx, getGamePosts,
		arg.GameID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGamePostsRow
	for rows.Next() {
		var i GetGamePostsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.MessageType,
			&i.ParentID,
			&i.ThreadDepth,
			&i.Visibility,
			&i.MentionedCharacterIds,
			&i.IsEdited,
			&i.IsDeleted,
			&i.IsDraft,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.EditedAt,
			&i.EditCount,
			&i.CharacterAvatarUrlAtPost,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.CharacterAvatarUrl,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManualReadCommentIDsForGame = `-- name: GetManualReadCommentIDsForGame :many
SELECT post_id, comment_id
FROM user_comment_reads
WHERE user_id = $1 AND game_id = $2
ORDER BY post_id, comment_id
`

type GetManualReadCommentIDsForGameParams struct {
	UserID int32 `json:"user_id"`
	GameID int32 `json:"game_id"`
}

type GetManualReadCommentIDsForGameRow struct {
	PostID    int32 `json:"post_id"`
	CommentID int32 `json:"comment_id"`
}

// Returns (post_id, comment_id) pairs for all manually read comments in a game
// Used to batch-load read state for the entire common room view
func (q *Queries) GetManualReadCommentIDsForGame(ctx context.Context, arg GetManualReadCommentIDsForGameParams) ([]GetManualReadCommentIDsForGameRow, error) {
	rows, err := q.db.Query(ctx, getManualReadCommentIDsForGame, arg.UserID, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetManualReadCommentIDsForGameRow
	for rows.Next() {
		var i GetManualReadCommentIDsForGameRow
		if err := rows.Scan(&i.PostID, &i.CommentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManualReadCommentIDsForPost = `-- name: GetManualReadCommentIDsForPost :many
SELECT comment_id
FROM user_comment_reads
WHERE user_id = $1 AND post_id = $2
`

type GetManualReadCommentIDsForPostParams struct {
	UserID int32 `json:"user_id"`
	PostID int32 `json:"post_id"`
}

// Returns comment IDs explicitly marked as read by the user under a specific post
func (q *Queries) GetManualReadCommentIDsForPost(ctx context.Context, arg GetManualReadCommentIDsForPostParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getManualReadCommentIDsForPost, arg.UserID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var comment_id int32
		if err := rows.Scan(&comment_id); err != nil {
			return nil, err
		}
		items = append(items, comment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.mentioned_character_ids, m.is_edited, m.is_deleted, m.is_draft, m.created_at, m.deleted_at, m.deleted_by_user_id, m.edited_at, m.edit_count, m.character_avatar_url_at_post,
       u.username as author_username,
       c.name as character_name,
       COALESCE(m.character_avatar_url_at_post, c.avatar_url) as character_avatar_url,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id) as reply_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.id = $1
  AND m.is_deleted = false
`

type GetMessageRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	PhaseID                  pgtype.Int4        `json:"phase_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	MessageType              MessageType        `json:"message_type"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	ThreadDepth              int32              `json:"thread_depth"`
	Visibility               MessageVisibility  `json:"visibility"`
	MentionedCharacterIds    []int32            `json:"mentioned_character_ids"`
	IsEdited                 bool               `json:"is_edited"`
	IsDeleted                bool               `json:"is_deleted"`
	IsDraft                  bool               `json:"is_draft"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	DeletedByUserID          pgtype.Int4        `json:"deleted_by_user_id"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	CharacterAvatarUrlAtPost pgtype.Text        `json:"character_avatar_url_at_post"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	ReplyCount               int64              `json:"reply_count"`
}

// Get any message by ID (post or comment) - used for deep linking
func (q *Queries) GetMessage(ctx context.Context, id int32) (GetMessageRow, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.MentionedCharacterIds,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsDraft,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.EditedAt,
		&i.EditCount,
		&i.CharacterAvatarUrlAtPost,
		&i.AuthorUsername,
		&i.CharacterName,
		&i.CharacterAvatarUrl,
		&i.ReplyCount,
	)
	return i, err
}

const getMessagePhaseID = `-- name: GetMessagePhaseID :one
SELECT phase_id
FROM messages
WHERE id = $1
`

// Get just the phase_id of a message, used when a new comment inherits its
// phase from the message it replies to. Deliberately does NOT filter on
// is_deleted: a reply to a soft-deleted parent still belongs to that phase.
func (q *Queries) GetMessagePhaseID(ctx context.Context, id int32) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getMessagePhaseID, id)
	var phase_id pgtype.Int4
	err := row.Scan(&phase_id)
	return phase_id, err
}

const getMessageReactions = `-- name: GetMessageReactions :many
SELECT mr.id, mr.message_id, mr.user_id, mr.reaction_type, mr.created_at, u.username
FROM message_reactions mr
JOIN users u ON mr.user_id = u.id
WHERE mr.message_id = $1
ORDER BY mr.created_at
`

type GetMessageReactionsRow struct {
	ID           int32            `json:"id"`
	MessageID    int32            `json:"message_id"`
	UserID       int32            `json:"user_id"`
	ReactionType string           `json:"reaction_type"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	Username     string           `json:"username"`
}

func (q *Queries) GetMessageReactions(ctx context.Context, messageID int32) ([]GetMessageReactionsRow, error) {
	rows, err := q.db.Query(ctx, getMessageReactions, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageReactionsRow
	for rows.Next() {
		var i GetMessageReactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.ReactionType,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageWithParentContext = `-- name: GetMessageWithParentContext :many
WITH RECURSIVE parent_chain AS (
    -- Base case: Start with the target message.
    SELECT
        m.id,
        m.game_id,
        m.phase_id,
        m.author_id,
        m.character_id,
        m.content,
        m.message_type,
        m.parent_id,
        m.thread_depth,
        m.visibility,
        m.mentioned_character_ids,
        m.is_edited,
        m.is_deleted,
        m.deleted_at,
        m.deleted_by_user_id,
        m.edited_at,
        m.edit_count,
        m.created_at,
        m.character_avatar_url_at_post
    FROM messages m
    WHERE m.id = $1

    UNION ALL

    -- Recursive case: Walk up the parent chain to root. Always continues to root (the
    -- walk itself is cheap: one indexed lookup per level) so root_post_id is resolvable
    -- even when the returned slice is trimmed by thread_depth below.
    SELECT
        m.id,
        m.game_id,
        m.phase_id,
        m.author_id,
        m.character_id,
        m.content,
        m.message_type,
        m.parent_id,
        m.thread_depth,
        m.visibility,
        m.mentioned_character_ids,
        m.is_edited,
        m.is_deleted,
        m.deleted_at,
        m.deleted_by_user_id,
        m.edited_at,
        m.edit_count,
        m.created_at,
        m.character_avatar_url_at_post
    FROM messages m
    INNER JOIN parent_chain pch ON m.id = pch.parent_id
),
root AS (
    -- The top-level post is the single row in the chain with no parent.
    SELECT id AS root_post_id
    FROM parent_chain
    WHERE parent_id IS NULL
)
SELECT
    pc.id,
    pc.game_id,
    pc.phase_id,
    pc.author_id,
    pc.character_id,
    pc.content,
    pc.message_type,
    pc.parent_id,
    pc.thread_depth,
    pc.visibility,
    pc.mentioned_character_ids,
    pc.is_edited,
    pc.is_deleted,
    pc.deleted_at,
    pc.deleted_by_user_id,
    pc.edited_at,
    pc.edit_count,
    pc.created_at,
    u.username as author_username,
    c.name as character_name,
    COALESCE(pc.character_avatar_url_at_post, c.avatar_url) as character_avatar_url,
    (SELECT COUNT(*) FROM messages WHERE parent_id = pc.id) as reply_count,
    root.root_post_id as root_post_id
FROM parent_chain pc
JOIN users u ON pc.author_id = u.id
LEFT JOIN characters c ON pc.character_id = c.id
LEFT JOIN root ON true
WHERE pc.thread_depth > (SELECT m.thread_depth FROM messages m WHERE m.id = $1) - ($2::integer + 1)
ORDER BY pc.thread_depth ASC
`

type GetMessageWithParentContextParams struct {
	MessageID  int32 `json:"message_id"`
	MaxParents int32 `json:"max_parents"`
}

type GetMessageWithParentContextRow struct {
	ID                    int32              `json:"id"`
	GameID                int32              `json:"game_id"`
	PhaseID               pgtype.Int4        `json:"phase_id"`
	AuthorID              int32              `json:"author_id"`
	CharacterID           int32              `json:"character_id"`
	Content               string             `json:"content"`
	MessageType           MessageType        `json:"message_type"`
	ParentID              pgtype.Int4        `json:"parent_id"`
	ThreadDepth           int32              `json:"thread_depth"`
	Visibility            MessageVisibility  `json:"visibility"`
	MentionedCharacterIds []int32            `json:"mentioned_character_ids"`
	IsEdited              bool               `json:"is_edited"`
	IsDeleted             bool               `json:"is_deleted"`
	DeletedAt             pgtype.Timestamp   `json:"deleted_at"`
	DeletedByUserID       pgtype.Int4        `json:"deleted_by_user_id"`
	EditedAt              pgtype.Timestamptz `json:"edited_at"`
	EditCount             int32              `json:"edit_count"`
	CreatedAt             pgtype.Timestamp   `json:"created_at"`
	AuthorUsername        string             `json:"author_username"`
	CharacterName         pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl    pgtype.Text        `json:"character_avatar_url"`
	ReplyCount            int64              `json:"reply_count"`
	RootPostID            pgtype.Int4        `json:"root_post_id"`
}

// Get a message plus a bounded slice of its parent chain for deep linking with context.
// Walks up from the target, returning the target + up to $2 nearest parents, in a single
// query (avoids a per-level request waterfall from the client).
// The trim happens in SQL via thread_depth (a real, monotonic column) so a very deep
// thread does not join/count rows we will discard. Every returned row also carries
// root_post_id (the true top-level post) so callers get the real root post ID for read
// tracking / replies without a second round trip, even when the slice is trimmed.
// Returns rows in parent-to-child order (nearest-included-parent → target).
// $1 = message_id (target comment)
// $2 = max_parents (how many ancestor levels above the target to include; 0 = target only)
// Keep the target and its $2 nearest ancestors. thread_depth is a real messages column,
// so sqlc can analyze this (unlike a CTE-only hop counter).
func (q *Queries) GetMessageWithParentContext(ctx context.Context, arg GetMessageWithParentContextParams) ([]GetMessageWithParentContextRow, error) {
	rows, err := q.db.Query(ctx, getMessageWithParentContext, arg.MessageID, arg.MaxParents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageWithParentContextRow
	for rows.Next() {
		var i GetMessageWithParentContextRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.MessageType,
			&i.ParentID,
			&i.ThreadDepth,
			&i.Visibility,
			&i.MentionedCharacterIds,
			&i.IsEdited,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.EditedAt,
			&i.EditCount,
			&i.CreatedAt,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.CharacterAvatarUrl,
			&i.ReplyCount,
			&i.RootPostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhasePosts = `-- name: GetPhasePosts :many
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.mentioned_character_ids, m.is_edited, m.is_deleted, m.is_draft, m.created_at, m.deleted_at, m.deleted_by_user_id, m.edited_at, m.edit_count, m.character_avatar_url_at_post,
       u.username as author_username,
       c.name as character_name,
       COALESCE(m.character_avatar_url_at_post, c.avatar_url) as character_avatar_url,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id) as comment_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.phase_id = $1
  AND m.message_type = 'post'
  AND m.is_deleted = false
  AND m.is_draft = false
ORDER BY m.created_at DESC
`

type GetPhasePostsRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	PhaseID                  pgtype.Int4        `json:"phase_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	MessageType              MessageType        `json:"message_type"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	ThreadDepth              int32              `json:"thread_depth"`
	Visibility               MessageVisibility  `json:"visibility"`
	MentionedCharacterIds    []int32            `json:"mentioned_character_ids"`
	IsEdited                 bool               `json:"is_edited"`
	IsDeleted                bool               `json:"is_deleted"`
	IsDraft                  bool               `json:"is_draft"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	DeletedByUserID          pgtype.Int4        `json:"deleted_by_user_id"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	CharacterAvatarUrlAtPost pgtype.Text        `json:"character_avatar_url_at_post"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	CommentCount             int64              `json:"comment_count"`
}

func (q *Queries) GetPhasePosts(ctx context.Context, phaseID pgtype.Int4) ([]GetPhasePostsRow, error) {
	rows, err := q.db.Query(ctx, getPhasePosts, phaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhasePostsRow
	for rows.Next() {
		var i GetPhasePostsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.MessageType,
			&i.ParentID,
			&i.ThreadDepth,
			&i.Visibility,
			&i.MentionedCharacterIds,
			&i.IsEdited,
			&i.IsDeleted,
			&i.IsDraft,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.EditedAt,
			&i.EditCount,
			&i.CharacterAvatarUrlAtPost,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.CharacterAvatarUrl,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPost = `-- name: GetPost :one
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.mentioned_character_ids, m.is_edited, m.is_deleted, m.is_draft, m.created_at, m.deleted_at, m.deleted_by_user_id, m.edited_at, m.edit_count, m.character_avatar_url_at_post,
       u.username as author_username,
       c.name as character_name,
       COALESCE(m.character_avatar_url_at_post, c.avatar_url) as character_avatar_url,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id) as comment_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.id = $1
`

type GetPostRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	PhaseID                  pgtype.Int4        `json:"phase_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	MessageType              MessageType        `json:"message_type"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	ThreadDepth              int32              `json:"thread_depth"`
	Visibility               MessageVisibility  `json:"visibility"`
	MentionedCharacterIds    []int32            `json:"mentioned_character_ids"`
	IsEdited                 bool               `json:"is_edited"`
	IsDeleted                bool               `json:"is_deleted"`
	IsDraft                  bool               `json:"is_draft"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	DeletedByUserID          pgtype.Int4        `json:"deleted_by_user_id"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	CharacterAvatarUrlAtPost pgtype.Text        `json:"character_avatar_url_at_post"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	CommentCount             int64              `json:"comment_count"`
}

func (q *Queries) GetPost(ctx context.Context, id int32) (GetPostRow, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i GetPostRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.MentionedCharacterIds,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsDraft,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.EditedAt,
		&i.EditCount,
		&i.CharacterAvatarUrlAtPost,
		&i.AuthorUsername,
		&i.CharacterName,
		&i.CharacterAvatarUrl,
		&i.CommentCount,
	)
	return i, err
}

const getPostCommentCount = `-- name: GetPostCommentCount :one
SELECT COUNT(*)
FROM messages
WHERE parent_id = $1
  AND is_deleted = false
`

func (q *Queries) GetPostCommentCount(ctx context.Context, parentID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, getPostCommentCount, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPostComments = `-- name: GetPostComments :many
WITH RECURSIVE descendants AS (
    -- Seed with the direct children we're about to return...
    SELECT id AS root_id, id AS descendant_id
    FROM messages
    WHERE parent_id = $1
      AND message_type = 'comment'

    UNION ALL

    -- ...then walk down the whole subtree under each of them.
    SELECT d.root_id, m.id
    FROM descendants d
    JOIN messages m ON m.parent_id = d.descendant_id
    WHERE m.message_type = 'comment'
),
descendant_counts AS (
    -- COUNT(*) - 1 drops the seed row (the comment counting itself).
    SELECT root_id, COUNT(*) - 1 AS reply_count
    FROM descendants
    GROUP BY root_id
)
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.mentioned_character_ids, m.is_edited, m.is_deleted, m.is_draft, m.created_at, m.deleted_at, m.deleted_by_user_id, m.edited_at, m.edit_count, m.character_avatar_url_at_post,
       u.username as author_username,
       c.name as character_name,
       COALESCE(m.character_avatar_url_at_post, c.avatar_url) as character_avatar_url,
       COALESCE(dc.reply_count, 0)::bigint as reply_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
LEFT JOIN descendant_counts dc ON dc.root_id = m.id
WHERE m.parent_id = $1
  AND m.message_type = 'comment'
ORDER BY m.created_at DESC
`

type GetPostCommentsRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	PhaseID                  pgtype.Int4        `json:"phase_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	MessageType              MessageType        `json:"message_type"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	ThreadDepth              int32              `json:"thread_depth"`
	Visibility               MessageVisibility  `json:"visibility"`
	MentionedCharacterIds    []int32            `json:"mentioned_character_ids"`
	IsEdited                 bool               `json:"is_edited"`
	IsDeleted                bool               `json:"is_deleted"`
	IsDraft                  bool               `json:"is_draft"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	DeletedByUserID          pgtype.Int4        `json:"deleted_by_user_id"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	CharacterAvatarUrlAtPost pgtype.Text        `json:"character_avatar_url_at_post"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	ReplyCount               int64              `json:"reply_count"`
}

// Get direct comments for a specific post
// For threaded display, call this recursively on the frontend
// Sorted newest first (DESC) for better UX - users see latest comments at top
// INCLUDES deleted comments to preserve thread structure - UI will show "[Comment deleted]" placeholder
//
// reply_count is the count of ALL descendants, not just direct children. It has
// to match GetPostCommentsWithThreads (see descendant_counts in
// backend/pkg/db/services/messages/comments.go), because the frontend renders
// this field as the "Continue this thread (N replies)" preview of how much
// thread is hidden behind the link. The main view is fed by the threaded query
// and the thread modal re-fetches each level through this query; when the two
// disagreed, a linear thread (one reply per comment) showed "(1 reply)" in the
// modal no matter how many comments were actually below.
func (q *Queries) GetPostComments(ctx context.Context, parentID pgtype.Int4) ([]GetPostCommentsRow, error) {
	rows, err := q.db.Query(ctx, getPostComments, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostCommentsRow
	for rows.Next() {
		var i GetPostCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.MessageType,
			&i.ParentID,
			&i.ThreadDepth,
			&i.Visibility,
			&i.MentionedCharacterIds,
			&i.IsEdited,
			&i.IsDeleted,
			&i.IsDraft,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.EditedAt,
			&i.EditCount,
			&i.CharacterAvatarUrlAtPost,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.CharacterAvatarUrl,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsWithUnreadCount = `-- name: GetPostsWithUnreadCount :many
SELECT
    m.id as post_id,
    m.created_at as post_created_at,
    COUNT(c.id) as total_comments,
    MAX(c.created_at) as latest_comment_at
FROM messages m
LEFT JOIN messages c ON c.parent_id = m.id AND c.is_deleted = false
WHERE m.game_id = $1
  AND m.message_type = 'post'
  AND m.is_deleted = false
  AND m.is_draft = false
GROUP BY m.id, m.created_at
ORDER BY m.created_at DESC
`

type GetPostsWithUnreadCountRow struct {
	PostID          int32            `json:"post_id"`
	PostCreatedAt   pgtype.Timestamp `json:"post_created_at"`
	TotalComments   int64            `json:"total_comments"`
	LatestCommentAt interface{}      `json:"latest_comment_at"`
}

// Get posts with their total comment count and last comment timestamp
// Frontend will compare these with read markers to determine unread status
func (q *Queries) GetPostsWithUnreadCount(ctx context.Context, gameID int32) ([]GetPostsWithUnreadCountRow, error) {
	rows, err := q.db.Query(ctx, getPostsWithUnreadCount, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsWithUnreadCountRow
	for rows.Next() {
		var i GetPostsWithUnreadCountRow
		if err := rows.Scan(
			&i.PostID,
			&i.PostCreatedAt,
			&i.TotalComments,
			&i.LatestCommentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReactionCounts = `-- name: GetReactionCounts :many
SELECT reaction_type, COUNT(*) as count
FROM message_reactions
WHERE message_id = $1
GROUP BY reaction_type
`

type GetReactionCountsRow struct {
	ReactionType string `json:"reaction_type"`
	Count        int64  `json:"count"`
}

func (q *Queries) GetReactionCounts(ctx context.Context, messageID int32) ([]GetReactionCountsRow, error) {
	rows, err := q.db.Query(ctx, getReactionCounts, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReactionCountsRow
	for rows.Next() {
		var i GetReactionCountsRow
		if err := rows.Scan(&i.ReactionType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCommentIDsForPosts = `-- name: GetUnreadCommentIDsForPosts :many
WITH RECURSIVE comment_threads AS (
    -- Base case: all top-level comments (direct children of posts)
    SELECT
        c.id as comment_id,
        c.parent_id as post_id,
        c.created_at,
        c.author_id
    FROM messages c
    WHERE c.parent_id IN (
        SELECT id FROM messages
        WHERE game_id = $2 AND message_type = 'post' AND is_deleted = false AND is_draft = false
    )
    AND c.is_deleted = false

    UNION ALL

    -- Recursive case: all nested replies
    SELECT
        m.id as comment_id,
        ct.post_id,
        m.created_at,
        m.author_id
    FROM messages m
    INNER JOIN comment_threads ct ON m.parent_id = ct.comment_id
    WHERE m.is_deleted = false
)
SELECT
    posts.id as post_id,
    COALESCE(
        array_agg(ct.comment_id ORDER BY ct.created_at DESC) FILTER (
            WHERE ucr.last_read_at IS NOT NULL
            AND ct.created_at > ucr.last_read_at
        ),
        '{}'::integer[]
    ) as unread_comment_ids
FROM messages posts
LEFT JOIN user_common_room_reads ucr ON ucr.post_id = posts.id AND ucr.user_id = $1
LEFT JOIN comment_threads ct ON ct.post_id = posts.id AND ct.author_id != $1
WHERE posts.game_id = $2
  AND posts.message_type = 'post'
  AND posts.is_deleted = false
GROUP BY posts.id
ORDER BY posts.created_at DESC
`

type GetUnreadCommentIDsForPostsParams struct {
	UserID int32 `json:"user_id"`
	GameID int32 `json:"game_id"`
}

type GetUnreadCommentIDsForPostsRow struct {
	PostID           int32       `json:"post_id"`
	UnreadCommentIds interface{} `json:"unread_comment_ids"`
}

// Get unread comment IDs for each post in a game for a specific user
// Returns post_id and array of comment IDs that are "new since last visit"
// A comment is new if:
//  1. It was created AFTER the user's last_read_at timestamp
//  2. It was NOT authored by the current user (users don't see their own comments as NEW)
//
// NOTE: If user has never visited (ucr.last_read_at IS NULL), returns empty array
// This prevents overwhelming users with "NEW" badges on their first visit
func (q *Queries) GetUnreadCommentIDsForPosts(ctx context.Context, arg GetUnreadCommentIDsForPostsParams) ([]GetUnreadCommentIDsForPostsRow, error) {
	rows, err := q.db.Query(ctx, getUnreadCommentIDsForPosts, arg.UserID, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreadCommentIDsForPostsRow
	for rows.Next() {
		var i GetUnreadCommentIDsForPostsRow
		if err := rows.Scan(&i.PostID, &i.UnreadCommentIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPostsInGame = `-- name: GetUserPostsInGame :many
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.mentioned_character_ids, m.is_edited, m.is_deleted, m.is_draft, m.created_at, m.deleted_at, m.deleted_by_user_id, m.edited_at, m.edit_count, m.character_avatar_url_at_post,
       u.username as author_username,
       c.name as character_name,
       COALESCE(m.character_avatar_url_at_post, c.avatar_url) as character_avatar_url,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id) as comment_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.game_id = $1
  AND m.author_id = $2
  AND m.message_type = 'post'
  AND m.is_deleted = false
  AND m.is_draft = false
ORDER BY m.created_at DESC
`

type GetUserPostsInGameParams struct {
	GameID   int32 `json:"game_id"`
	AuthorID int32 `json:"author_id"`
}

type GetUserPostsInGameRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	PhaseID                  pgtype.Int4        `json:"phase_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	MessageType              MessageType        `json:"message_type"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	ThreadDepth              int32              `json:"thread_depth"`
	Visibility               MessageVisibility  `json:"visibility"`
	MentionedCharacterIds    []int32            `json:"mentioned_character_ids"`
	IsEdited                 bool               `json:"is_edited"`
	IsDeleted                bool               `json:"is_deleted"`
	IsDraft                  bool               `json:"is_draft"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	DeletedByUserID          pgtype.Int4        `json:"deleted_by_user_id"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	CharacterAvatarUrlAtPost pgtype.Text        `json:"character_avatar_url_at_post"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	CommentCount             int64              `json:"comment_count"`
}

func (q *Queries) GetUserPostsInGame(ctx context.Context, arg GetUserPostsInGameParams) ([]GetUserPostsInGameRow, error) {
	rows, err := q.db.Query(ctx, getUserPostsInGame, arg.GameID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPostsInGameRow
	for rows.Next() {
		var i GetUserPostsInGameRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.MessageType,
			&i.ParentID,
			&i.ThreadDepth,
			&i.Visibility,
			&i.MentionedCharacterIds,
			&i.IsEdited,
			&i.IsDeleted,
			&i.IsDraft,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.DeletedByUserID,
			&i.EditedAt,
			&i.EditCount,
			&i.CharacterAvatarUrlAtPost,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.CharacterAvatarUrl,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReadMarker = `-- name: GetUserReadMarker :one
SELECT id, user_id, game_id, post_id, last_read_comment_id, last_read_at, created_at, updated_at FROM user_common_room_reads
WHERE user_id = $1 AND post_id = $2
`

type GetUserReadMarkerParams struct {
	UserID int32 `json:"user_id"`
	PostID int32 `json:"post_id"`
}

// Get the read tracking info for a specific user and post
func (q *Queries) GetUserReadMarker(ctx context.Context, arg GetUserReadMarkerParams) (UserCommonRoomRead, error) {
	row := q.db.QueryRow(ctx, getUserReadMarker, arg.UserID, arg.PostID)
	var i UserCommonRoomRead
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.PostID,
		&i.LastReadCommentID,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserReadMarkersForGame = `-- name: GetUserReadMarkersForGame :many
SELECT id, user_id, game_id, post_id, last_read_comment_id, last_read_at, created_at, updated_at FROM user_common_room_reads
WHERE user_id = $1 AND game_id = $2
ORDER BY last_read_at DESC
`

type GetUserReadMarkersForGameParams struct {
	UserID int32 `json:"user_id"`
	GameID int32 `json:"game_id"`
}

// Get all read markers for a user in a specific game
// Used to batch-check which posts have unread content
func (q *Queries) GetUserReadMarkersForGame(ctx context.Context, arg GetUserReadMarkersForGameParams) ([]UserCommonRoomRead, error) {
	rows, err := q.db.Query(ctx, getUserReadMarkersForGame, arg.UserID, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCommonRoomRead
	for rows.Next() {
		var i UserCommonRoomRead
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.PostID,
			&i.LastReadCommentID,
			&i.LastReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPrivateConversations = `-- name: ListAllPrivateConversations :many

WITH conversation_messages AS (
  SELECT
    c.id as conversation_id,
    c.title,
    c.conversation_type,
    c.created_at,
    COUNT(pm.id) as message_count,
    MAX(pm.created_at) as latest_message_at
  FROM conversations c
  LEFT JOIN private_messages pm ON c.id = pm.conversation_id
  WHERE c.game_id = $1
  GROUP BY c.id, c.title, c.conversation_type, c.created_at
),
participants_agg AS (
  -- Deduplicate by character_id first: an NPC shared by GM + co-GMs produces
  -- multiple conversation_participants rows for the same character, so we pick
  -- one row per (conversation_id, character_id) before aggregating names.
  SELECT
    cp.conversation_id,
    array_agg(COALESCE(ch.name, u.username) ORDER BY cp.id) as participant_names,
    array_agg(u.username ORDER BY cp.id) as participant_usernames,
    array_agg(cp.character_id ORDER BY cp.id) as participant_character_ids
  FROM (
    SELECT DISTINCT ON (conversation_id, character_id)
      id, conversation_id, user_id, character_id
    FROM conversation_participants
    ORDER BY conversation_id, character_id, id
  ) cp
  JOIN users u ON cp.user_id = u.id
  LEFT JOIN characters ch ON cp.character_id = ch.id
  GROUP BY cp.conversation_id
),
last_messages AS (
  -- Get the most recent message for each conversation with sender info
  SELECT DISTINCT ON (pm.conversation_id)
    pm.conversation_id,
    LEFT(pm.content, 150) as last_message_content,
    COALESCE(c.name, u.username) as last_sender_name,
    u.username as last_sender_username,
    pm.sender_character_id as last_sender_character_id
  FROM private_messages pm
  JOIN users u ON pm.sender_user_id = u.id
  LEFT JOIN characters c ON pm.sender_character_id = c.id
  WHERE pm.conversation_id IN (
    SELECT id FROM conversations WHERE game_id = $1
  )
  ORDER BY pm.conversation_id, pm.created_at DESC
)
SELECT
  cm.conversation_id,
  cm.title as subject,
  cm.conversation_type,
  cm.created_at,
  cm.message_count,
  cm.latest_message_at as last_message_at,
  pa.participant_names,
  pa.participant_usernames,
  pa.participant_character_ids,
  lm.last_message_content,
  lm.last_sender_name,
  lm.last_sender_username,
  lm.last_sender_character_id
FROM conversation_messages cm
LEFT JOIN participants_agg pa ON cm.conversation_id = pa.conversation_id
LEFT JOIN last_messages lm ON cm.conversation_id = lm.conversation_id
WHERE (
  -- If participant_names filter is provided (not empty array), filter by it
  -- Otherwise, show all conversations
  CASE
    WHEN $2::text[] IS NULL OR array_length($2::text[], 1) IS NULL THEN true
    ELSE pa.participant_names::text[] @> $2::text[]
  END
)
ORDER BY cm.latest_message_at DESC NULLS LAST
LIMIT $4
OFFSET $3
`

type ListAllPrivateConversationsParams struct {
	GameID           int32    `json:"game_id"`
	ParticipantNames []string `json:"participant_names"`
	ResultOffset     int32    `json:"result_offset"`
	ResultLimit      int32    `json:"result_limit"`
}

type ListAllPrivateConversationsRow struct {
	ConversationID          int32              `json:"conversation_id"`
	Subject                 pgtype.Text        `json:"subject"`
	ConversationType        string             `json:"conversation_type"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	MessageCount            int64              `json:"message_count"`
	LastMessageAt           interface{}        `json:"last_message_at"`
	ParticipantNames        interface{}        `json:"participant_names"`
	ParticipantUsernames    interface{}        `json:"participant_usernames"`
	ParticipantCharacterIds interface{}        `json:"participant_character_ids"`
	LastMessageContent      pgtype.Text        `json:"last_message_content"`
	LastSenderName          pgtype.Text        `json:"last_sender_name"`
	LastSenderUsername      pgtype.Text        `json:"last_sender_username"`
	LastSenderCharacterID   pgtype.Int4        `json:"last_sender_character_id"`
}

// ============================================================================
// AUDIENCE PARTICIPATION (Private Message Access)
// ============================================================================
// List all private message conversations in a game (for audience/GM)
// Returns all conversations with metadata, participant information, and last message preview
// Supports pagination and filtering by participant names
func (q *Queries) ListAllPrivateConversations(ctx context.Context, arg ListAllPrivateConversationsParams) ([]ListAllPrivateConversationsRow, error) {
	rows, err := q.db.Query(ctx, listAllPrivateConversations,
		arg.GameID,
		arg.ParticipantNames,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPrivateConversationsRow
	for rows.Next() {
		var i ListAllPrivateConversationsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.Subject,
			&i.ConversationType,
			&i.CreatedAt,
			&i.MessageCount,
			&i.LastMessageAt,
			&i.ParticipantNames,
			&i.ParticipantUsernames,
			&i.ParticipantCharacterIds,
			&i.LastMessageContent,
			&i.LastSenderName,
			&i.LastSenderUsername,
			&i.LastSenderCharacterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllCommentsReadForPhase = `-- name: MarkAllCommentsReadForPhase :exec
WITH RECURSIVE comment_threads AS (
    SELECT
        c.id as comment_id,
        c.parent_id as post_id
    FROM messages c
    WHERE c.parent_id IN (
        SELECT p.id FROM messages p
        WHERE p.game_id = $2 AND p.phase_id = $3 AND p.message_type = 'post' AND p.is_deleted = false
    )
    AND c.is_deleted = false

    UNION ALL

    SELECT
        m.id as comment_id,
        ct.post_id
    FROM messages m
    INNER JOIN comment_threads ct ON m.parent_id = ct.comment_id
    WHERE m.is_deleted = false
)
INSERT INTO user_comment_reads (user_id, comment_id, post_id, game_id)
SELECT $1, ct.comment_id, ct.post_id, $2
FROM comment_threads ct
ON CONFLICT (user_id, comment_id) DO NOTHING
`

type MarkAllCommentsReadForPhaseParams struct {
	UserID  int32       `json:"user_id"`
	GameID  int32       `json:"game_id"`
	PhaseID pgtype.Int4 `json:"phase_id"`
}

// Bulk-insert manual read records for every comment in a phase, for one user.
// Comments can be nested arbitrarily deep (replies to replies), so each
// comment's root post_id is resolved by walking up parent_id, mirroring the
// comment_threads CTE used by GetUnreadCommentIDsForPosts.
// Idempotent: existing records are left untouched.
func (q *Queries) MarkAllCommentsReadForPhase(ctx context.Context, arg MarkAllCommentsReadForPhaseParams) error {
	_, err := q.db.Exec(ctx, markAllCommentsReadForPhase, arg.UserID, arg.GameID, arg.PhaseID)
	return err
}

const markCommentRead = `-- name: MarkCommentRead :exec

INSERT INTO user_comment_reads (user_id, comment_id, post_id, game_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, comment_id) DO NOTHING
`

type MarkCommentReadParams struct {
	UserID    int32 `json:"user_id"`
	CommentID int32 `json:"comment_id"`
	PostID    int32 `json:"post_id"`
	GameID    int32 `json:"game_id"`
}

// ============================================================================
// MANUAL READ TRACKING (per-comment, user-controlled)
// ============================================================================
// Insert a manual read record; ignore if already exists (idempotent)
func (q *Queries) MarkCommentRead(ctx context.Context, arg MarkCommentReadParams) error {
	_, err := q.db.Exec(ctx, markCommentRead,
		arg.UserID,
		arg.CommentID,
		arg.PostID,
		arg.GameID,
	)
	return err
}

const markPostRead = `-- name: MarkPostRead :one

INSERT INTO user_common_room_reads (
    user_id,
    game_id,
    post_id,
    last_read_comment_id,
    last_read_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
)
ON CONFLICT (user_id, post_id)
DO UPDATE SET
    last_read_comment_id = EXCLUDED.last_read_comment_id,
    last_read_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, game_id, post_id, last_read_comment_id, last_read_at, created_at, updated_at
`

type MarkPostReadParams struct {
	UserID            int32       `json:"user_id"`
	GameID            int32       `json:"game_id"`
	PostID            int32       `json:"post_id"`
	LastReadCommentID pgtype.Int4 `json:"last_read_comment_id"`
}

// ============================================================================
// READ TRACKING (Common Room)
// ============================================================================
// Mark a post (and optionally a specific comment) as read by a user
// This is an upsert - creates new record or updates existing one
func (q *Queries) MarkPostRead(ctx context.Context, arg MarkPostReadParams) (UserCommonRoomRead, error) {
	row := q.db.QueryRow(ctx, markPostRead,
		arg.UserID,
		arg.GameID,
		arg.PostID,
		arg.LastReadCommentID,
	)
	var i UserCommonRoomRead
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.PostID,
		&i.LastReadCommentID,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const publishDraftPostsForPhase = `-- name: PublishDraftPostsForPhase :exec
UPDATE messages
SET is_draft = false
WHERE phase_id = $1
  AND message_type = 'post'
  AND is_draft = true
  AND is_deleted = false
`

// Called atomically during phase activation. Clears is_draft flag.
func (q *Queries) PublishDraftPostsForPhase(ctx context.Context, phaseID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, publishDraftPostsForPhase, phaseID)
	return err
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM message_reactions
WHERE message_id = $1 AND user_id = $2 AND reaction_type = $3
`

type RemoveReactionParams struct {
	MessageID    int32  `json:"message_id"`
	UserID       int32  `json:"user_id"`
	ReactionType string `json:"reaction_type"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.MessageID, arg.UserID, arg.ReactionType)
	return err
}

const unmarkCommentRead = `-- name: UnmarkCommentRead :exec
DELETE FROM user_comment_reads
WHERE user_id = $1 AND comment_id = $2
`

type UnmarkCommentReadParams struct {
	UserID    int32 `json:"user_id"`
	CommentID int32 `json:"comment_id"`
}

// Remove a manual read record
func (q *Queries) UnmarkCommentRead(ctx context.Context, arg UnmarkCommentReadParams) error {
	_, err := q.db.Exec(ctx, unmarkCommentRead, arg.UserID, arg.CommentID)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE messages
SET content = $2,
    character_id = COALESCE($3, character_id),
    mentioned_character_ids = $4,
    is_edited = true,
    edited_at = NOW(),
    edit_count = edit_count + 1
WHERE id = $1
  AND deleted_at IS NULL
  AND message_type = 'comment'
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, mentioned_character_ids, is_edited, is_deleted, is_draft, created_at, deleted_at, deleted_by_user_id, edited_at, edit_count, character_avatar_url_at_post
`

type UpdateCommentParams struct {
	ID                    int32   `json:"id"`
	Content               string  `json:"content"`
	CharacterID           int32   `json:"character_id"`
	MentionedCharacterIds []int32 `json:"mentioned_character_ids"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateComment,
		arg.ID,
		arg.Content,
		arg.CharacterID,
		arg.MentionedCharacterIds,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.MentionedCharacterIds,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsDraft,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.EditedAt,
		&i.EditCount,
		&i.CharacterAvatarUrlAtPost,
	)
	return i, err
}

const updateDraftPost = `-- name: UpdateDraftPost :one
UPDATE messages
SET content = $2,
    mentioned_character_ids = $3
WHERE id = $1
  AND message_type = 'post'
  AND is_draft = true
  AND is_deleted = false
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, mentioned_character_ids, is_edited, is_deleted, is_draft, created_at, deleted_at, deleted_by_user_id, edited_at, edit_count, character_avatar_url_at_post
`

type UpdateDraftPostParams struct {
	ID                    int32   `json:"id"`
	Content               string  `json:"content"`
	MentionedCharacterIds []int32 `json:"mentioned_character_ids"`
}

func (q *Queries) UpdateDraftPost(ctx context.Context, arg UpdateDraftPostParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateDraftPost, arg.ID, arg.Content, arg.MentionedCharacterIds)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.MentionedCharacterIds,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsDraft,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.EditedAt,
		&i.EditCount,
		&i.CharacterAvatarUrlAtPost,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
WITH updated AS (
  UPDATE messages
  SET content = $2,
      is_edited = true,
      edited_at = NOW(),
      edit_count = edit_count + 1
  WHERE messages.id = $1
    AND messages.is_deleted = false
    AND messages.message_type = 'post'
  RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, mentioned_character_ids, is_edited, is_deleted, is_draft, created_at, deleted_at, deleted_by_user_id, edited_at, edit_count, character_avatar_url_at_post
)
SELECT
  m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.mentioned_character_ids, m.is_edited, m.is_deleted, m.is_draft, m.created_at, m.deleted_at, m.deleted_by_user_id, m.edited_at, m.edit_count, m.character_avatar_url_at_post,
  u.username as author_username,
  c.name as character_name,
  -- Editing a post never repaints its avatar, so return the pinned value.
  COALESCE(m.character_avatar_url_at_post, c.avatar_url) as character_avatar_url,
  (SELECT COUNT(*) FROM messages WHERE parent_id = m.id) as comment_count
FROM updated m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
`

type UpdatePostParams struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
}

type UpdatePostRow struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	PhaseID                  pgtype.Int4        `json:"phase_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	MessageType              MessageType        `json:"message_type"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	ThreadDepth              int32              `json:"thread_depth"`
	Visibility               MessageVisibility  `json:"visibility"`
	MentionedCharacterIds    []int32            `json:"mentioned_character_ids"`
	IsEdited                 bool               `json:"is_edited"`
	IsDeleted                bool               `json:"is_deleted"`
	IsDraft                  bool               `json:"is_draft"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	DeletedByUserID          pgtype.Int4        `json:"deleted_by_user_id"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	CharacterAvatarUrlAtPost pgtype.Text        `json:"character_avatar_url_at_post"`
	AuthorUsername           string             `json:"author_username"`
	CharacterName            pgtype.Text        `json:"character_name"`
	CharacterAvatarUrl       pgtype.Text        `json:"character_avatar_url"`
	CommentCount             int64              `json:"comment_count"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (UpdatePostRow, error) {
	row := q.db.QueryRow(ctx, updatePost, arg.ID, arg.Content)
	var i UpdatePostRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.MentionedCharacterIds,
		&i.IsEdited,
		&i.IsDeleted,
		&i.IsDraft,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
		&i.EditedAt,
		&i.EditCount,
		&i.CharacterAvatarUrlAtPost,
		&i.AuthorUsername,
		&i.CharacterName,
		&i.CharacterAvatarUrl,
		&i.CommentCount,
	)
	return i, err
}
