// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MessageType string

const (
	MessageTypePost           MessageType = "post"
	MessageTypeComment        MessageType = "comment"
	MessageTypePrivateMessage MessageType = "private_message"
)

func (e *MessageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageType(s)
	case string:
		*e = MessageType(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageType: %T", src)
	}
	return nil
}

type NullMessageType struct {
	MessageType MessageType `json:"message_type"`
	Valid       bool        `json:"valid"` // Valid is true if MessageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageType) Scan(value interface{}) error {
	if value == nil {
		ns.MessageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageType), nil
}

type MessageVisibility string

const (
	MessageVisibilityGame    MessageVisibility = "game"
	MessageVisibilityPrivate MessageVisibility = "private"
)

func (e *MessageVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageVisibility(s)
	case string:
		*e = MessageVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageVisibility: %T", src)
	}
	return nil
}

type NullMessageVisibility struct {
	MessageVisibility MessageVisibility `json:"message_visibility"`
	Valid             bool              `json:"valid"` // Valid is true if MessageVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.MessageVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageVisibility), nil
}

type ActionResult struct {
	ID                 int32              `json:"id"`
	GameID             int32              `json:"game_id"`
	UserID             int32              `json:"user_id"`
	PhaseID            int32              `json:"phase_id"`
	CharacterID        pgtype.Int4        `json:"character_id"`
	ActionSubmissionID pgtype.Int4        `json:"action_submission_id"`
	GmUserID           int32              `json:"gm_user_id"`
	Content            string             `json:"content"`
	IsPublished        pgtype.Bool        `json:"is_published"`
	SentAt             pgtype.Timestamptz `json:"sent_at"`
	ParentResultID     pgtype.Int4        `json:"parent_result_id"`
	RevealDelayMinutes pgtype.Int4        `json:"reveal_delay_minutes"`
	ReleasedAt         pgtype.Timestamptz `json:"released_at"`
}

type ActionResultCharacterUpdate struct {
	ID             int32              `json:"id"`
	ActionResultID int32              `json:"action_result_id"`
	CharacterID    int32              `json:"character_id"`
	ModuleType     string             `json:"module_type"`
	FieldName      string             `json:"field_name"`
	FieldValue     pgtype.Text        `json:"field_value"`
	FieldType      string             `json:"field_type"`
	Operation      string             `json:"operation"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ActionSubmission struct {
	ID          int32              `json:"id"`
	GameID      int32              `json:"game_id"`
	UserID      int32              `json:"user_id"`
	PhaseID     int32              `json:"phase_id"`
	CharacterID pgtype.Int4        `json:"character_id"`
	Content     string             `json:"content"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Character struct {
	ID                  int32              `json:"id"`
	GameID              int32              `json:"game_id"`
	UserID              pgtype.Int4        `json:"user_id"`
	Name                string             `json:"name"`
	CharacterType       string             `json:"character_type"`
	Status              pgtype.Text        `json:"status"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	IsActive            bool               `json:"is_active"`
	OriginalOwnerUserID pgtype.Int4        `json:"original_owner_user_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type CharacterDatum struct {
	ID          int32              `json:"id"`
	CharacterID int32              `json:"character_id"`
	ModuleType  string             `json:"module_type"`
	FieldName   string             `json:"field_name"`
	FieldValue  pgtype.Text        `json:"field_value"`
	FieldType   pgtype.Text        `json:"field_type"`
	IsPublic    pgtype.Bool        `json:"is_public"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CommonRoomPoll struct {
	ID                         int32              `json:"id"`
	GameID                     int32              `json:"game_id"`
	PhaseID                    pgtype.Int4        `json:"phase_id"`
	CreatedByUserID            int32              `json:"created_by_user_id"`
	CreatedByCharacterID       pgtype.Int4        `json:"created_by_character_id"`
	Question                   string             `json:"question"`
	Description                pgtype.Text        `json:"description"`
	Deadline                   pgtype.Timestamptz `json:"deadline"`
	ShowIndividualVotes        pgtype.Bool        `json:"show_individual_votes"`
	AllowOtherOption           pgtype.Bool        `json:"allow_other_option"`
	HideResultsFromPlayers     bool               `json:"hide_results_from_players"`
	AllowAudienceVoting        bool               `json:"allow_audience_voting"`
	ShowRunningTotalsToPlayers bool               `json:"show_running_totals_to_players"`
	IsDeleted                  pgtype.Bool        `json:"is_deleted"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type Community struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	BannerUrl   pgtype.Text        `json:"banner_url"`
	OwnerUserID int32              `json:"owner_user_id"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CommunityBan struct {
	ID             int32              `json:"id"`
	CommunityID    int32              `json:"community_id"`
	UserID         int32              `json:"user_id"`
	Reason         pgtype.Text        `json:"reason"`
	BannedByUserID pgtype.Int4        `json:"banned_by_user_id"`
	BannedAt       pgtype.Timestamptz `json:"banned_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type CommunityBanEvent struct {
	ID           int32              `json:"id"`
	CommunityID  int32              `json:"community_id"`
	TargetUserID int32              `json:"target_user_id"`
	ActorUserID  pgtype.Int4        `json:"actor_user_id"`
	Action       string             `json:"action"`
	Reason       pgtype.Text        `json:"reason"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CommunityDocument struct {
	ID              int32              `json:"id"`
	CommunityID     int32              `json:"community_id"`
	Title           string             `json:"title"`
	Content         string             `json:"content"`
	Status          string             `json:"status"`
	SortOrder       int32              `json:"sort_order"`
	CreatedByUserID pgtype.Int4        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CommunityModerator struct {
	ID              int32              `json:"id"`
	CommunityID     int32              `json:"community_id"`
	UserID          int32              `json:"user_id"`
	GrantedByUserID pgtype.Int4        `json:"granted_by_user_id"`
	GrantedAt       pgtype.Timestamptz `json:"granted_at"`
}

type CommunityWebhook struct {
	ID            int32              `json:"id"`
	CommunityID   int32              `json:"community_id"`
	Url           string             `json:"url"`
	Label         pgtype.Text        `json:"label"`
	IsEnabled     bool               `json:"is_enabled"`
	Events        []string           `json:"events"`
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
	LastError     pgtype.Text        `json:"last_error"`
	LastErrorAt   pgtype.Timestamptz `json:"last_error_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Conversation struct {
	ID               int32              `json:"id"`
	GameID           int32              `json:"game_id"`
	ConversationType string             `json:"conversation_type"`
	Title            pgtype.Text        `json:"title"`
	CreatedByUserID  int32              `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ConversationParticipant struct {
	ID             int32              `json:"id"`
	ConversationID int32              `json:"conversation_id"`
	UserID         int32              `json:"user_id"`
	CharacterID    pgtype.Int4        `json:"character_id"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	LastReadAt     pgtype.Timestamptz `json:"last_read_at"`
}

type ConversationRead struct {
	ID                int32              `json:"id"`
	UserID            int32              `json:"user_id"`
	ConversationID    int32              `json:"conversation_id"`
	LastReadMessageID pgtype.Int4        `json:"last_read_message_id"`
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type EmailVerificationToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    int32              `json:"user_id"`
	Token     string             `json:"token"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type FingerprintBan struct {
	ID           int32              `json:"id"`
	Fingerprint  string             `json:"fingerprint"`
	CreatedBy    int32              `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Reason       pgtype.Text        `json:"reason"`
	BannedUserID pgtype.Int4        `json:"banned_user_id"`
}

type Game struct {
	ID                      int32              `json:"id"`
	Title                   string             `json:"title"`
	Description             pgtype.Text        `json:"description"`
	GmUserID                int32              `json:"gm_user_id"`
	State                   pgtype.Text        `json:"state"`
	Genre                   pgtype.Text        `json:"genre"`
	StartDate               pgtype.Timestamptz `json:"start_date"`
	EndDate                 pgtype.Timestamptz `json:"end_date"`
	RecruitmentDeadline     pgtype.Timestamptz `json:"recruitment_deadline"`
	MaxPlayers              pgtype.Int4        `json:"max_players"`
	IsPublic                pgtype.Bool        `json:"is_public"`
	IsAnonymous             bool               `json:"is_anonymous"`
	AutoAcceptAudience      bool               `json:"auto_accept_audience"`
	AllowGroupConversations bool               `json:"allow_group_conversations"`
	PortraitAvatars         bool               `json:"portrait_avatars"`
	BannerUrl               pgtype.Text        `json:"banner_url"`
	CommonRoomOpenDay       pgtype.Int2        `json:"common_room_open_day"`
	CommonRoomOpenTime      pgtype.Time        `json:"common_room_open_time"`
	CommonRoomCloseDay      pgtype.Int2        `json:"common_room_close_day"`
	CommonRoomCloseTime     pgtype.Time        `json:"common_room_close_time"`
	ScheduleTimezone        pgtype.Text        `json:"schedule_timezone"`
	CharacterSheet          []byte             `json:"character_sheet"`
	CommunityID             pgtype.Int4        `json:"community_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type GameApplication struct {
	ID               int32              `json:"id"`
	GameID           int32              `json:"game_id"`
	UserID           int32              `json:"user_id"`
	Role             string             `json:"role"`
	Message          pgtype.Text        `json:"message"`
	Status           pgtype.Text        `json:"status"`
	ReviewedByUserID pgtype.Int4        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
	IsPublished      bool               `json:"is_published"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type GameDeadline struct {
	ID              int32              `json:"id"`
	GameID          int32              `json:"game_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Deadline        pgtype.Timestamptz `json:"deadline"`
	CreatedByUserID int32              `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type GameExport struct {
	ID                 int32              `json:"id"`
	GameID             int32              `json:"game_id"`
	RequestedByUserID  pgtype.Int4        `json:"requested_by_user_id"`
	Status             string             `json:"status"`
	ContentFingerprint pgtype.Text        `json:"content_fingerprint"`
	StoragePath        pgtype.Text        `json:"storage_path"`
	SizeBytes          pgtype.Int8        `json:"size_bytes"`
	FileCount          pgtype.Int4        `json:"file_count"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	ProgressNote       pgtype.Text        `json:"progress_note"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type GameLog struct {
	ID        int32              `json:"id"`
	GameID    int32              `json:"game_id"`
	Type      string             `json:"type"`
	Message   pgtype.Text        `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GameLootTable struct {
	ID        int32              `json:"id"`
	GameID    int32              `json:"game_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type GameLootTableContent struct {
	ID          int32       `json:"id"`
	LootTableID int32       `json:"loot_table_id"`
	Name        string      `json:"name"`
	Data        pgtype.Text `json:"data"`
}

type GameParticipant struct {
	ID              int32              `json:"id"`
	GameID          int32              `json:"game_id"`
	UserID          int32              `json:"user_id"`
	Role            string             `json:"role"`
	Status          pgtype.Text        `json:"status"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
	RemovedAt       pgtype.Timestamptz `json:"removed_at"`
	RemovedByUserID pgtype.Int4        `json:"removed_by_user_id"`
	IsFormerPlayer  bool               `json:"is_former_player"`
}

type GamePhase struct {
	ID          int32              `json:"id"`
	GameID      int32              `json:"game_id"`
	PhaseType   string             `json:"phase_type"`
	PhaseNumber int32              `json:"phase_number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	IsActive    pgtype.Bool        `json:"is_active"`
	IsPublished bool               `json:"is_published"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Handout struct {
	ID        int32              `json:"id"`
	GameID    int32              `json:"game_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type HandoutComment struct {
	ID              int32              `json:"id"`
	HandoutID       int32              `json:"handout_id"`
	UserID          int32              `json:"user_id"`
	ParentCommentID pgtype.Int4        `json:"parent_comment_id"`
	Content         string             `json:"content"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	EditCount       int32              `json:"edit_count"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserID pgtype.Int4        `json:"deleted_by_user_id"`
}

type IpBan struct {
	ID           int32              `json:"id"`
	IpAddress    string             `json:"ip_address"`
	CreatedBy    int32              `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Reason       pgtype.Text        `json:"reason"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	BannedUserID pgtype.Int4        `json:"banned_user_id"`
}

type Message struct {
	ID                       int32              `json:"id"`
	GameID                   int32              `json:"game_id"`
	PhaseID                  pgtype.Int4        `json:"phase_id"`
	AuthorID                 int32              `json:"author_id"`
	CharacterID              int32              `json:"character_id"`
	Content                  string             `json:"content"`
	MessageType              MessageType        `json:"message_type"`
	ParentID                 pgtype.Int4        `json:"parent_id"`
	ThreadDepth              int32              `json:"thread_depth"`
	Visibility               MessageVisibility  `json:"visibility"`
	MentionedCharacterIds    []int32            `json:"mentioned_character_ids"`
	IsEdited                 bool               `json:"is_edited"`
	IsDeleted                bool               `json:"is_deleted"`
	IsDraft                  bool               `json:"is_draft"`
	CreatedAt                pgtype.Timestamp   `json:"created_at"`
	DeletedAt                pgtype.Timestamp   `json:"deleted_at"`
	DeletedByUserID          pgtype.Int4        `json:"deleted_by_user_id"`
	EditedAt                 pgtype.Timestamptz `json:"edited_at"`
	EditCount                int32              `json:"edit_count"`
	CharacterAvatarUrlAtPost pgtype.Text        `json:"character_avatar_url_at_post"`
}

type MessageReaction struct {
	ID           int32            `json:"id"`
	MessageID    int32            `json:"message_id"`
	UserID       int32            `json:"user_id"`
	ReactionType string           `json:"reaction_type"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type MessageRecipient struct {
	ID          int32            `json:"id"`
	MessageID   int32            `json:"message_id"`
	RecipientID int32            `json:"recipient_id"`
	IsRead      bool             `json:"is_read"`
	ReadAt      pgtype.Timestamp `json:"read_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Notification struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"user_id"`
	GameID      pgtype.Int4        `json:"game_id"`
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Content     pgtype.Text        `json:"content"`
	RelatedType pgtype.Text        `json:"related_type"`
	RelatedID   pgtype.Int4        `json:"related_id"`
	LinkUrl     pgtype.Text        `json:"link_url"`
	ContextType pgtype.Text        `json:"context_type"`
	ContextID   pgtype.Int4        `json:"context_id"`
	IsRead      pgtype.Bool        `json:"is_read"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type NpcAssignment struct {
	ID               int32              `json:"id"`
	CharacterID      int32              `json:"character_id"`
	AssignedUserID   int32              `json:"assigned_user_id"`
	AssignedByUserID int32              `json:"assigned_by_user_id"`
	AssignedAt       pgtype.Timestamptz `json:"assigned_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    int32              `json:"user_id"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type PhaseTransition struct {
	ID          int32              `json:"id"`
	GameID      int32              `json:"game_id"`
	FromPhaseID pgtype.Int4        `json:"from_phase_id"`
	ToPhaseID   int32              `json:"to_phase_id"`
	InitiatedBy int32              `json:"initiated_by"`
	Reason      pgtype.Text        `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PollOption struct {
	ID           int32              `json:"id"`
	PollID       int32              `json:"poll_id"`
	OptionText   string             `json:"option_text"`
	DisplayOrder int32              `json:"display_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PollVote struct {
	ID               int32              `json:"id"`
	PollID           int32              `json:"poll_id"`
	UserID           int32              `json:"user_id"`
	SelectedOptionID pgtype.Int4        `json:"selected_option_id"`
	OtherResponse    pgtype.Text        `json:"other_response"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PrivateMessage struct {
	ID                int32              `json:"id"`
	ConversationID    int32              `json:"conversation_id"`
	SenderUserID      int32              `json:"sender_user_id"`
	SenderCharacterID pgtype.Int4        `json:"sender_character_id"`
	Content           string             `json:"content"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	IsDeleted         pgtype.Bool        `json:"is_deleted"`
	IsEdited          bool               `json:"is_edited"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	EditCount         int32              `json:"edit_count"`
}

type RegistrationAttempt struct {
	ID                pgtype.UUID        `json:"id"`
	Email             string             `json:"email"`
	Username          string             `json:"username"`
	IpAddress         string             `json:"ip_address"`
	UserAgent         pgtype.Text        `json:"user_agent"`
	HoneypotTriggered bool               `json:"honeypot_triggered"`
	CaptchaPassed     bool               `json:"captcha_passed"`
	BlockedReason     pgtype.Text        `json:"blocked_reason"`
	Successful        bool               `json:"successful"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"user_id"`
	Data        string             `json:"data"`
	Expires     pgtype.Timestamptz `json:"expires"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	Fingerprint pgtype.Text        `json:"fingerprint"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

type Thread struct {
	ID              int32              `json:"id"`
	GameID          int32              `json:"game_id"`
	PhaseID         pgtype.Int4        `json:"phase_id"`
	Title           string             `json:"title"`
	Content         pgtype.Text        `json:"content"`
	CreatedByUserID int32              `json:"created_by_user_id"`
	IsPinned        pgtype.Bool        `json:"is_pinned"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ThreadPost struct {
	ID           int32              `json:"id"`
	ThreadID     int32              `json:"thread_id"`
	ParentPostID pgtype.Int4        `json:"parent_post_id"`
	UserID       int32              `json:"user_id"`
	CharacterID  pgtype.Int4        `json:"character_id"`
	Content      string             `json:"content"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                   int32              `json:"id"`
	Username             string             `json:"username"`
	Email                string             `json:"email"`
	Password             string             `json:"password"`
	IsAdmin              pgtype.Bool        `json:"is_admin"`
	CreatedAt            pgtype.Timestamp   `json:"created_at"`
	DisplayName          pgtype.Text        `json:"display_name"`
	Bio                  pgtype.Text        `json:"bio"`
	AvatarUrl            pgtype.Text        `json:"avatar_url"`
	Timezone             pgtype.Text        `json:"timezone"`
	EmailNotifications   pgtype.Bool        `json:"email_notifications"`
	HighContrast         pgtype.Bool        `json:"high_contrast"`
	IsBanned             bool               `json:"is_banned"`
	BannedAt             pgtype.Timestamp   `json:"banned_at"`
	BannedByUserID       pgtype.Int4        `json:"banned_by_user_id"`
	EmailVerified        bool               `json:"email_verified"`
	EmailChangePending   pgtype.Text        `json:"email_change_pending"`
	PasswordChangedAt    pgtype.Timestamptz `json:"password_changed_at"`
	UsernameChangedAt    pgtype.Timestamptz `json:"username_changed_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	DeletionScheduledFor pgtype.Timestamptz `json:"deletion_scheduled_for"`
	PendingApproval      bool               `json:"pending_approval"`
	PendingApprovalSince pgtype.Timestamptz `json:"pending_approval_since"`
}

type UserCommentRead struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	CommentID int32              `json:"comment_id"`
	PostID    int32              `json:"post_id"`
	GameID    int32              `json:"game_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserCommonRoomRead struct {
	ID                int32              `json:"id"`
	UserID            int32              `json:"user_id"`
	GameID            int32              `json:"game_id"`
	PostID            int32              `json:"post_id"`
	LastReadCommentID pgtype.Int4        `json:"last_read_comment_id"`
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserDiscordAccount struct {
	ID              int32              `json:"id"`
	UserID          int32              `json:"user_id"`
	DiscordUserID   string             `json:"discord_user_id"`
	DiscordUsername string             `json:"discord_username"`
	AccessToken     string             `json:"access_token"`
	RefreshToken    pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserPreference struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"user_id"`
	Preferences []byte             `json:"preferences"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
