// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, game_id, type, title, content, related_type, related_id, link_url, context_type, context_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, game_id, type, title, content, related_type, related_id, link_url, context_type, context_id, is_read, read_at, created_at
`

type CreateNotificationParams struct {
	UserID      int32       `json:"user_id"`
	GameID      pgtype.Int4 `json:"game_id"`
	Type        string      `json:"type"`
	Title       string      `json:"title"`
	Content     pgtype.Text `json:"content"`
	RelatedType pgtype.Text `json:"related_type"`
	RelatedID   pgtype.Int4 `json:"related_id"`
	LinkUrl     pgtype.Text `json:"link_url"`
	ContextType pgtype.Text `json:"context_type"`
	ContextID   pgtype.Int4 `json:"context_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.GameID,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.RelatedType,
		arg.RelatedID,
		arg.LinkUrl,
		arg.ContextType,
		arg.ContextID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.RelatedType,
		&i.RelatedID,
		&i.LinkUrl,
		&i.ContextType,
		&i.ContextID,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldNotifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications)
	return err
}

const getGameNotifications = `-- name: GetGameNotifications :many
SELECT n.id, n.user_id, n.game_id, n.type, n.title, n.content, n.related_type, n.related_id, n.link_url, n.context_type, n.context_id, n.is_read, n.read_at, n.created_at, u.username
FROM notifications n
JOIN users u ON n.user_id = u.id
WHERE n.game_id = $1
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $3
`

type GetGameNotificationsParams struct {
	GameID pgtype.Int4 `json:"game_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetGameNotificationsRow struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"user_id"`
	GameID      pgtype.Int4        `json:"game_id"`
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Content     pgtype.Text        `json:"content"`
	RelatedType pgtype.Text        `json:"related_type"`
	RelatedID   pgtype.Int4        `json:"related_id"`
	LinkUrl     pgtype.Text        `json:"link_url"`
	ContextType pgtype.Text        `json:"context_type"`
	ContextID   pgtype.Int4        `json:"context_id"`
	IsRead      pgtype.Bool        `json:"is_read"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
}

func (q *Queries) GetGameNotifications(ctx context.Context, arg GetGameNotificationsParams) ([]GetGameNotificationsRow, error) {
	rows, err := q.db.Query(ctx, getGameNotifications, arg.GameID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameNotificationsRow
	for rows.Next() {
		var i GetGameNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.RelatedType,
			&i.RelatedID,
			&i.LinkUrl,
			&i.ContextType,
			&i.ContextID,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnreadNotifications = `-- name: GetUnreadNotifications :many
SELECT n.id, n.user_id, n.game_id, n.type, n.title, n.content, n.related_type, n.related_id, n.link_url, n.context_type, n.context_id, n.is_read, n.read_at, n.created_at, g.title as game_title
FROM notifications n
LEFT JOIN games g ON n.game_id = g.id
WHERE n.user_id = $1 AND n.is_read = false
ORDER BY n.created_at DESC
`

type GetUnreadNotificationsRow struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"user_id"`
	GameID      pgtype.Int4        `json:"game_id"`
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Content     pgtype.Text        `json:"content"`
	RelatedType pgtype.Text        `json:"related_type"`
	RelatedID   pgtype.Int4        `json:"related_id"`
	LinkUrl     pgtype.Text        `json:"link_url"`
	ContextType pgtype.Text        `json:"context_type"`
	ContextID   pgtype.Int4        `json:"context_id"`
	IsRead      pgtype.Bool        `json:"is_read"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	GameTitle   pgtype.Text        `json:"game_title"`
}

func (q *Queries) GetUnreadNotifications(ctx context.Context, userID int32) ([]GetUnreadNotificationsRow, error) {
	rows, err := q.db.Query(ctx, getUnreadNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreadNotificationsRow
	for rows.Next() {
		var i GetUnreadNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.RelatedType,
			&i.RelatedID,
			&i.LinkUrl,
			&i.ContextType,
			&i.ContextID,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
			&i.GameTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT n.id, n.user_id, n.game_id, n.type, n.title, n.content, n.related_type, n.related_id, n.link_url, n.context_type, n.context_id, n.is_read, n.read_at, n.created_at, g.title as game_title
FROM notifications n
LEFT JOIN games g ON n.game_id = g.id
WHERE n.user_id = $1
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserNotificationsParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUserNotificationsRow struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"user_id"`
	GameID      pgtype.Int4        `json:"game_id"`
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Content     pgtype.Text        `json:"content"`
	RelatedType pgtype.Text        `json:"related_type"`
	RelatedID   pgtype.Int4        `json:"related_id"`
	LinkUrl     pgtype.Text        `json:"link_url"`
	ContextType pgtype.Text        `json:"context_type"`
	ContextID   pgtype.Int4        `json:"context_id"`
	IsRead      pgtype.Bool        `json:"is_read"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	GameTitle   pgtype.Text        `json:"game_title"`
}

func (q *Queries) GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]GetUserNotificationsRow, error) {
	rows, err := q.db.Query(ctx, getUserNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserNotificationsRow
	for rows.Next() {
		var i GetUserNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.RelatedType,
			&i.RelatedID,
			&i.LinkUrl,
			&i.ContextType,
			&i.ContextID,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
			&i.GameTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET is_read = true, read_at = NOW()
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markGameNotificationsRead = `-- name: MarkGameNotificationsRead :exec
UPDATE notifications
SET is_read = true, read_at = NOW()
WHERE user_id = $1 AND game_id = $2 AND is_read = FALSE
`

type MarkGameNotificationsReadParams struct {
	UserID int32       `json:"user_id"`
	GameID pgtype.Int4 `json:"game_id"`
}

func (q *Queries) MarkGameNotificationsRead(ctx context.Context, arg MarkGameNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markGameNotificationsRead, arg.UserID, arg.GameID)
	return err
}

const markNotificationAndContextRead = `-- name: MarkNotificationAndContextRead :execrows
WITH target AS (
  SELECT t0.id AS id, t0.context_type AS context_type, t0.context_id AS context_id
  FROM notifications t0
  WHERE t0.id = $1 AND t0.user_id = $2
)
UPDATE notifications n
SET is_read = true, read_at = NOW()
FROM target t
WHERE n.user_id = $2
  AND n.is_read = FALSE
  AND (
    n.id = t.id
    OR (
      t.context_type IS NOT NULL
      AND t.context_id IS NOT NULL
      AND n.context_type = t.context_type
      AND n.context_id = t.context_id
    )
  )
`

type MarkNotificationAndContextReadParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// Marks a notification read along with every other unread notification sharing
// its context (e.g. clicking one message notification clears the whole
// conversation). Notifications with a NULL context affect only themselves.
// Scoped to the owning user, so a foreign notification ID matches nothing.
func (q *Queries) MarkNotificationAndContextRead(ctx context.Context, arg MarkNotificationAndContextReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationAndContextRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationUnread = `-- name: MarkNotificationUnread :one
UPDATE notifications
SET is_read = false, read_at = NULL
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, game_id, type, title, content, related_type, related_id, link_url, context_type, context_id, is_read, read_at, created_at
`

type MarkNotificationUnreadParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) MarkNotificationUnread(ctx context.Context, arg MarkNotificationUnreadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationUnread, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.RelatedType,
		&i.RelatedID,
		&i.LinkUrl,
		&i.ContextType,
		&i.ContextID,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const markNotificationsReadByContext = `-- name: MarkNotificationsReadByContext :execrows
UPDATE notifications
SET is_read = true, read_at = NOW()
WHERE user_id = $1
  AND context_type = $2
  AND context_id = $3
  AND is_read = FALSE
`

type MarkNotificationsReadByContextParams struct {
	UserID      int32       `json:"user_id"`
	ContextType pgtype.Text `json:"context_type"`
	ContextID   pgtype.Int4 `json:"context_id"`
}

// Marks every unread notification a user has for one container (e.g. all
// messages in a conversation) as read. Returns the number of rows affected so
// callers can reconcile client-side unread counts.
func (q *Queries) MarkNotificationsReadByContext(ctx context.Context, arg MarkNotificationsReadByContextParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationsReadByContext, arg.UserID, arg.ContextType, arg.ContextID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notificationExistsForUser = `-- name: NotificationExistsForUser :one
SELECT EXISTS (
  SELECT 1 FROM notifications WHERE id = $1 AND user_id = $2
)
`

type NotificationExistsForUserParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// Ownership probe used to distinguish "already read" from "not yours", which
// rows-affected alone cannot tell apart.
func (q *Queries) NotificationExistsForUser(ctx context.Context, arg NotificationExistsForUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, notificationExistsForUser, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const notifyAudienceMembers = `-- name: NotifyAudienceMembers :exec
INSERT INTO notifications (user_id, game_id, type, title, content, related_type, related_id, link_url)
SELECT gp.user_id, $1, $2, $3, $4, $5, $6, $7
FROM game_participants gp
WHERE gp.game_id = $1 AND gp.role = 'audience' AND gp.status = 'active' AND gp.user_id != $8
`

type NotifyAudienceMembersParams struct {
	GameID      pgtype.Int4 `json:"game_id"`
	Type        string      `json:"type"`
	Title       string      `json:"title"`
	Content     pgtype.Text `json:"content"`
	RelatedType pgtype.Text `json:"related_type"`
	RelatedID   pgtype.Int4 `json:"related_id"`
	LinkUrl     pgtype.Text `json:"link_url"`
	UserID      int32       `json:"user_id"`
}

func (q *Queries) NotifyAudienceMembers(ctx context.Context, arg NotifyAudienceMembersParams) error {
	_, err := q.db.Exec(ctx, notifyAudienceMembers,
		arg.GameID,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.RelatedType,
		arg.RelatedID,
		arg.LinkUrl,
		arg.UserID,
	)
	return err
}

const notifyGM = `-- name: NotifyGM :exec
INSERT INTO notifications (user_id, game_id, type, title, content, related_type, related_id, link_url)
SELECT g.gm_user_id, $1, $2, $3, $4, $5, $6, $7
FROM games g
WHERE g.id = $1 AND g.gm_user_id != $8
`

type NotifyGMParams struct {
	GameID      pgtype.Int4 `json:"game_id"`
	Type        string      `json:"type"`
	Title       string      `json:"title"`
	Content     pgtype.Text `json:"content"`
	RelatedType pgtype.Text `json:"related_type"`
	RelatedID   pgtype.Int4 `json:"related_id"`
	LinkUrl     pgtype.Text `json:"link_url"`
	GmUserID    int32       `json:"gm_user_id"`
}

func (q *Queries) NotifyGM(ctx context.Context, arg NotifyGMParams) error {
	_, err := q.db.Exec(ctx, notifyGM,
		arg.GameID,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.RelatedType,
		arg.RelatedID,
		arg.LinkUrl,
		arg.GmUserID,
	)
	return err
}

const notifyGameParticipants = `-- name: NotifyGameParticipants :exec
INSERT INTO notifications (user_id, game_id, type, title, content, related_type, related_id, link_url)
SELECT gp.user_id, $1, $2, $3, $4, $5, $6, $7
FROM game_participants gp
WHERE gp.game_id = $1 AND gp.status = 'active' AND gp.user_id != $8
`

type NotifyGameParticipantsParams struct {
	GameID      pgtype.Int4 `json:"game_id"`
	Type        string      `json:"type"`
	Title       string      `json:"title"`
	Content     pgtype.Text `json:"content"`
	RelatedType pgtype.Text `json:"related_type"`
	RelatedID   pgtype.Int4 `json:"related_id"`
	LinkUrl     pgtype.Text `json:"link_url"`
	UserID      int32       `json:"user_id"`
}

// Helper queries for creating notifications
func (q *Queries) NotifyGameParticipants(ctx context.Context, arg NotifyGameParticipantsParams) error {
	_, err := q.db.Exec(ctx, notifyGameParticipants,
		arg.GameID,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.RelatedType,
		arg.RelatedID,
		arg.LinkUrl,
		arg.UserID,
	)
	return err
}
