// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activatePhase = `-- name: ActivatePhase :one
UPDATE game_phases
SET is_active = true, activated_at = NOW()
WHERE id = $1
RETURNING id, game_id, phase_type, phase_number, title, description, start_time, end_time, deadline, is_active, is_published, activated_at, created_at
`

func (q *Queries) ActivatePhase(ctx context.Context, id int32) (GamePhase, error) {
	row := q.db.QueryRow(ctx, activatePhase, id)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.IsPublished,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const canUserSubmitToPhase = `-- name: CanUserSubmitToPhase :one
SELECT
    CASE
        WHEN ph.phase_type != 'action' THEN false
        WHEN ph.deadline IS NOT NULL AND ph.deadline < NOW() THEN false
        WHEN NOT ph.is_active THEN false
        WHEN gp.role != 'player' THEN false
        ELSE true
    END as can_submit
FROM game_phases ph
JOIN games g ON ph.game_id = g.id
JOIN game_participants gp ON g.id = gp.game_id
WHERE ph.id = $1 AND gp.user_id = $2
`

type CanUserSubmitToPhaseParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) CanUserSubmitToPhase(ctx context.Context, arg CanUserSubmitToPhaseParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserSubmitToPhase, arg.ID, arg.UserID)
	var can_submit bool
	err := row.Scan(&can_submit)
	return can_submit, err
}

const clearStaleScheduledStartTimes = `-- name: ClearStaleScheduledStartTimes :exec
UPDATE game_phases
SET start_time = NULL
WHERE game_id = $1
  AND id != $2
  AND is_active = false
  AND start_time IS NOT NULL
  AND start_time <= NOW()
`

type ClearStaleScheduledStartTimesParams struct {
	GameID int32 `json:"game_id"`
	ID     int32 `json:"id"`
}

// Clears start_time on inactive phases in a game whose start_time is in the past,
// excluding the phase just activated. Called during phase activation to prevent
// the scheduler from overriding a manual activation with an overdue scheduled phase.
func (q *Queries) ClearStaleScheduledStartTimes(ctx context.Context, arg ClearStaleScheduledStartTimesParams) error {
	_, err := q.db.Exec(ctx, clearStaleScheduledStartTimes, arg.GameID, arg.ID)
	return err
}

const countActionResultsByPhase = `-- name: CountActionResultsByPhase :one
SELECT COUNT(*)
FROM action_results
WHERE phase_id = $1
`

// Count action results for a specific phase
// Used to check if phase can be deleted
func (q *Queries) CountActionResultsByPhase(ctx context.Context, phaseID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActionResultsByPhase, phaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActionSubmissionsByCharacter = `-- name: CountActionSubmissionsByCharacter :one
SELECT COUNT(*)
FROM action_submissions
WHERE character_id = $1
`

// Count action submissions for a specific character
// Used to check if character can be deleted
func (q *Queries) CountActionSubmissionsByCharacter(ctx context.Context, characterID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countActionSubmissionsByCharacter, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActionSubmissionsByPhase = `-- name: CountActionSubmissionsByPhase :one

SELECT COUNT(*)
FROM action_submissions
WHERE phase_id = $1
`

// Delete validation queries
// Count action submissions for a specific phase
// Used to check if phase can be deleted
func (q *Queries) CountActionSubmissionsByPhase(ctx context.Context, phaseID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActionSubmissionsByPhase, phaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllActionSubmissions = `-- name: CountAllActionSubmissions :one
SELECT COUNT(*)
FROM action_submissions acts
WHERE acts.game_id = $1
  AND (CASE WHEN $2 = 0 THEN TRUE ELSE acts.phase_id = $2 END)
`

type CountAllActionSubmissionsParams struct {
	GameID  int32       `json:"game_id"`
	PhaseID interface{} `json:"phase_id"`
}

// Count total action submissions for a game/phase (for pagination)
func (q *Queries) CountAllActionSubmissions(ctx context.Context, arg CountAllActionSubmissionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllActionSubmissions, arg.GameID, arg.PhaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesByPhase = `-- name: CountMessagesByPhase :one
SELECT COUNT(*)
FROM messages
WHERE phase_id = $1
  AND is_draft = false
`

// Count non-draft messages for a specific phase
// Used to check if phase can be deleted; draft posts are excluded (they're cleaned up separately)
func (q *Queries) CountMessagesByPhase(ctx context.Context, phaseID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesByPhase, phaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPollsByPhase = `-- name: CountPollsByPhase :one
SELECT COUNT(*)
FROM common_room_polls
WHERE phase_id = $1
`

// Count polls for a specific phase
// Used to check if phase can be deleted
func (q *Queries) CountPollsByPhase(ctx context.Context, phaseID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countPollsByPhase, phaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countThreadsByPhase = `-- name: CountThreadsByPhase :one
SELECT COUNT(*)
FROM threads
WHERE phase_id = $1
`

// Count common room threads for a specific phase
// Used to check if phase can be deleted
func (q *Queries) CountThreadsByPhase(ctx context.Context, phaseID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countThreadsByPhase, phaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActionResult = `-- name: CreateActionResult :one
INSERT INTO action_results (game_id, user_id, phase_id, character_id, action_submission_id, gm_user_id, content, is_published, sent_at, released_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        CASE WHEN $8 THEN NOW() ELSE NULL END,
        CASE WHEN $8 THEN NOW() ELSE NULL END)
RETURNING id, game_id, user_id, phase_id, character_id, action_submission_id, gm_user_id, content, is_published, sent_at, parent_result_id, reveal_delay_minutes, released_at
`

type CreateActionResultParams struct {
	GameID             int32       `json:"game_id"`
	UserID             int32       `json:"user_id"`
	PhaseID            int32       `json:"phase_id"`
	CharacterID        pgtype.Int4 `json:"character_id"`
	ActionSubmissionID pgtype.Int4 `json:"action_submission_id"`
	GmUserID           int32       `json:"gm_user_id"`
	Content            string      `json:"content"`
	IsPublished        pgtype.Bool `json:"is_published"`
}

// released_at tracks sent_at exactly: a result created already-published is
// visible immediately, and a draft is visible to nobody until publish sets both.
//
// This is load-bearing, not decorative. GetUserResults blanks the content of
// any row whose released_at is NULL, so a published row created without it
// would reach its recipient as an empty string — the same failure the
// migration's backfill fixed for historical rows.
//
// Creating a *staged* chain does not go through here; see CreateStagedResultPart,
// which leaves released_at NULL for the release worker to set.
func (q *Queries) CreateActionResult(ctx context.Context, arg CreateActionResultParams) (ActionResult, error) {
	row := q.db.QueryRow(ctx, createActionResult,
		arg.GameID,
		arg.UserID,
		arg.PhaseID,
		arg.CharacterID,
		arg.ActionSubmissionID,
		arg.GmUserID,
		arg.Content,
		arg.IsPublished,
	)
	var i ActionResult
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.ActionSubmissionID,
		&i.GmUserID,
		&i.Content,
		&i.IsPublished,
		&i.SentAt,
		&i.ParentResultID,
		&i.RevealDelayMinutes,
		&i.ReleasedAt,
	)
	return i, err
}

const createGamePhase = `-- name: CreateGamePhase :one
INSERT INTO game_phases (game_id, phase_type, phase_number, title, description, start_time, end_time, deadline)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, game_id, phase_type, phase_number, title, description, start_time, end_time, deadline, is_active, is_published, activated_at, created_at
`

type CreateGamePhaseParams struct {
	GameID      int32              `json:"game_id"`
	PhaseType   string             `json:"phase_type"`
	PhaseNumber int32              `json:"phase_number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) CreateGamePhase(ctx context.Context, arg CreateGamePhaseParams) (GamePhase, error) {
	row := q.db.QueryRow(ctx, createGamePhase,
		arg.GameID,
		arg.PhaseType,
		arg.PhaseNumber,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.Deadline,
	)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.IsPublished,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPhaseTransition = `-- name: CreatePhaseTransition :one

INSERT INTO phase_transitions (game_id, from_phase_id, to_phase_id, initiated_by, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, game_id, from_phase_id, to_phase_id, initiated_by, reason, created_at
`

type CreatePhaseTransitionParams struct {
	GameID      int32       `json:"game_id"`
	FromPhaseID pgtype.Int4 `json:"from_phase_id"`
	ToPhaseID   int32       `json:"to_phase_id"`
	InitiatedBy int32       `json:"initiated_by"`
	Reason      pgtype.Text `json:"reason"`
}

// Phase transition queries
func (q *Queries) CreatePhaseTransition(ctx context.Context, arg CreatePhaseTransitionParams) (PhaseTransition, error) {
	row := q.db.QueryRow(ctx, createPhaseTransition,
		arg.GameID,
		arg.FromPhaseID,
		arg.ToPhaseID,
		arg.InitiatedBy,
		arg.Reason,
	)
	var i PhaseTransition
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.FromPhaseID,
		&i.ToPhaseID,
		&i.InitiatedBy,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createStagedResultPart = `-- name: CreateStagedResultPart :one
INSERT INTO action_results (game_id, user_id, phase_id, character_id, action_submission_id, gm_user_id, content, is_published, sent_at, parent_result_id, reveal_delay_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        CASE WHEN $8 THEN NOW() ELSE NULL END,
        $9, $10)
RETURNING id, game_id, user_id, phase_id, character_id, action_submission_id, gm_user_id, content, is_published, sent_at, parent_result_id, reveal_delay_minutes, released_at
`

type CreateStagedResultPartParams struct {
	GameID             int32       `json:"game_id"`
	UserID             int32       `json:"user_id"`
	PhaseID            int32       `json:"phase_id"`
	CharacterID        pgtype.Int4 `json:"character_id"`
	ActionSubmissionID pgtype.Int4 `json:"action_submission_id"`
	GmUserID           int32       `json:"gm_user_id"`
	Content            string      `json:"content"`
	IsPublished        pgtype.Bool `json:"is_published"`
	ParentResultID     pgtype.Int4 `json:"parent_result_id"`
	RevealDelayMinutes pgtype.Int4 `json:"reveal_delay_minutes"`
}

// Append a non-head part to a chain. The head itself is an ordinary result and
// goes through CreateActionResult; only parts 2..N come through here.
//
// released_at is deliberately absent from the column list, so it defaults to
// NULL: a staged part is invisible to its recipient until the release worker
// sets it, even once is_published is TRUE. That NULL is the entire feature.
// Contrast CreateActionResult, which sets released_at alongside sent_at.
//
// sent_at still follows is_published, matching every other write path, so
// "when did the GM send this" and "when did the player get to see it" stay
// separate facts. For a staged part they genuinely differ.
//
// parent_result_id and reveal_delay_minutes are both non-NULL here by
// construction, which is what action_results_delay_requires_parent demands.
// Chain length, recipient consistency, and acyclicity are enforced in the
// service layer, since a CHECK constraint cannot walk the chain.
func (q *Queries) CreateStagedResultPart(ctx context.Context, arg CreateStagedResultPartParams) (ActionResult, error) {
	row := q.db.QueryRow(ctx, createStagedResultPart,
		arg.GameID,
		arg.UserID,
		arg.PhaseID,
		arg.CharacterID,
		arg.ActionSubmissionID,
		arg.GmUserID,
		arg.Content,
		arg.IsPublished,
		arg.ParentResultID,
		arg.RevealDelayMinutes,
	)
	var i ActionResult
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.ActionSubmissionID,
		&i.GmUserID,
		&i.Content,
		&i.IsPublished,
		&i.SentAt,
		&i.ParentResultID,
		&i.RevealDelayMinutes,
		&i.ReleasedAt,
	)
	return i, err
}

const deactivateAllGamePhases = `-- name: DeactivateAllGamePhases :exec
UPDATE game_phases
SET is_active = false
WHERE game_id = $1
`

func (q *Queries) DeactivateAllGamePhases(ctx context.Context, gameID int32) error {
	_, err := q.db.Exec(ctx, deactivateAllGamePhases, gameID)
	return err
}

const deactivatePhase = `-- name: DeactivatePhase :one
UPDATE game_phases
SET is_active = false, end_time = NOW()
WHERE id = $1
RETURNING id, game_id, phase_type, phase_number, title, description, start_time, end_time, deadline, is_active, is_published, activated_at, created_at
`

func (q *Queries) DeactivatePhase(ctx context.Context, id int32) (GamePhase, error) {
	row := q.db.QueryRow(ctx, deactivatePhase, id)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.IsPublished,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAction = `-- name: DeleteAction :exec
DELETE FROM action_submissions
WHERE game_id = $1 AND user_id = $2 AND phase_id = $3
`

type DeleteActionParams struct {
	GameID  int32 `json:"game_id"`
	UserID  int32 `json:"user_id"`
	PhaseID int32 `json:"phase_id"`
}

func (q *Queries) DeleteAction(ctx context.Context, arg DeleteActionParams) error {
	_, err := q.db.Exec(ctx, deleteAction, arg.GameID, arg.UserID, arg.PhaseID)
	return err
}

const deleteActionResult = `-- name: DeleteActionResult :exec
DELETE FROM action_results
WHERE id = $1 AND is_published = false
`

func (q *Queries) DeleteActionResult(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteActionResult, id)
	return err
}

const deleteActionSubmission = `-- name: DeleteActionSubmission :exec
DELETE FROM action_submissions
WHERE id = $1 AND user_id = $2
`

type DeleteActionSubmissionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteActionSubmission(ctx context.Context, arg DeleteActionSubmissionParams) error {
	_, err := q.db.Exec(ctx, deleteActionSubmission, arg.ID, arg.UserID)
	return err
}

const deletePhase = `-- name: DeletePhase :exec
DELETE FROM game_phases WHERE id = $1
`

func (q *Queries) DeletePhase(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePhase, id)
	return err
}

const deleteStagedPart = `-- name: DeleteStagedPart :exec
DELETE FROM action_results
WHERE id = $1 AND released_at IS NULL AND parent_result_id IS NOT NULL
`

// Cancel a staged part that has not yet been revealed.
//
// Guarded on released_at rather than is_published, which is the distinction
// DeleteActionResult cannot make: a scheduled part is *published* but not yet
// *released*, so DeleteActionResult's `is_published = false` matches nothing
// and would silently delete zero rows.
//
// ON DELETE CASCADE removes the parts scheduled after this one. A part whose
// parent is gone has no release time to measure its delay from and would never
// fire, so cascading is safer than orphaning.
func (q *Queries) DeleteStagedPart(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteStagedPart, id)
	return err
}

const getActionResult = `-- name: GetActionResult :one
SELECT id, game_id, user_id, phase_id, character_id, action_submission_id, gm_user_id, content, is_published, sent_at, parent_result_id, reveal_delay_minutes, released_at FROM action_results WHERE id = $1
`

func (q *Queries) GetActionResult(ctx context.Context, id int32) (ActionResult, error) {
	row := q.db.QueryRow(ctx, getActionResult, id)
	var i ActionResult
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.ActionSubmissionID,
		&i.GmUserID,
		&i.Content,
		&i.IsPublished,
		&i.SentAt,
		&i.ParentResultID,
		&i.RevealDelayMinutes,
		&i.ReleasedAt,
	)
	return i, err
}

const getActionSubmission = `-- name: GetActionSubmission :one
SELECT id, game_id, user_id, phase_id, character_id, content, submitted_at, updated_at FROM action_submissions WHERE id = $1
`

func (q *Queries) GetActionSubmission(ctx context.Context, id int32) (ActionSubmission, error) {
	row := q.db.QueryRow(ctx, getActionSubmission, id)
	var i ActionSubmission
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.Content,
		&i.SubmittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePhase = `-- name: GetActivePhase :one
SELECT id, game_id, phase_type, phase_number, title, description, start_time, end_time, deadline, is_active, is_published, activated_at, created_at FROM game_phases
WHERE game_id = $1 AND is_active = true
`

func (q *Queries) GetActivePhase(ctx context.Context, gameID int32) (GamePhase, error) {
	row := q.db.QueryRow(ctx, getActivePhase, gameID)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.IsPublished,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePhaseActivatedAt = `-- name: GetActivePhaseActivatedAt :one
SELECT activated_at FROM game_phases
WHERE game_id = $1 AND is_active = true
`

// Returns the activated_at timestamp of the currently active phase for a game.
// Used by the scheduler to detect if a manual activation superseded a scheduled one.
func (q *Queries) GetActivePhaseActivatedAt(ctx context.Context, gameID int32) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getActivePhaseActivatedAt, gameID)
	var activated_at pgtype.Timestamptz
	err := row.Scan(&activated_at)
	return activated_at, err
}

const getChainTailForAppend = `-- name: GetChainTailForAppend :one
WITH RECURSIVE head AS (
    SELECT anchor.id, anchor.parent_result_id
    FROM action_results anchor
    WHERE anchor.id = $1
    UNION ALL
    SELECT p.id, p.parent_result_id
    FROM action_results p
    JOIN head h ON h.parent_result_id = p.id
),
chain AS (
    SELECT r.id, r.game_id, r.user_id, r.phase_id, r.character_id, r.action_submission_id, r.gm_user_id, r.content, r.is_published, r.sent_at, r.parent_result_id, r.reveal_delay_minutes, r.released_at, 1 AS part_number
    FROM action_results r
    WHERE r.id = (SELECT id FROM head WHERE parent_result_id IS NULL)
    UNION ALL
    SELECT child.id, child.game_id, child.user_id, child.phase_id, child.character_id, child.action_submission_id, child.gm_user_id, child.content, child.is_published, child.sent_at, child.parent_result_id, child.reveal_delay_minutes, child.released_at, c.part_number + 1
    FROM action_results child
    JOIN chain c ON child.parent_result_id = c.id
)
SELECT c.id, c.game_id, c.user_id, c.phase_id, c.character_id, c.action_submission_id, c.gm_user_id, c.content, c.is_published, c.sent_at, c.parent_result_id, c.reveal_delay_minutes, c.released_at, c.part_number,
       (SELECT COUNT(*) FROM chain) AS part_count,
       (SELECT bool_or(is_published) FROM chain) AS any_published
FROM chain c
ORDER BY c.part_number DESC
LIMIT 1
`

type GetChainTailForAppendRow struct {
	ID                 int32              `json:"id"`
	GameID             int32              `json:"game_id"`
	UserID             int32              `json:"user_id"`
	PhaseID            int32              `json:"phase_id"`
	CharacterID        pgtype.Int4        `json:"character_id"`
	ActionSubmissionID pgtype.Int4        `json:"action_submission_id"`
	GmUserID           int32              `json:"gm_user_id"`
	Content            string             `json:"content"`
	IsPublished        pgtype.Bool        `json:"is_published"`
	SentAt             pgtype.Timestamptz `json:"sent_at"`
	ParentResultID     pgtype.Int4        `json:"parent_result_id"`
	RevealDelayMinutes pgtype.Int4        `json:"reveal_delay_minutes"`
	ReleasedAt         pgtype.Timestamptz `json:"released_at"`
	PartNumber         int32              `json:"part_number"`
	PartCount          int64              `json:"part_count"`
	AnyPublished       bool               `json:"any_published"`
}

// The last part of the chain containing $1, plus whether any part of that chain
// is published, for appending a new part to a draft chain.
//
// Returns the tail rather than requiring the caller to hold it, so a GM editing
// any part of a chain can append to it. A result with no parent and no children
// is a chain of one and comes back as its own tail — which is how an ordinary
// draft becomes a staged chain without a separate conversion path.
//
// any_published is computed over the whole chain, not just the tail: parts are
// published together, but checking every part means a partially published chain
// (which should not exist) fails closed rather than silently accepting an
// append.
func (q *Queries) GetChainTailForAppend(ctx context.Context, id int32) (GetChainTailForAppendRow, error) {
	row := q.db.QueryRow(ctx, getChainTailForAppend, id)
	var i GetChainTailForAppendRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.ActionSubmissionID,
		&i.GmUserID,
		&i.Content,
		&i.IsPublished,
		&i.SentAt,
		&i.ParentResultID,
		&i.RevealDelayMinutes,
		&i.ReleasedAt,
		&i.PartNumber,
		&i.PartCount,
		&i.AnyPublished,
	)
	return i, err
}

const getDueStagedParts = `-- name: GetDueStagedParts :many

SELECT r.id, r.game_id, r.user_id, r.phase_id, r.character_id, r.gm_user_id,
       r.parent_result_id, r.reveal_delay_minutes
FROM action_results r
JOIN action_results parent ON r.parent_result_id = parent.id
WHERE r.is_published = TRUE
  AND r.released_at IS NULL
  AND parent.released_at IS NOT NULL
  AND parent.released_at + make_interval(mins => r.reveal_delay_minutes) <= NOW()
ORDER BY r.id
`

type GetDueStagedPartsRow struct {
	ID                 int32       `json:"id"`
	GameID             int32       `json:"game_id"`
	UserID             int32       `json:"user_id"`
	PhaseID            int32       `json:"phase_id"`
	CharacterID        pgtype.Int4 `json:"character_id"`
	GmUserID           int32       `json:"gm_user_id"`
	ParentResultID     pgtype.Int4 `json:"parent_result_id"`
	RevealDelayMinutes pgtype.Int4 `json:"reveal_delay_minutes"`
}

// Staged result reveals -----------------------------------------------------
//
// A chain is a linked list: each part points at its predecessor via
// parent_result_id, and reveal_delay_minutes is measured from the moment that
// predecessor became visible. See .claude/planning/staged-result-reveals.md.
// Parts whose wait has elapsed and which the release worker should now reveal.
//
// Due-ness is computed entirely in SQL from the parent's release time, which is
// what makes this restart-safe: a part due while the process was down simply
// comes back on the next tick, and there is no in-memory timer to lose or
// double-fire.
//
// Deliberately does NOT join game_phases or games. A chain owns its own clock —
// phase advancement and game completion do not force, delay, or cancel a
// release. Adding a phase or state filter here would break that; see "Chain
// Independence" in the planning doc.
// Oldest chains first, and parents before children within a chain: id ordering
// means a chain inserted in part order releases in part order even if several
// parts come due in the same tick.
func (q *Queries) GetDueStagedParts(ctx context.Context) ([]GetDueStagedPartsRow, error) {
	rows, err := q.db.Query(ctx, getDueStagedParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueStagedPartsRow
	for rows.Next() {
		var i GetDueStagedPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.GmUserID,
			&i.ParentResultID,
			&i.RevealDelayMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameActions = `-- name: GetGameActions :many
SELECT acts.id, acts.game_id, acts.user_id, acts.phase_id, acts.character_id, acts.content, acts.submitted_at, acts.updated_at, u.username, c.name as character_name, gp.phase_type, gp.phase_number
FROM action_submissions acts
JOIN users u ON acts.user_id = u.id
JOIN game_phases gp ON acts.phase_id = gp.id
LEFT JOIN characters c ON acts.character_id = c.id
WHERE acts.game_id = $1
ORDER BY gp.phase_number, acts.submitted_at
`

type GetGameActionsRow struct {
	ID            int32              `json:"id"`
	GameID        int32              `json:"game_id"`
	UserID        int32              `json:"user_id"`
	PhaseID       int32              `json:"phase_id"`
	CharacterID   pgtype.Int4        `json:"character_id"`
	Content       string             `json:"content"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Username      string             `json:"username"`
	CharacterName pgtype.Text        `json:"character_name"`
	PhaseType     string             `json:"phase_type"`
	PhaseNumber   int32              `json:"phase_number"`
}

func (q *Queries) GetGameActions(ctx context.Context, gameID int32) ([]GetGameActionsRow, error) {
	rows, err := q.db.Query(ctx, getGameActions, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameActionsRow
	for rows.Next() {
		var i GetGameActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.Content,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.CharacterName,
			&i.PhaseType,
			&i.PhaseNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamePhases = `-- name: GetGamePhases :many
SELECT id, game_id, phase_type, phase_number, title, description, start_time, end_time, deadline, is_active, is_published, activated_at, created_at FROM game_phases
WHERE game_id = $1
ORDER BY phase_number
`

func (q *Queries) GetGamePhases(ctx context.Context, gameID int32) ([]GamePhase, error) {
	rows, err := q.db.Query(ctx, getGamePhases, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePhase
	for rows.Next() {
		var i GamePhase
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseType,
			&i.PhaseNumber,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.Deadline,
			&i.IsActive,
			&i.IsPublished,
			&i.ActivatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameResults = `-- name: GetGameResults :many
WITH RECURSIVE chain AS (
    -- Chain positions for this game's staged results. Same shape as the CTE in
    -- GetUserResults; see the longer note there for why it is scoped to the
    -- game rather than to the outer query's filter.
    SELECT h.id, h.id AS head_id, 1 AS part_number,
           h.released_at AS parent_released_at, h.reveal_delay_minutes
    FROM action_results h
    WHERE h.game_id = $1
      AND h.parent_result_id IS NULL
      AND EXISTS (SELECT 1 FROM action_results k WHERE k.parent_result_id = h.id)
    UNION ALL
    SELECT child.id, c.head_id, c.part_number + 1,
           parent.released_at, child.reveal_delay_minutes
    FROM action_results child
    JOIN chain c ON child.parent_result_id = c.id
    JOIN action_results parent ON child.parent_result_id = parent.id
),
chain_position AS (
    SELECT id, part_number,
           COUNT(*) OVER (PARTITION BY head_id) AS part_count,
           (CASE
               WHEN parent_released_at IS NOT NULL AND reveal_delay_minutes IS NOT NULL
               THEN parent_released_at + make_interval(mins => reveal_delay_minutes)
           END)::timestamptz AS unlocks_at
    FROM chain
)
SELECT results.id, results.game_id, results.user_id, results.phase_id, results.character_id, results.action_submission_id, results.gm_user_id, results.content, results.is_published, results.sent_at, results.parent_result_id, results.reveal_delay_minutes, results.released_at, u.username, gp.phase_type, gp.phase_number,
       c.name as character_name,
       cp.part_number, cp.part_count, cp.unlocks_at
FROM action_results results
JOIN users u ON results.user_id = u.id
JOIN game_phases gp ON results.phase_id = gp.id
LEFT JOIN characters c ON results.character_id = c.id
LEFT JOIN chain_position cp ON cp.id = results.id
WHERE results.game_id = $1
ORDER BY gp.phase_number, results.id
`

type GetGameResultsRow struct {
	ID                 int32              `json:"id"`
	GameID             int32              `json:"game_id"`
	UserID             int32              `json:"user_id"`
	PhaseID            int32              `json:"phase_id"`
	CharacterID        pgtype.Int4        `json:"character_id"`
	ActionSubmissionID pgtype.Int4        `json:"action_submission_id"`
	GmUserID           int32              `json:"gm_user_id"`
	Content            string             `json:"content"`
	IsPublished        pgtype.Bool        `json:"is_published"`
	SentAt             pgtype.Timestamptz `json:"sent_at"`
	ParentResultID     pgtype.Int4        `json:"parent_result_id"`
	RevealDelayMinutes pgtype.Int4        `json:"reveal_delay_minutes"`
	ReleasedAt         pgtype.Timestamptz `json:"released_at"`
	Username           string             `json:"username"`
	PhaseType          string             `json:"phase_type"`
	PhaseNumber        int32              `json:"phase_number"`
	CharacterName      pgtype.Text        `json:"character_name"`
	PartNumber         pgtype.Int4        `json:"part_number"`
	PartCount          pgtype.Int8        `json:"part_count"`
	UnlocksAt          pgtype.Timestamptz `json:"unlocks_at"`
}

// Oldest first within a phase, matching GetUserResults so the History tab reads
// chronologically for every role. The GM and audience path returns the whole cast
// (drafts included) while players get only their own published rows, but the two
// are read side by side in the same view and disagreeing on order made the same
// phase look different depending on who was logged in.
//
// id (SERIAL) rather than sent_at: this query returns unpublished drafts, whose
// sent_at is NULL until publish, so ordering by it would leave every draft tied
// and arbitrary. A GM writes results in the order they mean them to be read, so
// creation order is the chronological order.
//
// GameResultsManager (the GM composing view) shares this query but wants newest
// first, so it reverses client-side; see the comment there.
func (q *Queries) GetGameResults(ctx context.Context, gameID int32) ([]GetGameResultsRow, error) {
	rows, err := q.db.Query(ctx, getGameResults, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameResultsRow
	for rows.Next() {
		var i GetGameResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.ActionSubmissionID,
			&i.GmUserID,
			&i.Content,
			&i.IsPublished,
			&i.SentAt,
			&i.ParentResultID,
			&i.RevealDelayMinutes,
			&i.ReleasedAt,
			&i.Username,
			&i.PhaseType,
			&i.PhaseNumber,
			&i.CharacterName,
			&i.PartNumber,
			&i.PartCount,
			&i.UnlocksAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestPhaseNumber = `-- name: GetLatestPhaseNumber :one
SELECT COALESCE(MAX(phase_number), 0)
FROM game_phases
WHERE game_id = $1
`

func (q *Queries) GetLatestPhaseNumber(ctx context.Context, gameID int32) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLatestPhaseNumber, gameID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getPhase = `-- name: GetPhase :one
SELECT id, game_id, phase_type, phase_number, title, description, start_time, end_time, deadline, is_active, is_published, activated_at, created_at FROM game_phases WHERE id = $1
`

func (q *Queries) GetPhase(ctx context.Context, id int32) (GamePhase, error) {
	row := q.db.QueryRow(ctx, getPhase, id)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.IsPublished,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPhaseActions = `-- name: GetPhaseActions :many
SELECT acts.id, acts.game_id, acts.user_id, acts.phase_id, acts.character_id, acts.content, acts.submitted_at, acts.updated_at, u.username, c.name as character_name
FROM action_submissions acts
JOIN users u ON acts.user_id = u.id
LEFT JOIN characters c ON acts.character_id = c.id
WHERE acts.phase_id = $1
ORDER BY acts.submitted_at
`

type GetPhaseActionsRow struct {
	ID            int32              `json:"id"`
	GameID        int32              `json:"game_id"`
	UserID        int32              `json:"user_id"`
	PhaseID       int32              `json:"phase_id"`
	CharacterID   pgtype.Int4        `json:"character_id"`
	Content       string             `json:"content"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Username      string             `json:"username"`
	CharacterName pgtype.Text        `json:"character_name"`
}

func (q *Queries) GetPhaseActions(ctx context.Context, phaseID int32) ([]GetPhaseActionsRow, error) {
	rows, err := q.db.Query(ctx, getPhaseActions, phaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhaseActionsRow
	for rows.Next() {
		var i GetPhaseActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.Content,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhaseResults = `-- name: GetPhaseResults :many
SELECT results.id, results.game_id, results.user_id, results.phase_id, results.character_id, results.action_submission_id, results.gm_user_id, results.content, results.is_published, results.sent_at, results.parent_result_id, results.reveal_delay_minutes, results.released_at, u.username, gm.username as gm_username,
       c.name as character_name
FROM action_results results
JOIN users u ON results.user_id = u.id
JOIN users gm ON results.gm_user_id = gm.id
LEFT JOIN characters c ON results.character_id = c.id
WHERE results.phase_id = $1
ORDER BY results.id DESC
`

type GetPhaseResultsRow struct {
	ID                 int32              `json:"id"`
	GameID             int32              `json:"game_id"`
	UserID             int32              `json:"user_id"`
	PhaseID            int32              `json:"phase_id"`
	CharacterID        pgtype.Int4        `json:"character_id"`
	ActionSubmissionID pgtype.Int4        `json:"action_submission_id"`
	GmUserID           int32              `json:"gm_user_id"`
	Content            string             `json:"content"`
	IsPublished        pgtype.Bool        `json:"is_published"`
	SentAt             pgtype.Timestamptz `json:"sent_at"`
	ParentResultID     pgtype.Int4        `json:"parent_result_id"`
	RevealDelayMinutes pgtype.Int4        `json:"reveal_delay_minutes"`
	ReleasedAt         pgtype.Timestamptz `json:"released_at"`
	Username           string             `json:"username"`
	GmUsername         string             `json:"gm_username"`
	CharacterName      pgtype.Text        `json:"character_name"`
}

// Newest first. sent_at cannot order these: it is NULL until a result is
// published, so drafts would all tie. Note this disagrees with GetGameResults,
// which sorts ascending for the History tab — this query currently has no
// callers, so there is nothing to be consistent with. Match GetGameResults if it
// ever gets wired to a read path, or delete it.
func (q *Queries) GetPhaseResults(ctx context.Context, phaseID int32) ([]GetPhaseResultsRow, error) {
	rows, err := q.db.Query(ctx, getPhaseResults, phaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhaseResultsRow
	for rows.Next() {
		var i GetPhaseResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.ActionSubmissionID,
			&i.GmUserID,
			&i.Content,
			&i.IsPublished,
			&i.SentAt,
			&i.ParentResultID,
			&i.RevealDelayMinutes,
			&i.ReleasedAt,
			&i.Username,
			&i.GmUsername,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhaseSubmissions = `-- name: GetPhaseSubmissions :many
SELECT acts.id, acts.game_id, acts.user_id, acts.phase_id, acts.character_id, acts.content, acts.submitted_at, acts.updated_at, u.username, c.name as character_name
FROM action_submissions acts
JOIN users u ON acts.user_id = u.id
LEFT JOIN characters c ON acts.character_id = c.id
WHERE acts.phase_id = $1
ORDER BY acts.submitted_at
`

type GetPhaseSubmissionsRow struct {
	ID            int32              `json:"id"`
	GameID        int32              `json:"game_id"`
	UserID        int32              `json:"user_id"`
	PhaseID       int32              `json:"phase_id"`
	CharacterID   pgtype.Int4        `json:"character_id"`
	Content       string             `json:"content"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Username      string             `json:"username"`
	CharacterName pgtype.Text        `json:"character_name"`
}

func (q *Queries) GetPhaseSubmissions(ctx context.Context, phaseID int32) ([]GetPhaseSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, getPhaseSubmissions, phaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhaseSubmissionsRow
	for rows.Next() {
		var i GetPhaseSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.Content,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhaseTransitions = `-- name: GetPhaseTransitions :many
SELECT pt.id, pt.game_id, pt.from_phase_id, pt.to_phase_id, pt.initiated_by, pt.reason, pt.created_at,
       from_phase.phase_type as from_phase_type, from_phase.phase_number as from_phase_number,
       to_phase.phase_type as to_phase_type, to_phase.phase_number as to_phase_number,
       u.username as initiated_by_username
FROM phase_transitions pt
LEFT JOIN game_phases from_phase ON pt.from_phase_id = from_phase.id
JOIN game_phases to_phase ON pt.to_phase_id = to_phase.id
JOIN users u ON pt.initiated_by = u.id
WHERE pt.game_id = $1
ORDER BY pt.created_at
`

type GetPhaseTransitionsRow struct {
	ID                  int32              `json:"id"`
	GameID              int32              `json:"game_id"`
	FromPhaseID         pgtype.Int4        `json:"from_phase_id"`
	ToPhaseID           int32              `json:"to_phase_id"`
	InitiatedBy         int32              `json:"initiated_by"`
	Reason              pgtype.Text        `json:"reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	FromPhaseType       pgtype.Text        `json:"from_phase_type"`
	FromPhaseNumber     pgtype.Int4        `json:"from_phase_number"`
	ToPhaseType         string             `json:"to_phase_type"`
	ToPhaseNumber       int32              `json:"to_phase_number"`
	InitiatedByUsername string             `json:"initiated_by_username"`
}

func (q *Queries) GetPhaseTransitions(ctx context.Context, gameID int32) ([]GetPhaseTransitionsRow, error) {
	rows, err := q.db.Query(ctx, getPhaseTransitions, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhaseTransitionsRow
	for rows.Next() {
		var i GetPhaseTransitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.FromPhaseID,
			&i.ToPhaseID,
			&i.InitiatedBy,
			&i.Reason,
			&i.CreatedAt,
			&i.FromPhaseType,
			&i.FromPhaseNumber,
			&i.ToPhaseType,
			&i.ToPhaseNumber,
			&i.InitiatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResultChain = `-- name: GetResultChain :many
WITH RECURSIVE head AS (
    -- Climb from the given result to the chain head.
    SELECT anchor.id, anchor.parent_result_id
    FROM action_results anchor
    WHERE anchor.id = $1
    UNION ALL
    SELECT p.id, p.parent_result_id
    FROM action_results p
    JOIN head h ON h.parent_result_id = p.id
),
chain AS (
    -- Descend from the head, numbering as we go.
    SELECT r.id, r.game_id, r.user_id, r.phase_id, r.character_id, r.action_submission_id, r.gm_user_id, r.content, r.is_published, r.sent_at, r.parent_result_id, r.reveal_delay_minutes, r.released_at, 1 AS part_number
    FROM action_results r
    WHERE r.id = (SELECT id FROM head WHERE parent_result_id IS NULL)
    UNION ALL
    SELECT child.id, child.game_id, child.user_id, child.phase_id, child.character_id, child.action_submission_id, child.gm_user_id, child.content, child.is_published, child.sent_at, child.parent_result_id, child.reveal_delay_minutes, child.released_at, c.part_number + 1
    FROM action_results child
    JOIN chain c ON child.parent_result_id = c.id
)
SELECT c.id, c.game_id, c.user_id, c.phase_id, c.character_id, c.action_submission_id, c.gm_user_id, c.content, c.is_published, c.sent_at, c.parent_result_id, c.reveal_delay_minutes, c.released_at, c.part_number, (SELECT COUNT(*) FROM chain) AS part_count
FROM chain c
ORDER BY c.part_number
`

type GetResultChainRow struct {
	ID                 int32              `json:"id"`
	GameID             int32              `json:"game_id"`
	UserID             int32              `json:"user_id"`
	PhaseID            int32              `json:"phase_id"`
	CharacterID        pgtype.Int4        `json:"character_id"`
	ActionSubmissionID pgtype.Int4        `json:"action_submission_id"`
	GmUserID           int32              `json:"gm_user_id"`
	Content            string             `json:"content"`
	IsPublished        pgtype.Bool        `json:"is_published"`
	SentAt             pgtype.Timestamptz `json:"sent_at"`
	ParentResultID     pgtype.Int4        `json:"parent_result_id"`
	RevealDelayMinutes pgtype.Int4        `json:"reveal_delay_minutes"`
	ReleasedAt         pgtype.Timestamptz `json:"released_at"`
	PartNumber         int32              `json:"part_number"`
	PartCount          int64              `json:"part_count"`
}

// The whole chain containing a given result, with 1-based part indices, walked
// from the head. Used for "Part 2 of 3" labelling and for the GM's schedule
// view.
//
// Takes any member of the chain: the anchor CTE climbs to the head first, so
// callers do not need to know whether they hold the head.
func (q *Queries) GetResultChain(ctx context.Context, id int32) ([]GetResultChainRow, error) {
	rows, err := q.db.Query(ctx, getResultChain, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResultChainRow
	for rows.Next() {
		var i GetResultChainRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.ActionSubmissionID,
			&i.GmUserID,
			&i.Content,
			&i.IsPublished,
			&i.SentAt,
			&i.ParentResultID,
			&i.RevealDelayMinutes,
			&i.ReleasedAt,
			&i.PartNumber,
			&i.PartCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledPhasesToActivate = `-- name: GetScheduledPhasesToActivate :many
SELECT gp.id, gp.game_id, gp.phase_type, gp.phase_number, gp.title, gp.description, gp.start_time, gp.end_time, gp.deadline, gp.is_active, gp.is_published, gp.activated_at, gp.created_at
FROM game_phases gp
JOIN games g ON gp.game_id = g.id
WHERE gp.is_active = false
  AND gp.start_time IS NOT NULL
  AND gp.start_time <= NOW()
  AND gp.end_time IS NULL
  AND g.state = 'in_progress'
ORDER BY gp.start_time ASC
`

// Returns inactive phases whose start_time has arrived, for games that are in_progress.
// Excludes phases with end_time set — those are completed/historical and should never be re-activated.
// Used by the scheduler to auto-activate phases.
func (q *Queries) GetScheduledPhasesToActivate(ctx context.Context) ([]GamePhase, error) {
	rows, err := q.db.Query(ctx, getScheduledPhasesToActivate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePhase
	for rows.Next() {
		var i GamePhase
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseType,
			&i.PhaseNumber,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.Deadline,
			&i.IsActive,
			&i.IsPublished,
			&i.ActivatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmissionStatsForPhase = `-- name: GetSubmissionStatsForPhase :one
SELECT
    $1::int as phase_id,
    COUNT(DISTINCT gp.user_id) as total_players,
    COUNT(DISTINCT acts.user_id) as submitted_count,
    COALESCE(
        ROUND(
            (COUNT(DISTINCT acts.user_id) * 100.0) /
            NULLIF(COUNT(DISTINCT gp.user_id), 0),
            2
        ),
        0
    ) as submission_rate,
    MAX(acts.submitted_at) as latest_submission
FROM game_participants gp
JOIN game_phases ph ON gp.game_id = ph.game_id
LEFT JOIN action_submissions acts ON gp.user_id = acts.user_id AND acts.phase_id = ph.id
WHERE ph.id = $1 AND gp.role = 'player'
`

type GetSubmissionStatsForPhaseRow struct {
	PhaseID          int32       `json:"phase_id"`
	TotalPlayers     int64       `json:"total_players"`
	SubmittedCount   int64       `json:"submitted_count"`
	SubmissionRate   interface{} `json:"submission_rate"`
	LatestSubmission interface{} `json:"latest_submission"`
}

func (q *Queries) GetSubmissionStatsForPhase(ctx context.Context, dollar_1 int32) (GetSubmissionStatsForPhaseRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionStatsForPhase, dollar_1)
	var i GetSubmissionStatsForPhaseRow
	err := row.Scan(
		&i.PhaseID,
		&i.TotalPlayers,
		&i.SubmittedCount,
		&i.SubmissionRate,
		&i.LatestSubmission,
	)
	return i, err
}

const getUnpublishedResultIDs = `-- name: GetUnpublishedResultIDs :many
SELECT id
FROM action_results
WHERE phase_id = $1 AND is_published = false AND parent_result_id IS NULL
`

// Work list for PublishAllPhaseResults. Chain heads only, for the same reason
// as GetUnpublishedResultsCount — and here it is a correctness matter, not just
// a cosmetic one: publishSingleResultWithDrafts publishes the entire chain and
// notifies the recipient, so including followers would publish each chain N
// times and send the player N notifications for one scene.
func (q *Queries) GetUnpublishedResultIDs(ctx context.Context, phaseID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getUnpublishedResultIDs, phaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnpublishedResultsCount = `-- name: GetUnpublishedResultsCount :one
SELECT COUNT(*) as count
FROM action_results
WHERE phase_id = $1 AND is_published = false AND parent_result_id IS NULL
`

// How many results the GM's "publish all" would send out.
//
// Chain heads only. Publishing a head publishes its whole chain (see
// PublishActionResult), so counting followers separately would tell the GM
// they have 4 results to publish when they have one 4-part scene.
func (q *Queries) GetUnpublishedResultsCount(ctx context.Context, phaseID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getUnpublishedResultsCount, phaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserAction = `-- name: GetUserAction :one
SELECT acts.id, acts.game_id, acts.user_id, acts.phase_id, acts.character_id, acts.content, acts.submitted_at, acts.updated_at, c.name as character_name
FROM action_submissions acts
LEFT JOIN characters c ON acts.character_id = c.id
WHERE acts.game_id = $1 AND acts.user_id = $2 AND acts.phase_id = $3
`

type GetUserActionParams struct {
	GameID  int32 `json:"game_id"`
	UserID  int32 `json:"user_id"`
	PhaseID int32 `json:"phase_id"`
}

type GetUserActionRow struct {
	ID            int32              `json:"id"`
	GameID        int32              `json:"game_id"`
	UserID        int32              `json:"user_id"`
	PhaseID       int32              `json:"phase_id"`
	CharacterID   pgtype.Int4        `json:"character_id"`
	Content       string             `json:"content"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CharacterName pgtype.Text        `json:"character_name"`
}

func (q *Queries) GetUserAction(ctx context.Context, arg GetUserActionParams) (GetUserActionRow, error) {
	row := q.db.QueryRow(ctx, getUserAction, arg.GameID, arg.UserID, arg.PhaseID)
	var i GetUserActionRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.Content,
		&i.SubmittedAt,
		&i.UpdatedAt,
		&i.CharacterName,
	)
	return i, err
}

const getUserActions = `-- name: GetUserActions :many
SELECT acts.id, acts.game_id, acts.user_id, acts.phase_id, acts.character_id, acts.content, acts.submitted_at, acts.updated_at, gp.phase_type, gp.phase_number, c.name as character_name
FROM action_submissions acts
JOIN game_phases gp ON acts.phase_id = gp.id
LEFT JOIN characters c ON acts.character_id = c.id
WHERE acts.game_id = $1 AND acts.user_id = $2
ORDER BY gp.phase_number DESC
`

type GetUserActionsParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

type GetUserActionsRow struct {
	ID            int32              `json:"id"`
	GameID        int32              `json:"game_id"`
	UserID        int32              `json:"user_id"`
	PhaseID       int32              `json:"phase_id"`
	CharacterID   pgtype.Int4        `json:"character_id"`
	Content       string             `json:"content"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	PhaseType     string             `json:"phase_type"`
	PhaseNumber   int32              `json:"phase_number"`
	CharacterName pgtype.Text        `json:"character_name"`
}

func (q *Queries) GetUserActions(ctx context.Context, arg GetUserActionsParams) ([]GetUserActionsRow, error) {
	rows, err := q.db.Query(ctx, getUserActions, arg.GameID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserActionsRow
	for rows.Next() {
		var i GetUserActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.Content,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.PhaseType,
			&i.PhaseNumber,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPhaseResults = `-- name: GetUserPhaseResults :many
SELECT id, game_id, user_id, phase_id, character_id, action_submission_id, gm_user_id, content, is_published, sent_at, parent_result_id, reveal_delay_minutes, released_at FROM action_results
WHERE phase_id = $1 AND user_id = $2
ORDER BY id DESC
`

type GetUserPhaseResultsParams struct {
	PhaseID int32 `json:"phase_id"`
	UserID  int32 `json:"user_id"`
}

// ⚠️ Despite the name, this is NOT a player-facing read. It returns drafts and
// unreleased staged parts, and it has no non-test callers today — it feeds the
// GM composing view, which is why it sorts newest-first.
//
// If you wire this to anything a player sees, add
// `AND is_published = true AND released_at IS NOT NULL` first, or use
// GetUserResults, which is the gated player path. Returning an unreleased
// staged part here would hand the player the content of a reveal that has not
// happened yet.
// See GetGameResults: sent_at is NULL for drafts, so it cannot order them.
func (q *Queries) GetUserPhaseResults(ctx context.Context, arg GetUserPhaseResultsParams) ([]ActionResult, error) {
	rows, err := q.db.Query(ctx, getUserPhaseResults, arg.PhaseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionResult
	for rows.Next() {
		var i ActionResult
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.ActionSubmissionID,
			&i.GmUserID,
			&i.Content,
			&i.IsPublished,
			&i.SentAt,
			&i.ParentResultID,
			&i.RevealDelayMinutes,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPhaseSubmission = `-- name: GetUserPhaseSubmission :one
SELECT id, game_id, user_id, phase_id, character_id, content, submitted_at, updated_at FROM action_submissions
WHERE phase_id = $1 AND user_id = $2
`

type GetUserPhaseSubmissionParams struct {
	PhaseID int32 `json:"phase_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) GetUserPhaseSubmission(ctx context.Context, arg GetUserPhaseSubmissionParams) (ActionSubmission, error) {
	row := q.db.QueryRow(ctx, getUserPhaseSubmission, arg.PhaseID, arg.UserID)
	var i ActionSubmission
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.Content,
		&i.SubmittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserResults = `-- name: GetUserResults :many
WITH RECURSIVE chain AS (
    -- Chain positions for every staged result in this game, computed in one
    -- pass. Seeded from chain heads — a row with children but no parent — so
    -- ordinary single-part results never enter the CTE and cost nothing.
    --
    -- Deliberately scoped to game_id ONLY, not to the user or the released_at
    -- gate the outer query applies. The parts this CTE counts are precisely the
    -- ones the WHERE clause below hides: a player holding part 1 of 3 must
    -- still be told the chain has three parts, or the UI cannot say "Part 1 of
    -- 3" and the pending placeholder has nothing to render. Narrowing this CTE
    -- to match the outer filter would make part_count mean "parts you can
    -- already see", which is always 1 for the part that matters.
    SELECT h.id, h.id AS head_id, 1 AS part_number,
           h.released_at AS parent_released_at, h.reveal_delay_minutes
    FROM action_results h
    WHERE h.game_id = $1
      AND h.parent_result_id IS NULL
      AND EXISTS (SELECT 1 FROM action_results k WHERE k.parent_result_id = h.id)
    UNION ALL
    SELECT child.id, c.head_id, c.part_number + 1,
           parent.released_at, child.reveal_delay_minutes
    FROM action_results child
    JOIN chain c ON child.parent_result_id = c.id
    JOIN action_results parent ON child.parent_result_id = parent.id
),
chain_position AS (
    SELECT id, part_number,
           COUNT(*) OVER (PARTITION BY head_id) AS part_count,
           -- When this part becomes visible: the parent's release plus this
           -- part's delay. NULL when the parent is itself unreleased, because
           -- the time is then genuinely unknown — an estimate would be wrong
           -- the moment any upstream part slips. The UI shows a countdown only
           -- for the one pending part that has a known unlock time.
           (CASE
               WHEN parent_released_at IS NOT NULL AND reveal_delay_minutes IS NOT NULL
               THEN parent_released_at + make_interval(mins => reveal_delay_minutes)
           END)::timestamptz AS unlocks_at
    FROM chain
)
SELECT results.id, results.game_id, results.user_id, results.phase_id,
       results.character_id, results.action_submission_id, results.gm_user_id,
       -- THE gate the feature rests on. An unreleased part's text must never
       -- reach the client: a player with devtools would defeat the whole
       -- feature. Blanked in SQL so no Go code path can leak it by accident.
       --
       -- Ordinary unstaged results and every pre-feature row have released_at
       -- set at publish time (backfilled by migration 20260812214302), so this
       -- CASE is a no-op for everything except pending staged parts.
       --
       -- Empty string rather than NULL: content is NOT NULL on the table and
       -- every existing client reads it as a string. A locked part is
       -- identified by released_at being null, not by probing the content.
       -- The ::text cast is required, not cosmetic: without it sqlc cannot
       -- infer the CASE's type and generates ` + "`" + `Content interface{}` + "`" + `, which
       -- erases compile-time checking on the one field that must never leak.
       (CASE WHEN results.released_at IS NULL THEN '' ELSE results.content END)::text AS content,
       results.is_published, results.sent_at, results.parent_result_id,
       results.reveal_delay_minutes, results.released_at,
       gp.phase_type, gp.phase_number, u.username as gm_username,
       c.name as character_name,
       cp.part_number, cp.part_count, cp.unlocks_at
FROM action_results results
JOIN game_phases gp ON results.phase_id = gp.id
JOIN users u ON results.gm_user_id = u.id
LEFT JOIN characters c ON results.character_id = c.id
LEFT JOIN chain_position cp ON cp.id = results.id
WHERE results.game_id = $1 AND results.user_id = $2 AND results.is_published = true
ORDER BY gp.phase_number DESC, results.sent_at, results.id
`

type GetUserResultsParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

type GetUserResultsRow struct {
	ID                 int32              `json:"id"`
	GameID             int32              `json:"game_id"`
	UserID             int32              `json:"user_id"`
	PhaseID            int32              `json:"phase_id"`
	CharacterID        pgtype.Int4        `json:"character_id"`
	ActionSubmissionID pgtype.Int4        `json:"action_submission_id"`
	GmUserID           int32              `json:"gm_user_id"`
	Content            string             `json:"content"`
	IsPublished        pgtype.Bool        `json:"is_published"`
	SentAt             pgtype.Timestamptz `json:"sent_at"`
	ParentResultID     pgtype.Int4        `json:"parent_result_id"`
	RevealDelayMinutes pgtype.Int4        `json:"reveal_delay_minutes"`
	ReleasedAt         pgtype.Timestamptz `json:"released_at"`
	PhaseType          string             `json:"phase_type"`
	PhaseNumber        int32              `json:"phase_number"`
	GmUsername         string             `json:"gm_username"`
	CharacterName      pgtype.Text        `json:"character_name"`
	PartNumber         pgtype.Int4        `json:"part_number"`
	PartCount          pgtype.Int8        `json:"part_count"`
	UnlocksAt          pgtype.Timestamptz `json:"unlocks_at"`
}

// Columns are listed explicitly rather than using results.*, and that is a
// security decision, not a style one. A pending part IS returned to its
// recipient — the countdown placeholder needs the row to exist — with only its
// content withheld. `results.*` would put the real content on the row and leave
// nothing but Go discipline between it and the JSON encoder. Listing columns
// means the blanked content is the only content this query can ever emit.
//
// If you add a column to action_results, add it here too; it will not appear by
// itself. That is the intended trade-off.
// No released_at filter. Unreleased parts are returned deliberately so the
// player sees a placeholder counting down to the reveal (Design Decisions,
// "Locked-part UI"). The suspense comes from withholding the text, not the
// row's existence. The content CASE above is what enforces that — do not
// re-add a released_at filter here expecting it to be the gate.
//
// Ascending within a phase, unlike the GM-facing queries: a player reading a
// reveal delivered in several parts wants them in the order the GM sent them.
// Only published rows are returned here, so sent_at is always populated; id is
// the tiebreaker for results published in the same transaction.
func (q *Queries) GetUserResults(ctx context.Context, arg GetUserResultsParams) ([]GetUserResultsRow, error) {
	rows, err := q.db.Query(ctx, getUserResults, arg.GameID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserResultsRow
	for rows.Next() {
		var i GetUserResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.ActionSubmissionID,
			&i.GmUserID,
			&i.Content,
			&i.IsPublished,
			&i.SentAt,
			&i.ParentResultID,
			&i.RevealDelayMinutes,
			&i.ReleasedAt,
			&i.PhaseType,
			&i.PhaseNumber,
			&i.GmUsername,
			&i.CharacterName,
			&i.PartNumber,
			&i.PartCount,
			&i.UnlocksAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActionSubmissions = `-- name: ListAllActionSubmissions :many

SELECT acts.id, acts.game_id, acts.user_id, acts.phase_id, acts.character_id, acts.content, acts.submitted_at, acts.updated_at, u.username, c.name as character_name, gp.phase_type, gp.phase_number, gp.title as phase_title
FROM action_submissions acts
JOIN users u ON acts.user_id = u.id
JOIN game_phases gp ON acts.phase_id = gp.id
LEFT JOIN characters c ON acts.character_id = c.id
WHERE acts.game_id = $1
  AND (CASE WHEN $2 = 0 THEN TRUE ELSE acts.phase_id = $2 END)
ORDER BY gp.phase_number DESC, acts.submitted_at DESC
LIMIT $4 OFFSET $3
`

type ListAllActionSubmissionsParams struct {
	GameID       int32       `json:"game_id"`
	PhaseID      interface{} `json:"phase_id"`
	ResultOffset int32       `json:"result_offset"`
	ResultLimit  int32       `json:"result_limit"`
}

type ListAllActionSubmissionsRow struct {
	ID            int32              `json:"id"`
	GameID        int32              `json:"game_id"`
	UserID        int32              `json:"user_id"`
	PhaseID       int32              `json:"phase_id"`
	CharacterID   pgtype.Int4        `json:"character_id"`
	Content       string             `json:"content"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Username      string             `json:"username"`
	CharacterName pgtype.Text        `json:"character_name"`
	PhaseType     string             `json:"phase_type"`
	PhaseNumber   int32              `json:"phase_number"`
	PhaseTitle    string             `json:"phase_title"`
}

// Audience Participation Queries (Action Viewing)
// List all action submissions for a game (for audience/GM)
//
// Deliberately does NOT join action_results. Results are meaningful per phase,
// not per submission: a player submits 0-1 actions but may receive several
// results (staged reveals), so joining them fanned one submission into a row
// per result and desynced LIMIT/OFFSET from CountAllActionSubmissions, which
// counts submissions alone. Consumers read results from the per-phase results
// endpoints instead.
func (q *Queries) ListAllActionSubmissions(ctx context.Context, arg ListAllActionSubmissionsParams) ([]ListAllActionSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listAllActionSubmissions,
		arg.GameID,
		arg.PhaseID,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllActionSubmissionsRow
	for rows.Next() {
		var i ListAllActionSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.Content,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.CharacterName,
			&i.PhaseType,
			&i.PhaseNumber,
			&i.PhaseTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishActionResult = `-- name: PublishActionResult :many
WITH RECURSIVE anchor AS (
    -- Climb to the head, so publishing from any member publishes the chain.
    SELECT a.id, a.parent_result_id
    FROM action_results a
    WHERE a.id = $1
    UNION ALL
    SELECT p.id, p.parent_result_id
    FROM action_results p
    JOIN anchor n ON n.parent_result_id = p.id
),
chain AS (
    SELECT r.id
    FROM action_results r
    WHERE r.id = (SELECT id FROM anchor WHERE parent_result_id IS NULL)
    UNION ALL
    SELECT child.id
    FROM action_results child
    JOIN chain c ON child.parent_result_id = c.id
)
UPDATE action_results
SET is_published = true,
    sent_at = COALESCE(sent_at, NOW()),
    released_at = CASE WHEN parent_result_id IS NULL THEN COALESCE(released_at, NOW()) ELSE released_at END
WHERE id IN (SELECT id FROM chain)
RETURNING id, game_id, user_id, phase_id, character_id, action_submission_id, gm_user_id, content, is_published, sent_at, parent_result_id, reveal_delay_minutes, released_at
`

// Publishing a chain head (or an ordinary single result) makes it visible at
// once. A non-head staged part keeps released_at NULL so the release worker
// reveals it when its delay elapses — that is the whole feature, so the
// parent_result_id check here is load-bearing.
//
// Publishes the WHOLE chain, not just the row named. A chain built up part by
// part (AppendStagedPart) has followers that are still drafts at publish time,
// and GetDueStagedParts only considers is_published rows — so publishing the
// head alone would strand every follower permanently, with no repair path short
// of manual SQL. Publishing one row was sufficient only while chains were
// created whole and published together.
//
// The descend CTE walks from the named row's chain head down through every
// follower, so this behaves identically for an ordinary single result: a row
// with no parent and no children is a chain of one.
// Returns every published row, head first. The service hands the caller back
// the row it named; the rest are returned so a caller can see what else went
// out with it.
func (q *Queries) PublishActionResult(ctx context.Context, id int32) ([]ActionResult, error) {
	rows, err := q.db.Query(ctx, publishActionResult, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionResult
	for rows.Next() {
		var i ActionResult
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.ActionSubmissionID,
			&i.GmUserID,
			&i.Content,
			&i.IsPublished,
			&i.SentAt,
			&i.ParentResultID,
			&i.RevealDelayMinutes,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishAllPhaseResults = `-- name: PublishAllPhaseResults :exec
UPDATE action_results
SET is_published = true,
    sent_at = COALESCE(sent_at, NOW()),
    released_at = CASE WHEN parent_result_id IS NULL THEN COALESCE(released_at, NOW()) ELSE released_at END
WHERE phase_id = $1 AND is_published = false
`

// Same head-only release rule as PublishActionResult. Bulk-publishing ten
// chains starts ten independent timers from this instant; the delays are
// per-chain, so parts fire on their own schedules from here.
func (q *Queries) PublishAllPhaseResults(ctx context.Context, phaseID int32) error {
	_, err := q.db.Exec(ctx, publishAllPhaseResults, phaseID)
	return err
}

const releaseStagedPart = `-- name: ReleaseStagedPart :one
UPDATE action_results
SET released_at = NOW()
WHERE id = $1 AND released_at IS NULL
RETURNING id, game_id, user_id, phase_id, character_id, action_submission_id, gm_user_id, content, is_published, sent_at, parent_result_id, reveal_delay_minutes, released_at
`

// Reveal one part. Guarded on released_at IS NULL so a double-tick or a
// concurrent worker cannot re-release (and re-notify) an already-visible part;
// the second caller gets no row back.
func (q *Queries) ReleaseStagedPart(ctx context.Context, id int32) (ActionResult, error) {
	row := q.db.QueryRow(ctx, releaseStagedPart, id)
	var i ActionResult
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.ActionSubmissionID,
		&i.GmUserID,
		&i.Content,
		&i.IsPublished,
		&i.SentAt,
		&i.ParentResultID,
		&i.RevealDelayMinutes,
		&i.ReleasedAt,
	)
	return i, err
}

const submitAction = `-- name: SubmitAction :one
INSERT INTO action_submissions (game_id, user_id, phase_id, character_id, content, submitted_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (game_id, user_id, phase_id)
DO UPDATE SET content = $5, character_id = $4,
              submitted_at = COALESCE(action_submissions.submitted_at, NOW()),
              updated_at = NOW()
RETURNING id, game_id, user_id, phase_id, character_id, content, submitted_at, updated_at
`

type SubmitActionParams struct {
	GameID      int32       `json:"game_id"`
	UserID      int32       `json:"user_id"`
	PhaseID     int32       `json:"phase_id"`
	CharacterID pgtype.Int4 `json:"character_id"`
	Content     string      `json:"content"`
}

// submitted_at is stamped once on insert and preserved across edits: it marks
// when the player first submitted, not when they last touched the text.
// updated_at carries the latter, and the two being equal is how the handler
// detects a first-time submission for GM notification.
func (q *Queries) SubmitAction(ctx context.Context, arg SubmitActionParams) (ActionSubmission, error) {
	row := q.db.QueryRow(ctx, submitAction,
		arg.GameID,
		arg.UserID,
		arg.PhaseID,
		arg.CharacterID,
		arg.Content,
	)
	var i ActionSubmission
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.Content,
		&i.SubmittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateActionResult = `-- name: UpdateActionResult :one
UPDATE action_results
SET content = $2
WHERE id = $1 AND is_published = false
RETURNING id, game_id, user_id, phase_id, character_id, action_submission_id, gm_user_id, content, is_published, sent_at, parent_result_id, reveal_delay_minutes, released_at
`

type UpdateActionResultParams struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateActionResult(ctx context.Context, arg UpdateActionResultParams) (ActionResult, error) {
	row := q.db.QueryRow(ctx, updateActionResult, arg.ID, arg.Content)
	var i ActionResult
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.ActionSubmissionID,
		&i.GmUserID,
		&i.Content,
		&i.IsPublished,
		&i.SentAt,
		&i.ParentResultID,
		&i.RevealDelayMinutes,
		&i.ReleasedAt,
	)
	return i, err
}

const updatePhase = `-- name: UpdatePhase :one

UPDATE game_phases
SET title = $2, description = $3, start_time = $4, end_time = $5, deadline = $6
WHERE id = $1
RETURNING id, game_id, phase_type, phase_number, title, description, start_time, end_time, deadline, is_active, is_published, activated_at, created_at
`

type UpdatePhaseParams struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
}

// Additional queries for comprehensive phase management
func (q *Queries) UpdatePhase(ctx context.Context, arg UpdatePhaseParams) (GamePhase, error) {
	row := q.db.QueryRow(ctx, updatePhase,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.Deadline,
	)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.IsPublished,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePhaseDeadline = `-- name: UpdatePhaseDeadline :one
UPDATE game_phases
SET deadline = $2
WHERE id = $1
RETURNING id, game_id, phase_type, phase_number, title, description, start_time, end_time, deadline, is_active, is_published, activated_at, created_at
`

type UpdatePhaseDeadlineParams struct {
	ID       int32              `json:"id"`
	Deadline pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) UpdatePhaseDeadline(ctx context.Context, arg UpdatePhaseDeadlineParams) (GamePhase, error) {
	row := q.db.QueryRow(ctx, updatePhaseDeadline, arg.ID, arg.Deadline)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.IsPublished,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateStagedPartDelay = `-- name: UpdateStagedPartDelay :one
UPDATE action_results
SET reveal_delay_minutes = $2
WHERE id = $1 AND released_at IS NULL AND parent_result_id IS NOT NULL
RETURNING id, game_id, user_id, phase_id, character_id, action_submission_id, gm_user_id, content, is_published, sent_at, parent_result_id, reveal_delay_minutes, released_at
`

type UpdateStagedPartDelayParams struct {
	ID                 int32       `json:"id"`
	RevealDelayMinutes pgtype.Int4 `json:"reveal_delay_minutes"`
}

// Retime a staged part that has not yet been revealed.
//
// Guarded on released_at rather than is_published, for the same reason as
// DeleteStagedPart: a pending part is *published* but not yet *released*, so an
// `is_published = false` guard would match nothing and silently retime zero
// rows. This guard admits drafts and pending parts alike and refuses a part the
// player has already read — which is the rule "editable until it releases".
//
// parent_result_id IS NOT NULL excludes the chain head, which has no parent to
// measure a delay from; action_results_delay_requires_parent would reject a
// delay on it anyway, but failing here gives the caller a row count instead of
// a constraint violation.
//
// No rescheduling is needed after this. GetDueStagedParts recomputes due-ness
// from parent.released_at + reveal_delay_minutes on every tick, so the new
// delay is honoured on the next tick. Backdating a pending part below the
// elapsed time therefore releases it on that tick, which is intended.
func (q *Queries) UpdateStagedPartDelay(ctx context.Context, arg UpdateStagedPartDelayParams) (ActionResult, error) {
	row := q.db.QueryRow(ctx, updateStagedPartDelay, arg.ID, arg.RevealDelayMinutes)
	var i ActionResult
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.ActionSubmissionID,
		&i.GmUserID,
		&i.Content,
		&i.IsPublished,
		&i.SentAt,
		&i.ParentResultID,
		&i.RevealDelayMinutes,
		&i.ReleasedAt,
	)
	return i, err
}
