// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: polls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPoll = `-- name: CreatePoll :one

INSERT INTO common_room_polls (
    game_id,
    phase_id,
    created_by_user_id,
    created_by_character_id,
    question,
    description,
    deadline,
    show_individual_votes,
    allow_other_option,
    hide_results_from_players,
    allow_audience_voting,
    show_running_totals_to_players
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, game_id, phase_id, created_by_user_id, created_by_character_id, question, description, deadline, show_individual_votes, allow_other_option, hide_results_from_players, allow_audience_voting, show_running_totals_to_players, is_deleted, created_at, updated_at
`

type CreatePollParams struct {
	GameID                     int32              `json:"game_id"`
	PhaseID                    pgtype.Int4        `json:"phase_id"`
	CreatedByUserID            int32              `json:"created_by_user_id"`
	CreatedByCharacterID       pgtype.Int4        `json:"created_by_character_id"`
	Question                   string             `json:"question"`
	Description                pgtype.Text        `json:"description"`
	Deadline                   pgtype.Timestamptz `json:"deadline"`
	ShowIndividualVotes        pgtype.Bool        `json:"show_individual_votes"`
	AllowOtherOption           pgtype.Bool        `json:"allow_other_option"`
	HideResultsFromPlayers     bool               `json:"hide_results_from_players"`
	AllowAudienceVoting        bool               `json:"allow_audience_voting"`
	ShowRunningTotalsToPlayers bool               `json:"show_running_totals_to_players"`
}

// ================================================
// COMMON ROOM POLLS
// ================================================
func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (CommonRoomPoll, error) {
	row := q.db.QueryRow(ctx, createPoll,
		arg.GameID,
		arg.PhaseID,
		arg.CreatedByUserID,
		arg.CreatedByCharacterID,
		arg.Question,
		arg.Description,
		arg.Deadline,
		arg.ShowIndividualVotes,
		arg.AllowOtherOption,
		arg.HideResultsFromPlayers,
		arg.AllowAudienceVoting,
		arg.ShowRunningTotalsToPlayers,
	)
	var i CommonRoomPoll
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.CreatedByUserID,
		&i.CreatedByCharacterID,
		&i.Question,
		&i.Description,
		&i.Deadline,
		&i.ShowIndividualVotes,
		&i.AllowOtherOption,
		&i.HideResultsFromPlayers,
		&i.AllowAudienceVoting,
		&i.ShowRunningTotalsToPlayers,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPollOption = `-- name: CreatePollOption :one

INSERT INTO poll_options (poll_id, option_text, display_order)
VALUES ($1, $2, $3)
RETURNING id, poll_id, option_text, display_order, created_at
`

type CreatePollOptionParams struct {
	PollID       int32  `json:"poll_id"`
	OptionText   string `json:"option_text"`
	DisplayOrder int32  `json:"display_order"`
}

// ================================================
// POLL OPTIONS
// ================================================
func (q *Queries) CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (PollOption, error) {
	row := q.db.QueryRow(ctx, createPollOption, arg.PollID, arg.OptionText, arg.DisplayOrder)
	var i PollOption
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.OptionText,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deletePollOption = `-- name: DeletePollOption :exec
DELETE FROM poll_options
WHERE id = $1
`

func (q *Queries) DeletePollOption(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePollOption, id)
	return err
}

const deleteVote = `-- name: DeleteVote :exec
DELETE FROM poll_votes
WHERE id = $1
`

func (q *Queries) DeleteVote(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteVote, id)
	return err
}

const getActivePollsForGame = `-- name: GetActivePollsForGame :many

SELECT id, game_id, phase_id, created_by_user_id, created_by_character_id, question, description, deadline, show_individual_votes, allow_other_option, hide_results_from_players, allow_audience_voting, show_running_totals_to_players, is_deleted, created_at, updated_at FROM common_room_polls
WHERE game_id = $1
  AND is_deleted = FALSE
  AND deadline > NOW()
ORDER BY deadline ASC
`

// ================================================
// UTILITY QUERIES
// ================================================
// Get all active (not expired, not deleted) polls for a game
func (q *Queries) GetActivePollsForGame(ctx context.Context, gameID int32) ([]CommonRoomPoll, error) {
	rows, err := q.db.Query(ctx, getActivePollsForGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommonRoomPoll
	for rows.Next() {
		var i CommonRoomPoll
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.CreatedByUserID,
			&i.CreatedByCharacterID,
			&i.Question,
			&i.Description,
			&i.Deadline,
			&i.ShowIndividualVotes,
			&i.AllowOtherOption,
			&i.HideResultsFromPlayers,
			&i.AllowAudienceVoting,
			&i.ShowRunningTotalsToPlayers,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredPolls = `-- name: GetExpiredPolls :many
SELECT id, game_id, phase_id, created_by_user_id, created_by_character_id, question, description, deadline, show_individual_votes, allow_other_option, hide_results_from_players, allow_audience_voting, show_running_totals_to_players, is_deleted, created_at, updated_at FROM common_room_polls
WHERE is_deleted = FALSE
  AND deadline <= NOW()
ORDER BY deadline DESC
`

// For cleanup or notification jobs
func (q *Queries) GetExpiredPolls(ctx context.Context) ([]CommonRoomPoll, error) {
	rows, err := q.db.Query(ctx, getExpiredPolls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommonRoomPoll
	for rows.Next() {
		var i CommonRoomPoll
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.CreatedByUserID,
			&i.CreatedByCharacterID,
			&i.Question,
			&i.Description,
			&i.Deadline,
			&i.ShowIndividualVotes,
			&i.AllowOtherOption,
			&i.HideResultsFromPlayers,
			&i.AllowAudienceVoting,
			&i.ShowRunningTotalsToPlayers,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptionVoteCount = `-- name: GetOptionVoteCount :one
SELECT COUNT(*) as vote_count
FROM poll_votes
WHERE poll_id = $1
  AND selected_option_id = $2
`

type GetOptionVoteCountParams struct {
	PollID           int32       `json:"poll_id"`
	SelectedOptionID pgtype.Int4 `json:"selected_option_id"`
}

func (q *Queries) GetOptionVoteCount(ctx context.Context, arg GetOptionVoteCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getOptionVoteCount, arg.PollID, arg.SelectedOptionID)
	var vote_count int64
	err := row.Scan(&vote_count)
	return vote_count, err
}

const getOtherResponses = `-- name: GetOtherResponses :many
SELECT
    pv.id,
    pv.user_id,
    pv.other_response,
    pv.created_at,
    u.username,
    c.name as character_name,
    gp.role as voter_role
FROM poll_votes pv
JOIN users u ON pv.user_id = u.id
LEFT JOIN characters c ON c.id = (
    SELECT id FROM characters
    WHERE game_id = (SELECT game_id FROM common_room_polls WHERE id = pv.poll_id)
      AND user_id = pv.user_id
    LIMIT 1
)
LEFT JOIN game_participants gp
    ON gp.game_id = (SELECT game_id FROM common_room_polls WHERE id = pv.poll_id)
   AND gp.user_id = pv.user_id
   AND gp.status = 'active'
WHERE pv.poll_id = $1
  AND pv.other_response IS NOT NULL
ORDER BY pv.created_at ASC
`

type GetOtherResponsesRow struct {
	ID            int32              `json:"id"`
	UserID        int32              `json:"user_id"`
	OtherResponse pgtype.Text        `json:"other_response"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Username      string             `json:"username"`
	CharacterName pgtype.Text        `json:"character_name"`
	VoterRole     pgtype.Text        `json:"voter_role"`
}

// Get all "other" text responses
func (q *Queries) GetOtherResponses(ctx context.Context, pollID int32) ([]GetOtherResponsesRow, error) {
	rows, err := q.db.Query(ctx, getOtherResponses, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOtherResponsesRow
	for rows.Next() {
		var i GetOtherResponsesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OtherResponse,
			&i.CreatedAt,
			&i.Username,
			&i.CharacterName,
			&i.VoterRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOtherVoteCount = `-- name: GetOtherVoteCount :one
SELECT COUNT(*) as vote_count
FROM poll_votes
WHERE poll_id = $1
  AND other_response IS NOT NULL
`

func (q *Queries) GetOtherVoteCount(ctx context.Context, pollID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getOtherVoteCount, pollID)
	var vote_count int64
	err := row.Scan(&vote_count)
	return vote_count, err
}

const getPoll = `-- name: GetPoll :one
SELECT id, game_id, phase_id, created_by_user_id, created_by_character_id, question, description, deadline, show_individual_votes, allow_other_option, hide_results_from_players, allow_audience_voting, show_running_totals_to_players, is_deleted, created_at, updated_at FROM common_room_polls
WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetPoll(ctx context.Context, id int32) (CommonRoomPoll, error) {
	row := q.db.QueryRow(ctx, getPoll, id)
	var i CommonRoomPoll
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.CreatedByUserID,
		&i.CreatedByCharacterID,
		&i.Question,
		&i.Description,
		&i.Deadline,
		&i.ShowIndividualVotes,
		&i.AllowOtherOption,
		&i.HideResultsFromPlayers,
		&i.AllowAudienceVoting,
		&i.ShowRunningTotalsToPlayers,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPollOptions = `-- name: GetPollOptions :many
SELECT id, poll_id, option_text, display_order, created_at FROM poll_options
WHERE poll_id = $1
ORDER BY display_order ASC
`

func (q *Queries) GetPollOptions(ctx context.Context, pollID int32) ([]PollOption, error) {
	rows, err := q.db.Query(ctx, getPollOptions, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollOption
	for rows.Next() {
		var i PollOption
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.OptionText,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollResultsSummary = `-- name: GetPollResultsSummary :many

SELECT
    po.id as option_id,
    po.option_text,
    po.display_order,
    COUNT(pv.id) as vote_count
FROM poll_options po
LEFT JOIN poll_votes pv ON po.id = pv.selected_option_id
WHERE po.poll_id = $1
GROUP BY po.id, po.option_text, po.display_order
ORDER BY po.display_order ASC
`

type GetPollResultsSummaryRow struct {
	OptionID     int32  `json:"option_id"`
	OptionText   string `json:"option_text"`
	DisplayOrder int32  `json:"display_order"`
	VoteCount    int64  `json:"vote_count"`
}

// ================================================
// POLL RESULTS (with visibility logic)
// ================================================
// Get vote counts per option for results display
func (q *Queries) GetPollResultsSummary(ctx context.Context, pollID int32) ([]GetPollResultsSummaryRow, error) {
	rows, err := q.db.Query(ctx, getPollResultsSummary, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPollResultsSummaryRow
	for rows.Next() {
		var i GetPollResultsSummaryRow
		if err := rows.Scan(
			&i.OptionID,
			&i.OptionText,
			&i.DisplayOrder,
			&i.VoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollVoteCount = `-- name: GetPollVoteCount :one
SELECT COUNT(*) as vote_count
FROM poll_votes
WHERE poll_id = $1
`

func (q *Queries) GetPollVoteCount(ctx context.Context, pollID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getPollVoteCount, pollID)
	var vote_count int64
	err := row.Scan(&vote_count)
	return vote_count, err
}

const getPollVotesWithDetails = `-- name: GetPollVotesWithDetails :many
SELECT
    pv.id,
    pv.user_id,
    pv.selected_option_id,
    pv.other_response,
    pv.created_at,
    u.username,
    c.name as character_name,
    gp.role as voter_role
FROM poll_votes pv
JOIN users u ON pv.user_id = u.id
LEFT JOIN characters c ON c.id = (
    SELECT id FROM characters
    WHERE game_id = (SELECT game_id FROM common_room_polls WHERE id = pv.poll_id)
      AND user_id = pv.user_id
    LIMIT 1
)
LEFT JOIN game_participants gp
    ON gp.game_id = (SELECT game_id FROM common_room_polls WHERE id = pv.poll_id)
   AND gp.user_id = pv.user_id
   AND gp.status = 'active'
WHERE pv.poll_id = $1
ORDER BY pv.created_at ASC
`

type GetPollVotesWithDetailsRow struct {
	ID               int32              `json:"id"`
	UserID           int32              `json:"user_id"`
	SelectedOptionID pgtype.Int4        `json:"selected_option_id"`
	OtherResponse    pgtype.Text        `json:"other_response"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Username         string             `json:"username"`
	CharacterName    pgtype.Text        `json:"character_name"`
	VoterRole        pgtype.Text        `json:"voter_role"`
}

// Get detailed vote information (for when show_individual_votes = true)
func (q *Queries) GetPollVotesWithDetails(ctx context.Context, pollID int32) ([]GetPollVotesWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getPollVotesWithDetails, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPollVotesWithDetailsRow
	for rows.Next() {
		var i GetPollVotesWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SelectedOptionID,
			&i.OtherResponse,
			&i.CreatedAt,
			&i.Username,
			&i.CharacterName,
			&i.VoterRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoteByPollAndUser = `-- name: GetVoteByPollAndUser :one
SELECT id, poll_id, user_id, selected_option_id, other_response, created_at, updated_at FROM poll_votes
WHERE poll_id = $1
  AND user_id = $2
`

type GetVoteByPollAndUserParams struct {
	PollID int32 `json:"poll_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetVoteByPollAndUser(ctx context.Context, arg GetVoteByPollAndUserParams) (PollVote, error) {
	row := q.db.QueryRow(ctx, getVoteByPollAndUser, arg.PollID, arg.UserID)
	var i PollVote
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.UserID,
		&i.SelectedOptionID,
		&i.OtherResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasUserVoted = `-- name: HasUserVoted :one
SELECT EXISTS(
    SELECT 1 FROM poll_votes
    WHERE poll_id = $1
      AND user_id = $2
) as has_voted
`

type HasUserVotedParams struct {
	PollID int32 `json:"poll_id"`
	UserID int32 `json:"user_id"`
}

// Check if user has already voted in a poll
func (q *Queries) HasUserVoted(ctx context.Context, arg HasUserVotedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserVoted, arg.PollID, arg.UserID)
	var has_voted bool
	err := row.Scan(&has_voted)
	return has_voted, err
}

const listPollsByGame = `-- name: ListPollsByGame :many
SELECT id, game_id, phase_id, created_by_user_id, created_by_character_id, question, description, deadline, show_individual_votes, allow_other_option, hide_results_from_players, allow_audience_voting, show_running_totals_to_players, is_deleted, created_at, updated_at FROM common_room_polls
WHERE game_id = $1
  AND is_deleted = FALSE
  AND (
    -- Include expired polls if requested
    $2 = true OR deadline > NOW()
  )
ORDER BY deadline ASC
`

type ListPollsByGameParams struct {
	GameID  int32       `json:"game_id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) ListPollsByGame(ctx context.Context, arg ListPollsByGameParams) ([]CommonRoomPoll, error) {
	rows, err := q.db.Query(ctx, listPollsByGame, arg.GameID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommonRoomPoll
	for rows.Next() {
		var i CommonRoomPoll
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.CreatedByUserID,
			&i.CreatedByCharacterID,
			&i.Question,
			&i.Description,
			&i.Deadline,
			&i.ShowIndividualVotes,
			&i.AllowOtherOption,
			&i.HideResultsFromPlayers,
			&i.AllowAudienceVoting,
			&i.ShowRunningTotalsToPlayers,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollsByPhase = `-- name: ListPollsByPhase :many
SELECT id, game_id, phase_id, created_by_user_id, created_by_character_id, question, description, deadline, show_individual_votes, allow_other_option, hide_results_from_players, allow_audience_voting, show_running_totals_to_players, is_deleted, created_at, updated_at FROM common_room_polls
WHERE game_id = $1
  AND phase_id = $2
  AND is_deleted = FALSE
ORDER BY created_at DESC
`

type ListPollsByPhaseParams struct {
	GameID  int32       `json:"game_id"`
	PhaseID pgtype.Int4 `json:"phase_id"`
}

func (q *Queries) ListPollsByPhase(ctx context.Context, arg ListPollsByPhaseParams) ([]CommonRoomPoll, error) {
	rows, err := q.db.Query(ctx, listPollsByPhase, arg.GameID, arg.PhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommonRoomPoll
	for rows.Next() {
		var i CommonRoomPoll
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.CreatedByUserID,
			&i.CreatedByCharacterID,
			&i.Question,
			&i.Description,
			&i.Deadline,
			&i.ShowIndividualVotes,
			&i.AllowOtherOption,
			&i.HideResultsFromPlayers,
			&i.AllowAudienceVoting,
			&i.ShowRunningTotalsToPlayers,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePoll = `-- name: SoftDeletePoll :exec
UPDATE common_room_polls
SET is_deleted = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeletePoll(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeletePoll, id)
	return err
}

const submitVote = `-- name: SubmitVote :one

INSERT INTO poll_votes (
    poll_id,
    user_id,
    selected_option_id,
    other_response
)
VALUES ($1, $2, $3, $4)
RETURNING id, poll_id, user_id, selected_option_id, other_response, created_at, updated_at
`

type SubmitVoteParams struct {
	PollID           int32       `json:"poll_id"`
	UserID           int32       `json:"user_id"`
	SelectedOptionID pgtype.Int4 `json:"selected_option_id"`
	OtherResponse    pgtype.Text `json:"other_response"`
}

// ================================================
// POLL VOTES
// ================================================
func (q *Queries) SubmitVote(ctx context.Context, arg SubmitVoteParams) (PollVote, error) {
	row := q.db.QueryRow(ctx, submitVote,
		arg.PollID,
		arg.UserID,
		arg.SelectedOptionID,
		arg.OtherResponse,
	)
	var i PollVote
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.UserID,
		&i.SelectedOptionID,
		&i.OtherResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePoll = `-- name: UpdatePoll :one
UPDATE common_room_polls
SET question = $2,
    description = $3,
    deadline = $4,
    show_individual_votes = $5,
    allow_other_option = $6,
    hide_results_from_players = $7,
    allow_audience_voting = $8,
    show_running_totals_to_players = $9,
    updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, game_id, phase_id, created_by_user_id, created_by_character_id, question, description, deadline, show_individual_votes, allow_other_option, hide_results_from_players, allow_audience_voting, show_running_totals_to_players, is_deleted, created_at, updated_at
`

type UpdatePollParams struct {
	ID                         int32              `json:"id"`
	Question                   string             `json:"question"`
	Description                pgtype.Text        `json:"description"`
	Deadline                   pgtype.Timestamptz `json:"deadline"`
	ShowIndividualVotes        pgtype.Bool        `json:"show_individual_votes"`
	AllowOtherOption           pgtype.Bool        `json:"allow_other_option"`
	HideResultsFromPlayers     bool               `json:"hide_results_from_players"`
	AllowAudienceVoting        bool               `json:"allow_audience_voting"`
	ShowRunningTotalsToPlayers bool               `json:"show_running_totals_to_players"`
}

func (q *Queries) UpdatePoll(ctx context.Context, arg UpdatePollParams) (CommonRoomPoll, error) {
	row := q.db.QueryRow(ctx, updatePoll,
		arg.ID,
		arg.Question,
		arg.Description,
		arg.Deadline,
		arg.ShowIndividualVotes,
		arg.AllowOtherOption,
		arg.HideResultsFromPlayers,
		arg.AllowAudienceVoting,
		arg.ShowRunningTotalsToPlayers,
	)
	var i CommonRoomPoll
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.CreatedByUserID,
		&i.CreatedByCharacterID,
		&i.Question,
		&i.Description,
		&i.Deadline,
		&i.ShowIndividualVotes,
		&i.AllowOtherOption,
		&i.HideResultsFromPlayers,
		&i.AllowAudienceVoting,
		&i.ShowRunningTotalsToPlayers,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVote = `-- name: UpdateVote :one
UPDATE poll_votes
SET selected_option_id = $2,
    other_response = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, poll_id, user_id, selected_option_id, other_response, created_at, updated_at
`

type UpdateVoteParams struct {
	ID               int32       `json:"id"`
	SelectedOptionID pgtype.Int4 `json:"selected_option_id"`
	OtherResponse    pgtype.Text `json:"other_response"`
}

func (q *Queries) UpdateVote(ctx context.Context, arg UpdateVoteParams) (PollVote, error) {
	row := q.db.QueryRow(ctx, updateVote, arg.ID, arg.SelectedOptionID, arg.OtherResponse)
	var i PollVote
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.UserID,
		&i.SelectedOptionID,
		&i.OtherResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
